const q=s=>document.querySelector(s),C=q('#game'),x=C.getContext('2d',{alpha:false});x.imageSmoothingEnabled=false;
const W={w:1280,h:720,g:553,n:7},T={blue:{c:'#55c8ff',d:'#133b54',s:74,k:0,v:1},red:{c:'#ff625f',d:'#571f22',s:1206,k:0,v:-1}},K={1:{n:'RIFLEMAN',h:100,s:43,r:235,d:19,m:7,l:1.45,f:.73,g:12},2:{n:'ASSAULT',h:115,s:53,r:185,d:16,m:9,l:1.2,f:.52,g:14},3:{n:'GRENADIER',h:125,s:38,r:220,d:22,m:6,l:1.6,f:.88,g:8}},A={idle:[0,7,8,1],run:[1,8,12,1],shot:[2,4,13,0],recharge:[3,13,11,0],grenade:[4,9,12,0],hurt:[5,3,12,0],dead:[6,4,9,0]},M={1:{idle:7,run:8,shot:4,recharge:13,grenade:9,hurt:3,dead:4},2:{idle:9,run:8,shot:4,recharge:7,grenade:16,hurt:3,dead:4},3:{idle:7,run:6,shot:4,recharge:8,grenade:8,hurt:4,dead:5}},I={},S=[],V=new Map(),E=[],R=[],G=[],Q=Array.from({length:7},(_,i)=>({o:i<3?'blue':i>3?'red':'neutral',m:0,p:''}));
let go=0,win=0,last=performance.now(),cam=640,shake=0,round=1,cap=0,fps=60,idx=0;const demo=new URLSearchParams(location.search).get('demo')==='1',live=new URLSearchParams(location.search).get('live')==='1';
const U={bc:q('#blue-count'),rc:q('#red-count'),bk:q('#blue-kills'),rk:q('#red-kills'),ss:q('#sector-strip'),mo:q('#mode-label'),ro:q('#round-label'),fp:q('#fps-label'),fe:q('#kill-feed'),st:q('#start-card'),wc:q('#winner-card'),wt:q('#winner-title'),ld:q('#loading'),lp:q('#load-progress'),pa:q('#test-panel')};
function resize(){let d=Math.min(2,devicePixelRatio||1);C.width=innerWidth*d;C.height=innerHeight*d;x.imageSmoothingEnabled=false}addEventListener('resize',resize);resize();
async function load(){let a=[['1','assets/soldiers/soldier_1_atlas.webp'],['2','assets/soldiers/soldier_2_atlas.webp'],['3','assets/soldiers/soldier_3_atlas.webp'],['e','assets/vfx/explosion.webp']],n=0;await Promise.all(a.map(([k,s])=>new Promise((ok,no)=>{let i=new Image;i.onload=()=>{I[k]=i;U.lp.textContent=Math.round(++n/a.length*100)+'%';ok()};i.onerror=()=>no(Error(s));i.src=s})));U.ld.classList.add('hidden');U.mo.textContent=live?'LIVE MODE':demo?'DEMO MODE':'TEST MODE';if(demo){start(1);U.st.classList.add('hidden')}}
function feed(t,s){let e=document.createElement('div');e.className='kill-item '+t;e.textContent=s;U.fe.prepend(e);while(U.fe.children.length>6)U.fe.lastChild.remove();setTimeout(()=>e.remove(),4200)}
class Soldier{constructor(u,t,k,b=0){this.u=u;this.t=t;this.k=k;this.z=K[k];this.b=b;this.x=T[t].s+Math.random()*30-15;this.y=W.g+Math.random()*16-8;this.h=this.H=this.z.h;this.a=this.z.m;this.s='run';this.at=0;this.cd=Math.random()*.6;this.gc=3+Math.random()*5;this.tar=0;this.dead=0;this.dt=0;this.done=0;this.arm=0;this.follow=0;this.sc=.82+Math.random()*.08}
set(s){if(this.s!==s){this.s=s;this.at=0;this.done=0}} prog(){let a=A[this.s],f=M[this.k][this.s];return Math.min(1,this.at/(f/a[2]))} near(){let z=0,d=1e9;for(let s of S)if(!s.dead&&s.t!==this.t){let n=Math.abs(s.x-this.x)+Math.abs(s.y-this.y)*.35;if(n<d)d=n,z=s}return this.tar=z}
update(d){this.at+=d;if(this.dead){this.dt+=d;return}this.cd=Math.max(0,this.cd-d);this.gc=Math.max(0,this.gc-d);if(this.s==='hurt'){if(this.prog()>=1)this.set('idle');return}if(this.s==='recharge'){if(this.prog()>=1)this.a=this.z.m,this.set('idle');return}if(this.s==='shot'){if(!this.done&&this.prog()>.38)this.fire(),this.done=1;if(this.prog()>=1)this.set('idle');return}if(this.s==='grenade'){if(!this.done&&this.prog()>.48)this.throw(),this.done=1;if(this.prog()>=1)this.set('idle');return}let e=this.tar&&!this.tar.dead?this.tar:this.near();if(!e)return this.move(d);let dist=Math.abs(e.x-this.x);if(this.gc<=0&&dist>90&&dist<265&&Math.random()<d*.22)return this.set('grenade');if(dist<=this.z.r){if(this.a<=0)return this.set('recharge');if(this.cd<=0)return this.set('shot');this.set('idle')}else this.move(d)}
move(d){this.set('run');let v=this.z.s;if(Math.abs(this.x-front())>360)v*=1.28;this.x=Math.max(36,Math.min(1244,this.x+T[this.t].v*v*d))}fire(){let e=this.tar&&!this.tar.dead?this.tar:this.near();if(!e)return;this.a--;this.cd=this.z.f*(.88+Math.random()*.25);R.push({a:this.x+T[this.t].v*18,b:this.y-39,c:e.x,d:e.y-32,l:.09,t:this.t});E.push({q:'m',x:this.x+T[this.t].v*28,y:this.y-39,l:.08,t:this.t});if(Math.random()<(this.k===1?.74:this.k===2?.62:.68))e.hit(this.z.d*(.82+Math.random()*.35),this)}throw(){let e=this.tar&&!this.tar.dead?this.tar:0,tx=e?e.x:this.x+T[this.t].v*190;this.gc=this.z.g*(.85+Math.random()*.35);G.push({x:this.x,y:this.y-42,sx:this.x,sy:this.y-42,tx,ty:W.g-5,p:0,d:.7+Math.random()*.2,t:this.t,o:this})}
hit(n,a){let z=Math.min(this.arm,n*.45);this.arm-=z;this.h-=n-z;if(this.h<=0){this.h=0;this.dead=1;this.set('dead');if(a){T[a.t].k++;feed(a.t,`${a.u} ▸ ${this.u}`)}}else if(!['grenade','recharge'].includes(this.s))this.set('hurt')}heal(n){if(!this.dead){this.h=Math.min(this.H,this.h+n);E.push({q:'h',x:this.x,y:this.y-58,l:.55})}}boost(){if(!this.follow&&!this.dead){this.follow=1;this.H+=20;this.h+=20;this.arm+=15;E.push({q:'f',x:this.x,y:this.y-66,l:.8})}}
draw(){let im=I[this.k],a=A[this.s],f=M[this.k][this.s];if(!im)return;let n=Math.floor(this.at*a[2]);n=a[3]?n%f:Math.min(f-1,n);let z=128*this.sc;x.save();x.translate(this.x,this.y);if(this.t==='red')x.scale(-1,1);x.drawImage(im,n*64,a[0]*64,64,64,-z/2,-z+17,z,z);x.restore();if(!this.dead){let y=this.y-100*this.sc;x.fillStyle='#000a';x.fillRect(this.x-29,y,58,4);x.fillStyle=T[this.t].c;x.fillRect(this.x-29,y,58*this.h/this.H,4);x.font='bold 9px system-ui';x.textAlign='center';x.fillStyle='#fff';x.fillText(this.u,this.x,y-5);x.font='7px system-ui';x.fillStyle='#cbd2d4';x.fillText(this.z.n,this.x,y+14)}}}
function count(){let b=0,r=0;for(let s of S)if(!s.dead)s.t==='blue'?b++:r++;return{b,r}}function spawn(u,t,k,b=0){if(V.has(u)&&!V.get(u).dead)return V.get(u);let c=count();t=t||(c.b<=c.r?'blue':'red');k=k||1+Math.floor(Math.random()*3);let s=new Soldier(u,t,k,b);S.push(s);V.set(u,s);E.push({q:'s',x:s.x,y:s.y-42,l:.8,t});feed(t,`${u} DEPLOYED • ${K[k].n}`);return s}function alive(){let a=S.filter(s=>!s.dead&&!s.b);return a[Math.floor(Math.random()*a.length)]}
function front(){let b=-1,r=7;Q.forEach((s,i)=>{if(s.o==='blue')b=Math.max(b,i);if(s.o==='red')r=Math.min(r,i)});return Math.max(90,Math.min(1190,((b+r)/2+.5)*W.w/7))}
function sectors(d){let sw=W.w/7;for(let i=0;i<7;i++){let L=i*sw,H=L+sw,b=0,r=0;for(let s of S)if(!s.dead&&s.x>=L&&s.x<H)s.t==='blue'?b++:r++;if(!b&&!r){Q[i].m=Math.max(0,Q[i].m-d*.25);continue}if(b===r)continue;let t=b>r?'blue':'red',n=Math.abs(b-r),c=Q[i];if(c.p!==t){c.m=Math.max(0,c.m-d*.8);if(!c.m)c.p=t}else c.m+=d*(.16+Math.min(4,n)*.055);if(c.m>=1&&c.o!==t){c.o=t;c.m=0;c.p='';feed(t,`${t.toUpperCase()} CAPTURED SECTOR ${i+1}`);shake=5;if((t==='blue'&&i===6)||(t==='red'&&i===0))finish(t)}}}
function boom(g){E.push({q:'e',x:g.tx,y:g.ty-18,l:.75});shake=11;for(let s of S)if(!s.dead&&s.t!==g.t){let d=Math.hypot(s.x-g.tx,(s.y-g.ty)*.6);if(d<120)s.hit((1-d/120)*78+16,g.o)}}function updG(d){for(let i=G.length-1;i>=0;i--){let g=G[i];g.p+=d/g.d;if(g.p>=1){boom(g);G.splice(i,1);continue}g.x=g.sx+(g.tx-g.sx)*g.p;g.y=g.sy+(g.ty-g.sy)*g.p-Math.sin(Math.PI*g.p)*95}}
function bg(){let g=x.createLinearGradient(0,0,0,720);g.addColorStop(0,'#15252d');g.addColorStop(.54,'#29383b');g.addColorStop(.55,'#4a4437');g.addColorStop(1,'#1a1c18');x.fillStyle=g;x.fillRect(0,0,1280,720);x.fillStyle='#3d3b31';x.fillRect(0,W.g,1280,167);let sw=1280/7;x.font='bold 9px system-ui';x.textAlign='center';for(let i=0;i<7;i++){x.strokeStyle='#ffffff12';x.setLineDash([4,8]);x.beginPath();x.moveTo(i*sw,W.g-120);x.lineTo(i*sw,720);x.stroke();x.setLineDash([]);x.fillStyle='#ffffff18';x.fillText(`SECTOR ${i+1}`,i*sw+sw/2,W.g+26)}base(55,'blue');base(1225,'red');x.fillStyle='#171a17';for(let p of [230,430,640,850,1050]){x.fillRect(p-55,W.g+6,110,12);x.fillStyle='#595144';x.fillRect(p-52,W.g+1,104,6);x.fillStyle='#171a17'}}function base(p,t){x.fillStyle=T[t].d;x.fillRect(p-35,W.g-90,70,90);x.fillStyle='#0d1417';x.fillRect(p-18,W.g-47,36,47);x.fillStyle=T[t].c;x.fillRect(p+(t==='blue'?-28:20),W.g-122,8,38)}
function drawFX(){for(let r of R){x.globalAlpha=Math.min(1,r.l/.07);x.strokeStyle=T[r.t].c;x.beginPath();x.moveTo(r.a,r.b);x.lineTo(r.c,r.d);x.stroke()}x.globalAlpha=1;for(let g of G){x.fillStyle='#d7dfce';x.fillRect(g.x-3,g.y-3,6,6)}for(let e of E){if(e.q==='m'){x.globalAlpha=Math.min(1,e.l/.08);x.fillStyle='#ffe08a';x.beginPath();x.arc(e.x,e.y,7,0,7);x.fill()}if(e.q==='h'||e.q==='f'){x.globalAlpha=Math.min(1,e.l/.45);x.fillStyle=e.q==='h'?'#74f0a8':'#bde4ff';x.font='bold 12px system-ui';x.textAlign='center';x.fillText(e.q==='h'?'+HP':'FOLLOW +ARMOR',e.x,e.y)}if(e.q==='s'){x.globalAlpha=Math.min(1,e.l/.3);x.strokeStyle=T[e.t].c;x.beginPath();x.arc(e.x,e.y,18+(1-e.l)*20,0,7);x.stroke()}if(e.q==='e'&&I.e){let n=I.e.width/64,p=1-e.l/.75,f=Math.min(n-1,Math.floor(p*n));x.globalAlpha=1;x.drawImage(I.e,f*64,0,64,64,e.x-64,e.y-88,128,128)}}x.globalAlpha=1}
function render(){let z=C.height/720,v=C.width/z,t=front();cam+=(t-cam)*.055;cam=Math.max(v/2,Math.min(1280-v/2,cam));let a=(Math.random()-.5)*shake,b=(Math.random()-.5)*shake*.5;shake*=.86;x.save();x.setTransform(z,0,0,z,C.width/2-cam*z+a,b);bg();[...S].sort((a,b)=>a.y-b.y).forEach(s=>s.draw());drawFX();x.restore()}
function update(d){if(!go||win)return;S.forEach(s=>s.update(d));updG(d);for(let a of [E,R])for(let i=a.length-1;i>=0;i--)if((a[i].l-=d)<=0)a.splice(i,1);cap+=d;if(cap>.25){sectors(cap);cap=0}for(let i=S.length-1;i>=0;i--){let s=S[i];if(s.dead&&s.dt>5.5){S.splice(i,1);if(V.get(s.u)===s)V.delete(s.u)}}if(demo){let c=count();if(c.b<7)spawn('Blue'+Math.floor(Math.random()*999),'blue',0,1);if(c.r<7)spawn('Red'+Math.floor(Math.random()*999),'red',0,1)}}
function hud(){let c=count();U.bc.textContent=c.b;U.rc.textContent=c.r;U.bk.textContent=T.blue.k+' KILLS';U.rk.textContent=T.red.k+' KILLS';U.fp.textContent=Math.round(fps)+' FPS';U.ro.textContent=`ROUND ${round} • FRONT ${Math.round(front())}`;U.ss.innerHTML=Q.map((s,i)=>`<i class="sector ${s.o}" style="--capture:${Math.min(1,s.m)}" title="Sector ${i+1}"></i>`).join('')}
function loop(n){let d=Math.min(.05,(n-last)/1000);last=n;fps=fps*.92+(1/Math.max(.001,d))*.08;update(d);render();hud();requestAnimationFrame(loop)}
function reset(b=0){S.length=E.length=R.length=G.length=0;V.clear();T.blue.k=T.red.k=0;Q.forEach((s,i)=>Object.assign(s,{o:i<3?'blue':i>3?'red':'neutral',m:0,p:''}));round++;win=0;cam=640;if(b)start(1)}function start(b=1){go=1;win=0;U.st.classList.add('hidden');if(b&&!S.length)for(let i=0;i<6;i++){spawn('B-'+(i+1),'blue',1+i%3,1);spawn('R-'+(i+1),'red',1+(i+1)%3,1)}}function finish(t){if(win)return;win=1;U.wt.textContent=t.toUpperCase()+' FORCE WINS';U.wt.style.color=T[t].c;U.wc.classList.remove('hidden');setTimeout(()=>{U.wc.classList.add('hidden');reset(1)},4500)}
function handle(e){if(!e)return;let t=String(e.type||e.event||'').toLowerCase(),u=String(e.username||e.user||e.uniqueId||'Viewer').slice(0,18);if(t==='join'){go=1;return spawn(u)}let s=V.get(u)||alive();if(!s)return;if(t==='like')return s.heal(Math.min(30,Math.max(2,Number(e.count||1)*.6)));if(t==='follow')return s.boost();if(t==='gift'){let n=String(e.giftName||e.name||'').toLowerCase(),v=Number(e.diamonds||e.value||1);if(n.includes('rose')||v<=2){s.gc=0;feed(s.t,s.u+' • GRENADE READY')}else if(v<50){s.heal(35);s.arm+=10}else{for(let i=0;i<Math.min(5,1+Math.floor(v/100));i++)spawn(`${u}-${i+1}`,s.t,0,1);feed(s.t,u+' CALLED REINFORCEMENTS')}}}
window.FRONTLINE_LIVE={handle,join:u=>handle({type:'join',username:u}),like:(u,c=1)=>handle({type:'like',username:u,count:c}),follow:u=>handle({type:'follow',username:u}),gift:(u,n='Rose',d=1)=>handle({type:'gift',username:u,giftName:n,diamonds:d}),reset:()=>reset(),state:()=>({soldiers:S.length,sectors:Q.map(s=>s.o),kills:{blue:T.blue.k,red:T.red.k}})};
q('#start-test').onclick=()=>start(1);q('#test-toggle').onclick=()=>U.pa.classList.toggle('hidden');q('#close-test').onclick=()=>U.pa.classList.add('hidden');document.querySelectorAll('[data-test]').forEach(b=>b.onclick=()=>{let a=b.dataset.test;go=1;if(a==='join')return handle({type:'join',username:'Viewer'+(++idx)});if(a==='reset')return reset(1);if(a==='reinforce'){let c=count(),t=c.b<=c.r?'blue':'red';for(let i=0;i<3;i++)spawn('Reinf'+(++idx),t,0,1);return}let s=alive();if(!s)return;if(a==='like')handle({type:'like',username:s.u,count:25});if(a==='rose')handle({type:'gift',username:s.u,giftName:'Rose'});if(a==='follow')handle({type:'follow',username:s.u})});
load().catch(e=>U.ld.innerHTML='<b>ASSET LOAD ERROR</b><span>'+e.message+'</span>');requestAnimationFrame(loop);
