import{renderArenaHD as baseRender,preloadArenaHD as basePreload}from'./arena-hd-v114.js?v=1.14.0';
const VERSION='1.15.0',ID='volcanic_ring',COUNT=10;
let volcanic=null,pending=null;
function imageFrom(src){return new Promise((resolve,reject)=>{const im=new Image();im.decoding='async';im.onload=()=>resolve(im);im.onerror=()=>reject(new Error('image decode failed'));im.src=src})}
async function loadVolcanic(){if(volcanic)return volcanic;if(pending)return pending;pending=(async()=>{const parts=await Promise.all(Array.from({length:COUNT},async(_,i)=>{const n=String(i).padStart(2,'0'),r=await fetch(`./assets/arenas/q82/${ID}.${n}.b64?v=${VERSION}`,{cache:'force-cache'});if(!r.ok)throw new Error(`Volcanic chunk ${n} HTTP ${r.status}`);return r.text()}));const bin=atob(parts.join('')),bytes=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)bytes[i]=bin.charCodeAt(i);const u=URL.createObjectURL(new Blob([bytes],{type:'image/avif'}));try{volcanic=await imageFrom(u);return volcanic}finally{URL.revokeObjectURL(u);pending=null}})();return pending}
const TAU=Math.PI*2,groundCache=new WeakMap();
function dot(c,x,y,r,color,alpha=1){c.globalAlpha=alpha;c.fillStyle=color;c.beginPath();c.arc(x,y,r,0,TAU);c.fill();c.globalAlpha=1}
function skyLava(c,w,h,t){const bg=c.createLinearGradient(0,0,0,h);bg.addColorStop(0,'#120508');bg.addColorStop(.67,'#4b0d0a');bg.addColorStop(1,'#08070d');c.fillStyle=bg;c.fillRect(0,0,w,h);const p=.16+.09*Math.sin(t*.002),g=c.createRadialGradient(w*.5,h*.72,0,w*.5,h*.72,w*.55);g.addColorStop(0,`rgba(255,78,12,${p})`);g.addColorStop(1,'rgba(40,0,0,0)');c.fillStyle=g;c.fillRect(0,0,w,h);for(let i=0;i<10;i++){const x=(i*137+t*.004*(1+i%2))%(w+180)-90,y=h*(.12+(i%4)*.11);c.fillStyle='rgba(28,20,22,.11)';c.beginPath();c.ellipse(x,y,w*.09,h*.055,0,0,TAU);c.fill()}for(let i=0;i<28;i++){const x=(i*73+t*.014)%(w+20)-10,y=h*.78-((i*41+t*(.02+(i%3)*.006))%(h*.55));dot(c,x,y,1+(i%3)*.65,'#ff8c2b',.32+(i%4)*.1)}}
function detectGround(im){if(groundCache.has(im))return groundCache.get(im);let ratio=.72;try{const iw=im.naturalWidth||im.width,ih=im.naturalHeight||im.height,aw=256,ah=Math.max(96,Math.round(aw*ih/iw)),cv=document.createElement('canvas');cv.width=aw;cv.height=ah;const q=cv.getContext('2d',{willReadFrequently:true});q.drawImage(im,0,0,aw,ah);const px=q.getImageData(0,0,aw,ah).data,ys=[];for(let x=Math.round(aw*.18);x<=Math.round(aw*.82);x+=2){let y=ah-1;while(y>=Math.round(ah*.42)&&px[(y*aw+x)*4+3]<28)y--;if(y<ah*.42)continue;let top=y,gap=0,solid=0;for(;y>=Math.round(ah*.38);y--){if(px[(y*aw+x)*4+3]>=28){top=y;gap=0;solid++}else if(++gap>4&&solid>=5)break}if(solid>=5)ys.push(top/ah)}if(ys.length){ys.sort((a,b)=>a-b);ratio=ys[Math.min(ys.length-1,Math.floor(ys.length*.72))]}}catch(e){console.warn('[Fighter Arena] Volcanic floor scan fallback',e)}ratio=Math.max(.56,Math.min(.84,ratio));groundCache.set(im,ratio);return ratio}
function targetGround(w,h){return h*(w<600?.70:.75)}
function drawArena(c,im,w,h){const iw=im.naturalWidth||im.width,ih=im.naturalHeight||im.height;if(!iw||!ih)return;const landscape=w>=h*1.45,s=landscape?Math.min(w/iw,(h/ih)*1.10):Math.max(w/iw,h/ih),dw=iw*s,dh=ih*s,dx=(w-dw)*.5,dy=targetGround(w,h)-detectGround(im)*dh;c.imageSmoothingEnabled=true;c.imageSmoothingQuality='high';c.drawImage(im,0,0,iw,ih,dx,dy,dw,dh)}
function vignette(c,w,h){const v=c.createRadialGradient(w*.5,h*.48,Math.min(w,h)*.2,w*.5,h*.5,Math.max(w,h)*.76);v.addColorStop(.58,'rgba(0,0,0,0)');v.addColorStop(1,'rgba(0,0,0,.28)');c.fillStyle=v;c.fillRect(0,0,w,h)}
function paint(c,w,h,dpr,im){c.save();c.setTransform(dpr,0,0,dpr,0,0);c.clearRect(0,0,w,h);skyLava(c,w,h,performance.now());if(im)drawArena(c,im,w,h);vignette(c,w,h);c.restore()}
export function renderArenaHD(c,id,w,h,dpr=1){if(id!==ID)return baseRender(c,id,w,h,dpr);paint(c,w,h,dpr,volcanic);if(!volcanic)loadVolcanic().then(im=>paint(c,w,h,dpr,im)).catch(e=>{console.warn('[Fighter Arena] Volcanic q82 fallback: '+e.message);baseRender(c,id,w,h,dpr)})}
export function preloadArenaHD(){return Promise.allSettled([basePreload(),loadVolcanic()])}
const idle=window.requestIdleCallback||((fn)=>setTimeout(fn,0));idle(()=>loadVolcanic().catch(()=>{}));