import{renderArenaHD as baseRender,preloadArenaHD as basePreload}from'./arena-hd.js?v=1.12.0';
const VERSION='1.13.0',ID='neon_city',COUNT=32;
let neon=null,pending=null;
function imageFrom(src){return new Promise((resolve,reject)=>{const im=new Image();im.decoding='async';im.onload=()=>resolve(im);im.onerror=()=>reject(new Error('image decode failed'));im.src=src})}
async function loadNeon(){if(neon)return neon;if(pending)return pending;pending=(async()=>{const parts=await Promise.all(Array.from({length:COUNT},async(_,i)=>{const n=String(i).padStart(2,'0'),r=await fetch(`./assets/arenas/q82/${ID}.${n}.b64?v=${VERSION}`,{cache:'force-cache'});if(!r.ok)throw new Error(`Neon chunk ${n} HTTP ${r.status}`);return r.text()}));const bin=atob(parts.join('')),bytes=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)bytes[i]=bin.charCodeAt(i);const u=URL.createObjectURL(new Blob([bytes],{type:'image/avif'}));try{neon=await imageFrom(u);return neon}finally{URL.revokeObjectURL(u);pending=null}})();return pending}
const TAU=Math.PI*2,groundCache=new WeakMap();
function grad(c,w,h,a,b,m=.58){const g=c.createLinearGradient(0,0,0,h);g.addColorStop(0,a);g.addColorStop(m,b);g.addColorStop(1,'#08070d');c.fillStyle=g;c.fillRect(0,0,w,h)}
function skyNeon(c,w,h,t){grad(c,w,h,'#03051d','#150d35',.72);const base=h*.57;c.fillStyle='rgba(15,23,62,.7)';for(let i=0;i<20;i++){const bw=w*(.025+(i%4)*.009),bh=h*(.08+(i%6)*.025),x=((i*w*.071-t*.004)%(w+bw))-bw;c.fillRect(x,base-bh,bw,bh);c.fillStyle=i%2?'rgba(0,220,255,.12)':'rgba(255,45,220,.11)';c.fillRect(x+bw*.18,base-bh,bw*.08,bh);c.fillStyle='rgba(15,23,62,.7)'}c.fillStyle='rgba(58,210,255,.035)';for(let y=0;y<h*.72;y+=4)c.fillRect(0,y,w,1);for(let i=0;i<7;i++){const x=w*(.08+i*.15),y=h*(.15+(i%3)*.1),r=w*.08,g=c.createRadialGradient(x,y,0,x,y,r);g.addColorStop(0,i%2?'rgba(255,42,220,.08)':'rgba(0,220,255,.09)');g.addColorStop(1,'rgba(0,0,0,0)');c.fillStyle=g;c.fillRect(x-r,y-r,r*2,r*2)}}
function detectGround(im){if(groundCache.has(im))return groundCache.get(im);let ratio=.72;try{const iw=im.naturalWidth||im.width,ih=im.naturalHeight||im.height,aw=256,ah=Math.max(96,Math.round(aw*ih/iw)),cv=document.createElement('canvas');cv.width=aw;cv.height=ah;const q=cv.getContext('2d',{willReadFrequently:true});q.drawImage(im,0,0,aw,ah);const px=q.getImageData(0,0,aw,ah).data,ys=[];for(let x=Math.round(aw*.18);x<=Math.round(aw*.82);x+=2){let y=ah-1;while(y>=Math.round(ah*.42)&&px[(y*aw+x)*4+3]<28)y--;if(y<ah*.42)continue;let top=y,gap=0,solid=0;for(;y>=Math.round(ah*.38);y--){if(px[(y*aw+x)*4+3]>=28){top=y;gap=0;solid++}else if(++gap>4&&solid>=5)break}if(solid>=5)ys.push(top/ah)}if(ys.length){ys.sort((a,b)=>a-b);ratio=ys[Math.min(ys.length-1,Math.floor(ys.length*.72))]}}catch(e){console.warn('[Fighter Arena] Neon floor scan fallback',e)}ratio=Math.max(.56,Math.min(.84,ratio));groundCache.set(im,ratio);return ratio}
function targetGround(w,h){return h*(w<600?.70:.75)}
function drawArena(c,im,w,h){const iw=im.naturalWidth||im.width,ih=im.naturalHeight||im.height;if(!iw||!ih)return;const landscape=w>=h*1.45,s=landscape?Math.min(w/iw,(h/ih)*1.10):Math.max(w/iw,h/ih),dw=iw*s,dh=ih*s,dx=(w-dw)*.5,dy=targetGround(w,h)-detectGround(im)*dh;c.imageSmoothingEnabled=true;c.imageSmoothingQuality='high';c.drawImage(im,0,0,iw,ih,dx,dy,dw,dh)}
function vignette(c,w,h){const v=c.createRadialGradient(w*.5,h*.48,Math.min(w,h)*.2,w*.5,h*.5,Math.max(w,h)*.76);v.addColorStop(.58,'rgba(0,0,0,0)');v.addColorStop(1,'rgba(0,0,0,.27)');c.fillStyle=v;c.fillRect(0,0,w,h)}
function paint(c,w,h,dpr,im){c.save();c.setTransform(dpr,0,0,dpr,0,0);c.clearRect(0,0,w,h);skyNeon(c,w,h,performance.now());if(im)drawArena(c,im,w,h);vignette(c,w,h);c.restore()}
export function renderArenaHD(c,id,w,h,dpr=1){if(id!==ID)return baseRender(c,id,w,h,dpr);paint(c,w,h,dpr,neon);if(!neon)loadNeon().then(im=>paint(c,w,h,dpr,im)).catch(e=>{console.warn('[Fighter Arena] Neon q82 fallback: '+e.message);baseRender(c,id,w,h,dpr)})}
export function preloadArenaHD(){return Promise.allSettled([basePreload(),loadNeon()])}
const idle=window.requestIdleCallback||((fn)=>setTimeout(fn,0));idle(()=>loadNeon().catch(()=>{}));
