import{renderArenaHD as baseRender,preloadArenaHD as basePreload}from'./arena-hd-v113.js?v=1.13.0';
const VERSION='1.14.0',ID='jungle_temple';
const PARTS=['00','01','02','03','04','05','06','07','08a','08b','09a','09b'];
let jungle=null,pending=null;
function imageFrom(src){return new Promise((resolve,reject)=>{const im=new Image();im.decoding='async';im.onload=()=>resolve(im);im.onerror=()=>reject(new Error('image decode failed'));im.src=src})}
async function loadJungle(){if(jungle)return jungle;if(pending)return pending;pending=(async()=>{const parts=await Promise.all(PARTS.map(async n=>{const r=await fetch(`./assets/arenas/q82/${ID}.${n}.b64?v=${VERSION}`,{cache:'force-cache'});if(!r.ok)throw new Error(`Jungle chunk ${n} HTTP ${r.status}`);return r.text()}));const bin=atob(parts.join('')),bytes=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)bytes[i]=bin.charCodeAt(i);const u=URL.createObjectURL(new Blob([bytes],{type:'image/avif'}));try{jungle=await imageFrom(u);return jungle}finally{URL.revokeObjectURL(u);pending=null}})();return pending}
const groundCache=new WeakMap();
function skyJungle(c,w,h,t){const g=c.createLinearGradient(0,0,0,h);g.addColorStop(0,'#081d28');g.addColorStop(.48,'#315746');g.addColorStop(1,'#0d1711');c.fillStyle=g;c.fillRect(0,0,w,h);const moon=c.createRadialGradient(w*.76,h*.18,0,w*.76,h*.18,w*.14);moon.addColorStop(0,'rgba(212,255,206,.24)');moon.addColorStop(.45,'rgba(164,226,180,.08)');moon.addColorStop(1,'rgba(0,0,0,0)');c.fillStyle=moon;c.fillRect(0,0,w,h);for(let i=0;i<14;i++){const x=((i*w*.093+t*.004*(i%2?1:-1))%(w+w*.12))-w*.06,y=h*(.12+(i%5)*.075),rw=w*(.08+(i%3)*.025),rh=h*.035;c.fillStyle='rgba(210,235,218,.025)';c.beginPath();c.ellipse(x,y,rw,rh,0,0,Math.PI*2);c.fill()}for(let i=0;i<24;i++){const phase=(t*.00018+i*.63)%(Math.PI*2),x=w*(.04+(i%12)*.083),y=h*(.18+(i%6)*.085)+Math.sin(phase)*h*.012;c.fillStyle=`rgba(185,255,121,${.035+(i%4)*.018})`;c.beginPath();c.arc(x,y,1+(i%3)*.45,0,Math.PI*2);c.fill()}}
function detectGround(im){if(groundCache.has(im))return groundCache.get(im);let ratio=.72;try{const iw=im.naturalWidth||im.width,ih=im.naturalHeight||im.height,aw=256,ah=Math.max(96,Math.round(aw*ih/iw)),cv=document.createElement('canvas');cv.width=aw;cv.height=ah;const q=cv.getContext('2d',{willReadFrequently:true});q.drawImage(im,0,0,aw,ah);const px=q.getImageData(0,0,aw,ah).data,ys=[];for(let x=Math.round(aw*.18);x<=Math.round(aw*.82);x+=2){let y=ah-1;while(y>=Math.round(ah*.42)&&px[(y*aw+x)*4+3]<28)y--;if(y<ah*.42)continue;let top=y,gap=0,solid=0;for(;y>=Math.round(ah*.38);y--){if(px[(y*aw+x)*4+3]>=28){top=y;gap=0;solid++}else if(++gap>4&&solid>=5)break}if(solid>=5)ys.push(top/ah)}if(ys.length){ys.sort((a,b)=>a-b);ratio=ys[Math.min(ys.length-1,Math.floor(ys.length*.72))]}}catch(e){console.warn('[Fighter Arena] Jungle floor scan fallback',e)}ratio=Math.max(.56,Math.min(.84,ratio));groundCache.set(im,ratio);return ratio}
function targetGround(w,h){return h*(w<600?.70:.75)}
function drawArena(c,im,w,h){const iw=im.naturalWidth||im.width,ih=im.naturalHeight||im.height;if(!iw||!ih)return;const landscape=w>=h*1.45,s=landscape?Math.min(w/iw,(h/ih)*1.10):Math.max(w/iw,h/ih),dw=iw*s,dh=ih*s,dx=(w-dw)*.5,dy=targetGround(w,h)-detectGround(im)*dh;c.imageSmoothingEnabled=true;c.imageSmoothingQuality='high';c.drawImage(im,0,0,iw,ih,dx,dy,dw,dh)}
function vignette(c,w,h){const v=c.createRadialGradient(w*.5,h*.48,Math.min(w,h)*.2,w*.5,h*.5,Math.max(w,h)*.76);v.addColorStop(.58,'rgba(0,0,0,0)');v.addColorStop(1,'rgba(0,0,0,.28)');c.fillStyle=v;c.fillRect(0,0,w,h)}
function paint(c,w,h,dpr,im){c.save();c.setTransform(dpr,0,0,dpr,0,0);c.clearRect(0,0,w,h);skyJungle(c,w,h,performance.now());if(im)drawArena(c,im,w,h);vignette(c,w,h);c.restore()}
export function renderArenaHD(c,id,w,h,dpr=1){if(id!==ID)return baseRender(c,id,w,h,dpr);paint(c,w,h,dpr,jungle);if(!jungle)loadJungle().then(im=>paint(c,w,h,dpr,im)).catch(e=>{console.warn('[Fighter Arena] Jungle q82 fallback: '+e.message);baseRender(c,id,w,h,dpr)})}
export function preloadArenaHD(){return Promise.allSettled([basePreload(),loadJungle()])}
const idle=window.requestIdleCallback||((fn)=>setTimeout(fn,0));idle(()=>loadJungle().catch(()=>{}));
