import{S,cfg,clamp,finish,rotate,tierColor}from'./core.js?v=1.3.0';
import{renderArenaHD}from'./arena-hd.js?v=1.3.0';

export function startCombat(canvas){
  const ctx=canvas.getContext('2d',{alpha:false,desynchronized:true});
  let last=performance.now(),dpr=1,arenaId='sky_dojo',arenaCanvas=null,shake=0,flash=0,toastTimer=0,audio=null;
  let particles=[],floats=[],sheetFx=[],projectiles=[];
  const metrics=new Map();
  const bias={samurai:.80,medieval_king:.94};
  const groundY=()=>S.h*(S.w<600?.70:.75);
  const combatGap=()=>Math.max(S.w<700?132:148,S.w*(S.w<700?.34:.10));
  const FX={impact:{key:'fx:impact',frameW:64,frameH:32,frames:6,fps:22},burst:{key:'fx:burst',frameW:64,frameH:32,frames:5,fps:20},slash:{key:'fx:slash',frameW:32,frameH:32,frames:5,fps:22},spark:{key:'fx:spark',frameW:32,frameH:32,frames:5,fps:22},impactGb:{key:'fx:impactGb',frameW:64,frameH:32,frames:6,fps:22},burstGb:{key:'fx:burstGb',frameW:64,frameH:32,frames:5,fps:20},slashGb:{key:'fx:slashGb',frameW:32,frameH:32,frames:5,fps:22},sparkGb:{key:'fx:sparkGb',frameW:32,frameH:32,frames:5,fps:22}};
  const tone=(freq=220,duration=.05,gain=.025,type='square')=>{if(!S.started)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(gain,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+duration)}catch{}};
  const burst=(x,y,c,n=10,p=1)=>{for(let i=0;i<n;i++){const a=Math.random()*Math.PI*2,s=(30+Math.random()*90)*p;particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s-20,l:.35+Math.random()*.45,m:.8,c,z:2+Math.random()*4})}};
  const floatText=(x,y,t,c)=>floats.push({x,y,t,c,l:.8,m:.8});
  const toast=(text,color='#ffd56b')=>{const el=document.querySelector('#eventToast');if(!el)return;el.textContent=text;el.style.color=color;el.classList.add('show');toastTimer=1.8};
  function sheet(kind,x,y,scale=2,flipX=false){const def=FX[kind]||FX.impact,img=S.images.get(def.key);if(!img){burst(x,y,'#ffd56b',8,.7);return}sheetFx.push({kind,x,y,scale,flipX,age:0,duration:def.frames/def.fps})}
  function rebuildArena(){if(!S.w||!S.h)return;arenaCanvas=document.createElement('canvas');arenaCanvas.width=Math.max(1,Math.round(S.w*dpr));arenaCanvas.height=Math.max(1,Math.round(S.h*dpr));renderArenaHD(arenaCanvas.getContext('2d'),arenaId,S.w,S.h,dpr)}
  function setArenaVisual(arena){arenaId=arena?.id||'sky_dojo';const el=document.querySelector('#arenaLabel');if(el)el.textContent=(arena?.name||'Sky Dojo').toUpperCase();rebuildArena()}
  S.fx={tone,burst,float:floatText,toast,arena:setArenaVisual,sheet,flash:v=>flash=Math.max(flash,v)};
  function resize(){S.w=innerWidth;S.h=innerHeight;dpr=Math.min(devicePixelRatio||1,S.w<700?2.25:2.5);canvas.width=Math.round(S.w*dpr);canvas.height=Math.round(S.h*dpr);canvas.style.width=`${S.w}px`;canvas.style.height=`${S.h}px`;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';metrics.clear();rebuildArena()}
  addEventListener('resize',resize,{passive:true});resize();
  function meta(r,state=r.state){const f=cfg(r.fighterId),a=f.animations[state];if(a)return{name:state,a};if(state==='special'){for(const n of ['attack3','attack2','attack1'])if(f.animations[n])return{name:n,a:f.animations[n]}}if(state==='death'&&!f.animations.death)return f.animations.hurt?{name:'hurt',a:f.animations.hurt}:{name:'idle',a:f.animations.idle};if(state==='fall'&&!f.animations.fall)return{name:'idle',a:f.animations.idle};return{name:'idle',a:f.animations.idle}}
  function setAnim(r,state,restart=false){if(r.state===state&&!restart)return;r.state=state;r.anim=0;r.time=0;r.hit=false}
  const duration=r=>{const a=meta(r).a;return Math.max(.24,a.frames/a.fps)};
  const attacks=f=>Object.keys(f.animations).filter(n=>/^attack\d+$/.test(n)).sort((a,b)=>+a.slice(6)-+b.slice(6));
  function pickAttack(r,f){const list=attacks(f);if(!list.length)return'attack1';const opts=list.length>1?list.filter(n=>n!==r.lastAttack):list,n=opts[Math.floor(Math.random()*opts.length)]||list[0];r.lastAttack=n;return n}
  const doubleChance=r=>clamp(.18+(cfg(r.fighterId).tier||0)*.012+Math.min(.045,(r.viewer.level-1)*.004),.18,.27);
  function getMetrics(f,img){const k=f.atlas;if(metrics.has(k))return metrics.get(k);const a=f.animations.idle;let out={cx:.5,foot:.88,top:.18,bodyH:.65};try{const cv=document.createElement('canvas');cv.width=a.frameW;cv.height=a.frameH;const q=cv.getContext('2d',{willReadFrequently:true});let sx=0,sfoot=0,stop=0,sh=0,count=0;for(let sample=0;sample<Math.min(4,a.frames);sample++){const fr=Math.floor(sample*(a.frames-1)/Math.max(1,Math.min(4,a.frames)-1));q.clearRect(0,0,a.frameW,a.frameH);q.drawImage(img,(a.x||0)+fr*a.frameW,a.y||0,a.frameW,a.frameH,0,0,a.frameW,a.frameH);const px=q.getImageData(0,0,a.frameW,a.frameH).data,rows=new Uint16Array(a.frameH),cols=new Uint16Array(a.frameW);let minX=a.frameW,minY=a.frameH,maxX=-1,maxY=-1;for(let y=0;y<a.frameH;y+=2)for(let x=0;x<a.frameW;x+=2){const i=(y*a.frameW+x)*4;if(px[i+3]>20&&px[i]+px[i+1]+px[i+2]>10){rows[y]++;cols[x]++;minX=Math.min(minX,x);maxX=Math.max(maxX,x);minY=Math.min(minY,y);maxY=Math.max(maxY,y)}}if(maxY<0)continue;const rt=Math.max(2,Math.round(a.frameW*.012)),ct=Math.max(2,Math.round(a.frameH*.012));let top=minY,foot=maxY,left=minX,right=maxX;for(let y=minY;y<=maxY;y+=2)if(rows[y]>=rt){top=y;break}for(let y=maxY;y>=minY;y-=2)if(rows[y]>=rt){foot=y;break}for(let x=minX;x<=maxX;x+=2)if(cols[x]>=ct){left=x;break}for(let x=maxX;x>=minX;x-=2)if(cols[x]>=ct){right=x;break}sx+=(left+right+1)/2/a.frameW;sfoot+=(foot+1)/a.frameH;stop+=top/a.frameH;sh+=Math.max(.15,(foot-top+1)/a.frameH);count++}if(count)out={cx:sx/count,foot:sfoot/count,top:stop/count,bodyH:sh/count}}catch{}metrics.set(k,out);return out}
  function fighterIdFor(f){return Object.keys(S.manifest.fighters).find(id=>S.manifest.fighters[id]===f)}
  function visualScale(f,img){const m=getMetrics(f,img),target=S.w<600?Math.min(148,S.h*.205):Math.min(182,S.h*.255),px=Math.max(8,m.bodyH*f.animations.idle.frameH);return clamp(target/px,.58,4.8)*(bias[fighterIdFor(f)]||1)}
  function addProjectile(a,d,kind='magic'){projectiles.push({kind,from:a.x,to:d.x,x:a.x,y:groundY()-82,age:0,dur:.2+Math.min(.3,Math.abs(d.x-a.x)/850),side:a.side,fighterId:a.fighterId})}
  function hit(a,d,strong=false,mult=1){if(!d||d.dead||d.inv>0)return;const dist=Math.abs(a.x-d.x),reach=Math.max(combatGap()+20,a.range*Math.min(1.55,S.w/860))+(strong?30:0);if(dist>reach)return;let dmg=Math.max(2,a.attack*(strong?1.45:1)*mult*(.9+Math.random()*.2)-d.defense*.32);if(d.shield>0){const b=Math.min(d.shield,dmg);d.shield-=b;dmg-=b;floatText(d.x,groundY()-132,`SHIELD ${Math.round(b)}`,'#75cfff');sheet('sparkGb',d.x,groundY()-78,1.9)}d.hp-=dmg;a.energy=clamp(a.energy+18,0,100);d.energy=clamp(d.energy+11,0,100);d.flash=.15;d.inv=.12;d.knock=Math.sign(d.x-a.x)*(strong?115:68);setAnim(d,'hurt');const ranged=/wizard|mage|huntress/i.test(cfg(a.fighterId).name);if(ranged)addProjectile(a,d,/huntress/i.test(cfg(a.fighterId).name)?'spear':'magic');sheet(strong?'burst':a.comboStrike?'slashGb':'slash',d.x,groundY()-75,strong?2.65:a.comboStrike?2.2:1.9,a.side===1);sheet('impact',d.x,groundY()-78,strong?2.4:1.75);burst(d.x,groundY()-70,strong?'#ffd56b':'#ff6579',strong?18:10,strong?1.2:.7);floatText(d.x,groundY()-126,`${a.comboStrike?'×2 ':''}-${Math.round(dmg)}`,strong?'#ffd56b':'#ff889a');tone(strong?120:175,.045,.018,'square');shake=Math.max(shake,strong?7:3.5);if(d.hp<=0){d.hp=0;d.dead=true;d.airY=0;setAnim(d,'death');a.energy=100;finish(d,a)}}
  function beginAttack(r,f){r.comboStrike=false;r.doubleQueued=Math.random()<doubleChance(r);setAnim(r,pickAttack(r,f),true)}
  function chain(r,e,f){r.doubleQueued=false;r.comboStrike=true;toast(`${r.viewer.name} · DOUBLE ATTACK!`,'#8ceaff');floatText(r.x,groundY()-155,'DOUBLE!','#8ceaff');sheet(f.tier>=3?'burstGb':'burst',r.x,groundY()-86,2.35);tone(690,.08,.024,'triangle');setAnim(r,pickAttack(r,f),true)}
  function updateFighter(r,e,dt){r.time+=dt;r.anim+=dt;r.cool=Math.max(0,r.cool-dt);r.special=Math.max(0,r.special-dt);r.inv=Math.max(0,r.inv-dt);r.flash=Math.max(0,r.flash-dt);r.glow=Math.max(0,r.glow-dt);r.knock*=Math.pow(.04,dt);r.x=clamp(r.x+r.knock*dt,S.w*.07,S.w*.93);if(r.dead)return;const f=cfg(r.fighterId),dur=duration(r);if(r.state==='hurt'){if(r.time>=dur)setAnim(r,'idle');return}if(r.state==='jump'||r.state==='fall'){const p=clamp(r.time/dur,0,1);r.airY=r.state==='jump'?-Math.sin(p*Math.PI)*Math.min(42,S.h*.05):-Math.cos(p*Math.PI*.5)*Math.min(30,S.h*.04);if(r.time>=dur){if(r.state==='jump'&&f.animations.fall)setAnim(r,'fall');else{r.airY=0;setAnim(r,'idle')}}return}if(r.state==='dash'){const dir=r.side===0?1:-1;r.x=clamp(r.x+dir*145*r.speed*dt,S.w*.07,S.w*.93);if(!r.hit&&r.time>=dur*.48){r.hit=true;hit(r,e,true)}if(r.time>=dur){r.cool=.55;setAnim(r,'idle')}return}if(/^attack\d+$/.test(r.state)||r.state==='special'){if(!r.hit&&r.time>=dur*.54){r.hit=true;hit(r,e,r.state==='special'||r.state==='attack3',r.comboStrike?.84:1)}if(r.time>=dur){if(r.doubleQueued&&!r.comboStrike&&!e.dead){chain(r,e,f);return}r.comboStrike=false;r.doubleQueued=false;r.cool=.46/Math.max(.85,r.speed);setAnim(r,'idle')}return}const dist=Math.abs(e.x-r.x),wanted=Math.max(combatGap(),r.range*Math.min(1.28,S.w/920));if(dist>wanted+6){setAnim(r,'run');const dir=r.side===0?1:-1,desired=e.x-dir*wanted,max=86*r.speed*dt;r.x+=clamp(desired-r.x,-max,max);return}if(r.cool<=0){if(r.energy>=100||(r.special<=0&&Math.random()<.2)){r.energy=Math.max(0,r.energy-70);r.special=4.5;r.doubleQueued=false;r.comboStrike=false;setAnim(r,'special',true);sheet(f.tier>=3?'sparkGb':'spark',r.x,groundY()-88,2.2)}else if(f.animations.jump&&f.animations.fall&&Math.random()<.05){r.cool=.25;setAnim(r,'jump')}else beginAttack(r,f);return}setAnim(r,'idle')}
  function separate(a,b){if(!a||!b)return;const gap=combatGap();if(a.x>b.x-gap){const m=(a.x+b.x)/2;a.x=clamp(m-gap/2,S.w*.07,S.w*.84);b.x=clamp(m+gap/2,S.w*.16,S.w*.93);a.knock=Math.min(0,a.knock);b.knock=Math.max(0,b.knock)}}
  function updateProjectiles(dt){for(const p of projectiles){p.age+=dt;const q=clamp(p.age/p.dur,0,1);p.x=p.from+(p.to-p.from)*q;p.y=groundY()-82-Math.sin(q*Math.PI)*18}projectiles=projectiles.filter(p=>p.age<p.dur)}
  function update(dt){if(S.round==='countdown'){S.clock-=dt;if(S.clock<=0){S.round='fighting';S.clock=90;toast('FIGHT!','#ff5aa5');tone(250,.08,.025,'square')}return}if(S.round==='finished'){S.delay-=dt;if(S.delay<=0)rotate();return}if(S.round!=='fighting')return;const[a,b]=S.active;if(!a||!b)return;S.clock=Math.max(0,S.clock-dt);updateFighter(a,b,dt);updateFighter(b,a,dt);separate(a,b);updateProjectiles(dt);if(S.clock<=0&&!a.dead&&!b.dead){const loser=a.hp<=b.hp?a:b,winner=loser===a?b:a;loser.hp=0;loser.dead=true;setAnim(loser,'death');finish(loser,winner)}}
  function animateArena(t){ctx.save();if(arenaId==='neon_city'){ctx.strokeStyle='rgba(92,231,255,.14)';for(let i=0;i<16;i++){const x=(i*83+t*75)%S.w,y=(i*127+t*160)%S.h;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x-8,y+26);ctx.stroke()}}else if(arenaId==='volcanic_ring'||arenaId==='mecha_forge'){for(let i=0;i<16;i++){const x=(i*137+t*24)%S.w,y=groundY()+10-((i*61+t*48)%(S.h*.38));ctx.globalAlpha=.16+(i%4)*.07;ctx.fillStyle=arenaId==='volcanic_ring'?'#ff6a2a':'#ffc15b';ctx.fillRect(x,y,2+(i%3),2+(i%3))}}else if(arenaId==='ice_crystal'){ctx.globalAlpha=.08;ctx.fillStyle='#baf8ff';for(let i=0;i<20;i++)ctx.fillRect((i*97+t*11)%S.w,(i*71+t*21)%S.h,1.5,5)}ctx.restore()}
  function drawBackground(t){ctx.save();ctx.setTransform(dpr,0,0,dpr,0,0);ctx.fillStyle='#080511';ctx.fillRect(0,0,S.w,S.h);if(shake>0){ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);shake*=.86}if(arenaCanvas)ctx.drawImage(arenaCanvas,0,0,arenaCanvas.width,arenaCanvas.height,0,0,S.w,S.h);animateArena(t);ctx.restore()}
  function drawLabels(r,h){const y=groundY()+(r.airY||0);ctx.globalAlpha=.3;ctx.fillStyle='#000';ctx.beginPath();ctx.ellipse(r.x,groundY()+7,Math.max(22,h*.18),7,0,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;if(r.shield>0){ctx.strokeStyle='rgba(86,215,255,.72)';ctx.lineWidth=1.5;ctx.beginPath();ctx.ellipse(r.x,y-h*.48,h*.28,h*.4,0,0,Math.PI*2);ctx.stroke()}ctx.textAlign='center';ctx.font='700 11px system-ui';ctx.fillStyle='#fff';ctx.fillText(r.viewer.name,r.x,y-h*.77-9)}
  function drawFighter(r){if(!r)return;const f=cfg(r.fighterId),img=S.images.get(f.atlas)||S.images.get(`./${f.atlas.replace(/^\.\//,'')}`);if(!img)return;const m=getMetrics(f,img),mm=meta(r),a=mm.a,scale=visualScale(f,img),target=S.w<600?Math.min(148,S.h*.205):Math.min(182,S.h*.255);let fr=Math.floor(r.anim*a.fps);fr=a.loop?fr%a.frames:Math.min(a.frames-1,fr);const W=a.frameW*scale,H=a.frameH*scale,dx=r.x-m.cx*a.frameW*scale,dy=groundY()+(r.airY||0)-m.foot*a.frameH*scale;ctx.save();ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';if(r.glow>0){ctx.shadowColor=tierColor(f.tier);ctx.shadowBlur=16+r.glow*10}if(r.flash>0)ctx.globalAlpha=.65+Math.random()*.3;if(r.side===1){ctx.translate(r.x,0);ctx.scale(-1,1);ctx.translate(-r.x,0)}ctx.drawImage(img,(a.x||0)+fr*a.frameW,a.y||0,a.frameW,a.frameH,dx,dy,W,H);ctx.restore();drawLabels(r,target)}
  function drawProjectiles(){for(const p of projectiles){ctx.save();ctx.shadowColor=p.kind==='spear'?'#ffe29b':'#d8b8ff';ctx.shadowBlur=14;ctx.fillStyle=p.kind==='spear'?'#fff0bb':'#f5eaff';ctx.beginPath();ctx.arc(p.x,p.y,p.kind==='spear'?3:5,0,Math.PI*2);ctx.fill();ctx.restore()}}
  function drawSheetFx(dt){for(const f of sheetFx)f.age+=dt;sheetFx=sheetFx.filter(f=>f.age<f.duration);for(const f of sheetFx){const def=FX[f.kind]||FX.impact,img=S.images.get(def.key);if(!img)continue;const fr=Math.min(def.frames-1,Math.floor(f.age*def.fps)),w=def.frameW*f.scale,h=def.frameH*f.scale;ctx.save();if(f.flipX){ctx.translate(f.x,0);ctx.scale(-1,1);ctx.translate(-f.x,0)}ctx.imageSmoothingEnabled=false;ctx.drawImage(img,0,fr*def.frameH,def.frameW,def.frameH,f.x-w/2,f.y-h/2,w,h);ctx.restore()}}
  function drawFx(dt){for(const p of particles){p.l-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=90*dt}particles=particles.filter(p=>p.l>0);for(const f of floats){f.l-=dt;f.y-=24*dt}floats=floats.filter(f=>f.l>0);drawProjectiles();drawSheetFx(dt);for(const p of particles){ctx.globalAlpha=clamp(p.l/p.m,0,1);ctx.fillStyle=p.c;ctx.fillRect(p.x,p.y,p.z,p.z)}for(const f of floats){ctx.globalAlpha=clamp(f.l/f.m,0,1);ctx.fillStyle=f.c;ctx.font='800 12px system-ui';ctx.textAlign='center';ctx.fillText(f.t,f.x,f.y)}ctx.globalAlpha=1;if(flash>0){flash=Math.max(0,flash-dt);ctx.fillStyle=`rgba(255,255,255,${Math.min(.22,flash)})`;ctx.fillRect(0,0,S.w,S.h)}if(toastTimer>0){toastTimer-=dt;if(toastTimer<=0)document.querySelector('#eventToast')?.classList.remove('show')}}
  function loop(now){const dt=Math.min(.033,(now-last)/1000||0);last=now;if(S.started)update(dt);drawBackground(now/1000);if(S.started){drawFighter(S.active[0]);drawFighter(S.active[1]);drawFx(dt)}requestAnimationFrame(loop)}
  requestAnimationFrame(loop);return{tone}
}
