import{S,cfg,clamp,finish,rotate,tierColor}from'./core.js';
export function startCombat(canvas){const x=canvas.getContext('2d',{alpha:false,desynchronized:true});x.imageSmoothingEnabled=false;let last=performance.now(),shake=0,flash=0,toastTimer=0,parts=[],floats=[],audio=null,arenaImg=null;const anchors=new Map();
const gy=()=>S.h*(S.w<600?.70:.75);const tone=(f=220,d=.05,g=.025,t='square')=>{if(!S.started)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();const o=audio.createOscillator(),v=audio.createGain();o.type=t;o.frequency.value=f;v.gain.setValueAtTime(g,audio.currentTime);v.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.connect(v);v.connect(audio.destination);o.start();o.stop(audio.currentTime+d)}catch{}};
const burst=(px,py,c,n=10,p=1)=>{for(let i=0;i<n;i++){const a=Math.random()*Math.PI*2,s=(30+Math.random()*90)*p;parts.push({x:px,y:py,vx:Math.cos(a)*s,vy:Math.sin(a)*s-20,l:.35+Math.random()*.45,m:.8,c,z:2+Math.random()*4})}};const float=(px,py,t,c)=>floats.push({x:px,y:py,t,c,l:.8,m:.8});
const toast=(t,c='#ffd56b')=>{const e=document.querySelector('#eventToast');e.textContent=t;e.style.color=c;e.classList.add('show');toastTimer=1.8};const arena=a=>{arenaImg=S.images.get(a.file)||S.images.get(`./${a.file.replace(/^\.\//,'')}`)||null;document.querySelector('#arenaLabel').textContent=a.name.toUpperCase()};S.fx={tone,burst,float,toast,arena,flash:v=>flash=Math.max(flash,v)};if(S.manifest)arena(S.manifest.arenas[S.arenaIndex]);
function resize(){S.w=innerWidth;S.h=innerHeight;const d=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(S.w*d);canvas.height=Math.round(S.h*d);canvas.style.width=S.w+'px';canvas.style.height=S.h+'px';x.setTransform(d,0,0,d,0,0);x.imageSmoothingEnabled=false}addEventListener('resize',resize);resize();
const meta=(r,n=r.state)=>{const f=cfg(r.fighterId),a=f.animations[n];if(a)return{name:n,a};if(n==='special')return f.animations.attack3?{name:'attack3',a:f.animations.attack3}:f.animations.attack2?{name:'attack2',a:f.animations.attack2}:{name:'attack1',a:f.animations.attack1};if(n==='death'&&!f.animations.death)return f.animations.hurt?{name:'hurt',a:f.animations.hurt}:{name:'idle',a:f.animations.idle};return{name:'idle',a:f.animations.idle}};
const anim=(r,n)=>{if(r.state===n)return;r.state=n;r.anim=0;r.time=0;r.hit=false};const dur=r=>{const{a}=meta(r);return Math.max(.26,a.frames/a.fps)};
function anchorFor(f,im){const key=f.atlas;if(anchors.has(key))return anchors.get(key);const a=f.animations.idle;let out={x:.5,y:.88,top:.18,visibleH:.70};try{const c=document.createElement('canvas');c.width=a.frameW;c.height=a.frameH;const q=c.getContext('2d',{willReadFrequently:true});q.clearRect(0,0,c.width,c.height);q.drawImage(im,a.x||0,a.y||0,a.frameW,a.frameH,0,0,a.frameW,a.frameH);const d=q.getImageData(0,0,a.frameW,a.frameH).data;let minX=a.frameW,minY=a.frameH,maxX=-1,maxY=-1;for(let yy=0;yy<a.frameH;yy++)for(let xx=0;xx<a.frameW;xx++){const i=(yy*a.frameW+xx)*4,al=d[i+3],lum=d[i]+d[i+1]+d[i+2];if(al>18&&lum>12){if(xx<minX)minX=xx;if(xx>maxX)maxX=xx;if(yy<minY)minY=yy;if(yy>maxY)maxY=yy}}if(maxX>=minX&&maxY>=minY){out={x:((minX+maxX+1)/2)/a.frameW,y:(maxY+1)/a.frameH,top:minY/a.frameH,visibleH:Math.max(.12,(maxY-minY+1)/a.frameH)}}}catch{}anchors.set(key,out);return out}
function hit(a,b,strong){if(!b||b.dead||b.inv>0)return;const dist=Math.abs(a.x-b.x),reach=Math.max(54,a.range*Math.min(1.55,S.w/880))+(strong?22:0);if(dist>reach)return;let d=Math.max(2,a.attack*(strong?1.45:1)*(.9+Math.random()*.2)-b.defense*.32);if(b.shield>0){const q=Math.min(b.shield,d);b.shield-=q;d-=q;float(b.x,gy()-132,`SHIELD ${Math.round(q)}`,'#75cfff')}b.hp-=d;a.energy=clamp(a.energy+18,0,100);b.energy=clamp(b.energy+11,0,100);b.flash=.15;b.inv=.12;b.knock=Math.sign(b.x-a.x)*(strong?115:68);anim(b,'hurt');burst(b.x,gy()-70,strong?'#ffd56b':'#ff6579',strong?18:10,strong?1.2:.7);float(b.x,gy()-126,`-${Math.round(d)}`,strong?'#ffd56b':'#ff889a');tone(strong?120:175,.045,.018,'square');shake=Math.max(shake,strong?7:3.5);if(b.hp<=0){b.hp=0;b.dead=true;anim(b,'death');a.energy=100;finish(b,a)}}
function fighter(r,e,dt){r.time+=dt;r.anim+=dt;r.cool=Math.max(0,r.cool-dt);r.special=Math.max(0,r.special-dt);r.inv=Math.max(0,r.inv-dt);r.flash=Math.max(0,r.flash-dt);r.glow=Math.max(0,r.glow-dt);r.knock*=Math.pow(.04,dt);r.x=clamp(r.x+r.knock*dt,S.w*.08,S.w*.92);if(r.dead)return;if(r.state==='hurt'){if(r.time>=dur(r))anim(r,'idle');return}if(['attack1','attack2','attack3','special'].includes(r.state)){const d=dur(r);if(!r.hit&&r.time>=d*.56){r.hit=true;hit(r,e,r.state==='special'||r.state==='attack3')}if(r.time>=d){r.cool=.42/Math.max(.85,r.speed);anim(r,'idle')}return}const dist=Math.abs(e.x-r.x),want=Math.max(54,r.range*Math.min(1.42,S.w/920));if(dist>want+3){anim(r,'run');const dir=r.side===0?1:-1,desired=e.x-dir*want,delta=desired-r.x,maxStep=86*r.speed*dt;r.x+=clamp(delta,-maxStep,maxStep)}else if(r.cool<=0){if(r.energy>=100||(r.special<=0&&Math.random()<.18)){r.energy=Math.max(0,r.energy-70);r.special=4.5;anim(r,'special')}else anim(r,Math.random()<.32&&cfg(r.fighterId).animations.attack2?'attack2':'attack1')}else anim(r,'idle')}
function separate(a,b){if(!a||!b)return;const minGap=Math.max(34,S.w*.025);if(a.x>b.x-minGap){const mid=(a.x+b.x)/2;a.x=clamp(mid-minGap/2,S.w*.08,S.w*.88);b.x=clamp(mid+minGap/2,S.w*.12,S.w*.92);a.knock=Math.min(0,a.knock);b.knock=Math.max(0,b.knock)}}
function update(dt){if(S.round==='countdown'){S.clock-=dt;if(S.clock<=0){S.round='fighting';S.clock=90;toast('FIGHT!','#ff5aa5');tone(250,.08,.025,'square')}return}if(S.round==='finished'){S.delay-=dt;if(S.delay<=0)rotate();return}if(S.round!=='fighting')return;S.clock=Math.max(0,S.clock-dt);const[a,b]=S.active;if(!a||!b)return;fighter(a,b,dt);fighter(b,a,dt);separate(a,b);if(S.clock<=0&&!a.dead&&!b.dead){const l=a.hp<=b.hp?a:b,w=l===a?b:a;l.hp=0;l.dead=true;anim(l,'death');finish(l,w)}}
function bg(){const w=S.w,h=S.h;x.save();x.fillStyle='#080511';x.fillRect(0,0,w,h);if(shake>0){x.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);shake*=.86}if(arenaImg){const ir=arenaImg.width/arenaImg.height,cr=w/h;let dw,dh,dx,dy;if(cr>ir){dw=w;dh=w/ir;dx=0;dy=(h-dh)/2}else{dh=h;dw=h*ir;dy=0;dx=(w-dw)/2}x.drawImage(arenaImg,dx,dy,dw,dh)}else{x.fillStyle='#0b0717';x.fillRect(0,0,w,h)}const g=x.createLinearGradient(0,0,0,h);g.addColorStop(0,'rgba(4,3,12,.28)');g.addColorStop(.55,'rgba(4,3,12,.06)');g.addColorStop(1,'rgba(4,2,10,.78)');x.fillStyle=g;x.fillRect(0,0,w,h);x.fillStyle='rgba(8,5,15,.42)';x.fillRect(0,gy()+18,w,h-gy());x.strokeStyle='rgba(255,214,107,.20)';x.beginPath();x.moveTo(w*.08,gy()+16);x.lineTo(w*.92,gy()+16);x.stroke();x.restore()}
function draw(r){if(!r)return;const f=cfg(r.fighterId),im=S.images.get(f.atlas)||S.images.get(`./${f.atlas.replace(/^\.\//,'')}`);if(!im)return;const{a}=meta(r);let fr=Math.floor(r.anim*a.fps);fr=a.loop?fr%a.frames:Math.min(a.frames-1,fr);const an=anchorFor(f,im),targetVisible=S.w<600?Math.min(148,S.h*.23):Math.min(190,S.h*.28),visiblePx=Math.max(8,an.visibleH*a.frameH),sc=clamp(targetVisible/visiblePx,.65,5),W=a.frameW*sc,H=a.frameH*sc,dx=r.x-an.x*a.frameW*sc,dy=gy()-an.y*a.frameH*sc;x.save();if(r.glow>0){x.shadowColor=tierColor(f.tier);x.shadowBlur=16+r.glow*10}if(r.flash>0)x.globalAlpha=.64+Math.random()*.3;if(r.side===1){x.translate(r.x,0);x.scale(-1,1);x.translate(-r.x,0)}x.drawImage(im,(a.x||0)+fr*a.frameW,a.y||0,a.frameW,a.frameH,dx,dy,W,H);x.restore();x.globalAlpha=.38;x.fillStyle='#000';x.beginPath();x.ellipse(r.x,gy()+7,Math.max(22,targetVisible*.18),7,0,0,Math.PI*2);x.fill();x.globalAlpha=1;if(r.shield>0){x.strokeStyle='rgba(86,215,255,.72)';x.lineWidth=1.5;x.beginPath();x.ellipse(r.x,gy()-targetVisible*.48,targetVisible*.28,targetVisible*.40,0,0,Math.PI*2);x.stroke()}x.textAlign='center';x.font='700 11px system-ui';x.fillStyle='#fff';const labelY=gy()-(an.y-an.top)*a.frameH*sc-9;x.fillText(r.viewer.name,r.x,labelY)}
function fx(dt){for(const p of parts){p.l-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=90*dt}parts=parts.filter(p=>p.l>0);for(const f of floats){f.l-=dt;f.y-=24*dt}floats=floats.filter(f=>f.l>0);for(const p of parts){x.globalAlpha=clamp(p.l/p.m,0,1);x.fillStyle=p.c;x.fillRect(p.x,p.y,p.z,p.z)}for(const f of floats){x.globalAlpha=clamp(f.l/f.m,0,1);x.fillStyle=f.c;x.font='800 12px system-ui';x.textAlign='center';x.fillText(f.t,f.x,f.y)}x.globalAlpha=1;if(flash>0){flash=Math.max(0,flash-dt);x.fillStyle=`rgba(255,255,255,${Math.min(.22,flash)})`;x.fillRect(0,0,S.w,S.h)}if(toastTimer>0){toastTimer-=dt;if(toastTimer<=0)document.querySelector('#eventToast').classList.remove('show')}}
function loop(t){const dt=Math.min(.035,(t-last)/1000||0);last=t;if(S.started){update(dt);bg();draw(S.active[0]);draw(S.active[1]);fx(dt)}requestAnimationFrame(loop)}requestAnimationFrame(loop);return{tone}}
