import{S,cfg,clamp,emit,fillArena,installBridge,setArena}from'./core.js?v=1.0.7';
import{startCombat}from'./combat.js?v=1.0.7';
const VERSION='1.0.7';
const MODULES=Array.from({length:9},(_,i)=>`./assets-${i}.js?v=${VERSION}`);
const EMBEDDED_ASSETS={"./assets/street_mon.webp":"./assets/street_mon.webp"};
const assetKey=src=>{const s=String(src||'').replace(/^\.\//,'');return`./${s}`};
const $=s=>document.querySelector(s),U={q:$('#queueCount'),fq:$('#fightCount'),dq:$('#drawerQueueCount'),ql:$('#queueList'),lb:$('#leaderboard'),next:$('#nextQueue'),arena:$('#arenaLabel'),ln:$('#leftName'),ll:$('#leftLevel'),lh:$('#leftHealth'),le:$('#leftEnergy'),lc:$('#leftClass'),lw:$('#leftWins'),rn:$('#rightName'),rl:$('#rightLevel'),rh:$('#rightHealth'),re:$('#rightEnergy'),rc:$('#rightClass'),rw:$('#rightWins'),rlabel:$('#roundLabel'),timer:$('#roundTimer'),drawer:$('#drawer'),shade:$('#drawerShade'),menu:$('#menuButton'),close:$('#closeDrawer'),load:$('#loading'),bar:$('#loadProgress'),text:$('#loadText'),start:$('#startButton'),test:$('#testName')};
const hudPatch=document.createElement('style');hudPatch.textContent=`.versus-hud{top:max(54px,calc(42px + env(safe-area-inset-top)))!important}.arena-label{top:29%!important}@media(min-width:800px) and (orientation:landscape){.versus-hud{top:58px!important}.arena-label{top:27%!important}}`;document.head.append(hudPatch);
async function json(url){const r=await fetch(`${url}?v=${VERSION}`,{cache:'no-store'});if(!r.ok)throw Error(`Failed ${url} (${r.status})`);return r.json()}
async function loadAssetModules(){const errors=[];for(let i=0;i<MODULES.length;i++){U.text.textContent=`Loading asset pack ${i+1}/${MODULES.length}…`;U.bar.style.width=`${Math.round((i/MODULES.length)*30)}%`;try{const mod=await import(MODULES[i]);const pack=mod[`A${i}`]||Object.values(mod).find(v=>v&&typeof v==='object'&&!Array.isArray(v));if(!pack)throw Error(`A${i} export missing`);Object.assign(EMBEDDED_ASSETS,pack)}catch(e){errors.push(`pack ${i}: ${e?.message||e}`);console.warn('[Fighter Arena] optional asset pack failed',i,e)}}return errors}
function loadImage(src,data){return new Promise((ok,no)=>{const im=new Image;im.decoding='async';im.onload=()=>ok(im);im.onerror=()=>no(Error(`Image decode failed: ${src}`));im.src=data})}
function chooseFallbackAtlas(failedAtlas,goodAtlases){const entries=Object.values(S.manifest.fighters);const bad=entries.find(f=>f.atlas===failedAtlas);if(!bad)return goodAtlases[0];const sameTier=entries.find(f=>f.atlas!==failedAtlas&&goodAtlases.includes(f.atlas)&&f.tier===bad.tier);if(sameTier)return sameTier.atlas;const martial=goodAtlases.find(a=>/martial|knight|samurai/i.test(a));return martial||goodAtlases[0]}
async function load(){try{window.__fighterArenaReady=false;window.__fighterArenaLoadError=null;U.text.textContent='Loading fighter data…';const[f0,f1,f2,m]=await Promise.all(['./fighters-0.json','./fighters-1.json','./fighters-2.json','./manifest-core.json'].map(json));S.manifest={fighters:{...f0,...f1,...f2},...m};const moduleErrors=await loadAssetModules();const fighterAtlases=[...new Set(Object.values(S.manifest.fighters).map(f=>f.atlas))];const otherAssets=[S.manifest.effects.atlas,...S.manifest.arenas.map(a=>a.file)];const files=[...new Set([...fighterAtlases,...otherAssets])];const failed=[];let n=0;for(const src of files){const key=assetKey(src),data=EMBEDDED_ASSETS[key]||EMBEDDED_ASSETS[src]||(String(src).includes('street_mon.webp')?src:null);if(!data){failed.push(src);console.warn('[Fighter Arena] asset missing',src);continue}try{const im=await loadImage(src,data);S.images.set(src,im);S.images.set(key,im)}catch(e){failed.push(src);console.warn('[Fighter Arena] asset decode skipped',src,e)}n++;U.bar.style.width=`${30+Math.round(n/files.length*70)}%`;U.text.textContent=`Checked ${n}/${files.length} assets`}
const goodFighterAtlases=fighterAtlases.filter(a=>S.images.has(a)||S.images.has(assetKey(a)));if(!goodFighterAtlases.length)throw Error('No fighter atlas could be decoded');for(const f of Object.values(S.manifest.fighters)){if(!S.images.has(f.atlas)&&!S.images.has(assetKey(f.atlas))){const replacement=chooseFallbackAtlas(f.atlas,goodFighterAtlases);console.warn(`[Fighter Arena] ${f.name} atlas unavailable; using session fallback`,replacement);f.atlas=replacement;f.assetFallback=true}}
let arenaIndex=S.manifest.arenas.findIndex(a=>S.images.has(a.file)||S.images.has(assetKey(a.file)));if(arenaIndex<0)arenaIndex=0;setArena(arenaIndex);U.bar.style.width='100%';const fighterFailures=failed.filter(x=>fighterAtlases.includes(x));const notes=[];if(moduleErrors.length)notes.push(`${moduleErrors.length} pack recovered`);if(fighterFailures.length)notes.push(`${fighterFailures.length} fighter asset isolated`);U.text.textContent=notes.length?`Ready · ${notes.join(' · ')}`:'Fighters preloaded · ready for LIVE';U.start.disabled=false;U.start.textContent='ENTER ARENA';U.start.dataset.retry='';window.__fighterArenaReady=true;window.__fighterArenaAssetFailures={modules:moduleErrors,files:failed}}catch(e){window.__fighterArenaLoadError=e;U.text.textContent=`Load error: ${e?.message||e}`;U.start.disabled=false;U.start.textContent='RETRY LOADING';U.start.dataset.retry='1';console.error(e)}}
const panel=open=>{U.drawer.classList.toggle('open',open);U.shade.classList.toggle('open',open);U.drawer.setAttribute('aria-hidden',String(!open))};U.menu.onclick=()=>panel(true);U.close.onclick=()=>panel(false);U.shade.onclick=()=>panel(false);
function hud(r,p){for(const k of['n','l','h','e','c','w'])if(!U[p+k])return;if(!r){U[p+'n'].textContent='WAITING';U[p+'l'].textContent='—';U[p+'c'].textContent='—';U[p+'w'].textContent='0W';U[p+'h'].style.width='0%';U[p+'e'].style.width='0%';return}const v=r.viewer,f=cfg(r.fighterId);U[p+'n'].textContent=v.name;U[p+'l'].textContent=`LV ${v.level}`;U[p+'c'].textContent=f.name;U[p+'w'].textContent=`${v.wins}W`;U[p+'h'].style.width=`${clamp(r.hp/r.maxHp*100,0,100)}%`;U[p+'e'].style.width=`${clamp(r.energy,0,100)}%`}
function ui(){U.q.textContent=S.queue.length;U.dq.textContent=`${S.queue.length} waiting`;U.fq.textContent=S.fightNo;hud(S.active[0],'l');hud(S.active[1],'r');if(S.round==='countdown'){U.rlabel.textContent='READY';U.timer.textContent=Math.max(1,Math.ceil(S.clock))}else if(S.round==='fighting'){U.rlabel.textContent=`FIGHT ${S.fightNo}`;U.timer.textContent=Math.ceil(S.clock)}else if(S.round==='finished'){U.rlabel.textContent='WINNER';U.timer.textContent='KO'}else{U.rlabel.textContent='NEXT BATTLE';U.timer.textContent='VS'}U.ql.innerHTML=S.queue.length?S.queue.slice(0,12).map((v,i)=>`<div class="queue-item"><i>${i+1}</i><div><b>${v.name}</b><span>${cfg(v.fighterId).name} · LV ${v.level}</span></div><span>${v.wins}W</span></div>`).join(''):'<div class="empty">No challengers yet.</div>';const rank=[...S.viewers.values()].sort((a,b)=>b.score-a.score||b.wins-a.wins||b.level-a.level).slice(0,8);U.lb.innerHTML=rank.length?rank.map((v,i)=>`<div class="rank-item"><i>${i+1}</i><div><b>${v.name}</b><span>${cfg(v.fighterId).rarity} · LV ${v.level}</span></div><span>${v.score}</span></div>`).join(''):'<div class="empty">Leaderboard starts with the first JOIN.</div>';const q=S.queue[0];U.next.innerHTML=q?`<b>NEXT: ${q.name}</b><span>${cfg(q.fighterId).name} · LV ${q.level}</span>`:'<b>JOIN THE LIVE</b><span>Viewers enter the battle queue automatically</span>'}
function test(type){const name=(U.test.value||'Viewer').slice(0,16),userId=`viewer:${name.toLowerCase()}`;if(type==='join')emit('join',{userId,username:name});if(type==='like')emit('like',{userId,username:name,count:10});if(type==='follow')emit('follow',{userId,username:name});if(type==='rose')emit('rose',{userId,username:name,count:1});const gifts={'gift-small':5,'gift-medium':50,'gift-high':250,'gift-legend':1000};if(gifts[type])emit('gift',{userId,username:name,giftName:type,diamondCount:gifts[type]});ui()}document.querySelectorAll('[data-test]').forEach(b=>b.onclick=()=>test(b.dataset.test));
U.start.onclick=()=>{if(U.start.dataset.retry==='1'){U.start.dataset.retry='';U.start.disabled=true;U.start.textContent='ENTER ARENA';U.bar.style.width='0%';load();return}S.started=true;U.load.classList.add('done');fillArena();if(new URLSearchParams(location.search).get('demo')==='1'){['ShadowKing','PinkStorm','NeoBlade','FireBoy'].forEach((n,i)=>emit('join',{userId:'demo:'+i,username:n}));emit('follow',{userId:'demo:0',username:'ShadowKing'});emit('rose',{userId:'demo:1',username:'PinkStorm'})}};
installBridge();startCombat($('#game'));setInterval(ui,100);load();