import{A0}from'./assets-0.js';import{A1}from'./assets-1.js';import{A2}from'./assets-2.js';import{A3}from'./assets-3.js';import{A4}from'./assets-4.js';import{A5}from'./assets-5.js';import{A6}from'./assets-6.js';import{A7}from'./assets-7.js';import{A8}from'./assets-8.js';
import{S,cfg,clamp,emit,fillArena,installBridge,setArena}from'./core.js';import{startCombat}from'./combat.js';
const EMBEDDED_ASSETS={...A0,...A1,...A2,...A3,...A4,...A5,...A6,...A7,...A8};
const VERSION='1.0.2';
const assetKey=src=>{const s=String(src||'').replace(/^\.\//,'');return`./${s}`};
const $=s=>document.querySelector(s),U={q:$('#queueCount'),fq:$('#fightCount'),dq:$('#drawerQueueCount'),ql:$('#queueList'),lb:$('#leaderboard'),next:$('#nextQueue'),arena:$('#arenaLabel'),ln:$('#leftName'),ll:$('#leftLevel'),lh:$('#leftHealth'),le:$('#leftEnergy'),lc:$('#leftClass'),lw:$('#leftWins'),rn:$('#rightName'),rl:$('#rightLevel'),rh:$('#rightHealth'),re:$('#rightEnergy'),rc:$('#rightClass'),rw:$('#rightWins'),rlabel:$('#roundLabel'),timer:$('#roundTimer'),drawer:$('#drawer'),shade:$('#drawerShade'),menu:$('#menuButton'),close:$('#closeDrawer'),load:$('#loading'),bar:$('#loadProgress'),text:$('#loadText'),start:$('#startButton'),test:$('#testName')};
const hudPatch=document.createElement('style');hudPatch.textContent=`.versus-hud{top:max(54px,calc(42px + env(safe-area-inset-top)))!important}.arena-label{top:29%!important}@media(min-width:800px) and (orientation:landscape){.versus-hud{top:58px!important}.arena-label{top:27%!important}}`;document.head.append(hudPatch);
async function json(url){const r=await fetch(`${url}?v=${VERSION}`,{cache:'no-store'});if(!r.ok)throw Error(`Failed ${url}`);return r.json()}
async function load(){try{const[f0,f1,f2,m]=await Promise.all(['./fighters-0.json','./fighters-1.json','./fighters-2.json','./manifest-core.json'].map(json));S.manifest={fighters:{...f0,...f1,...f2},...m};const files=[...new Set([...Object.values(S.manifest.fighters).map(f=>f.atlas),S.manifest.effects.atlas,...S.manifest.arenas.map(a=>a.file)])];let n=0;await Promise.all(files.map(src=>new Promise((ok,no)=>{const key=assetKey(src),data=EMBEDDED_ASSETS[key];if(!data){no(Error(`Embedded asset missing: ${src}`));return}const im=new Image;im.decoding='async';im.onload=()=>{S.images.set(src,im);S.images.set(key,im);n++;U.bar.style.width=`${Math.round(n/files.length*100)}%`;U.text.textContent=`Loaded ${n}/${files.length} assets`;ok()};im.onerror=()=>no(Error(`Failed ${src}`));im.src=data})));setArena(0);U.text.textContent='Unique fighters preloaded · ready for LIVE';U.start.disabled=false}catch(e){U.text.textContent=`Load error: ${e.message}`;console.error(e)}}
const panel=open=>{U.drawer.classList.toggle('open',open);U.shade.classList.toggle('open',open);U.drawer.setAttribute('aria-hidden',String(!open))};U.menu.onclick=()=>panel(true);U.close.onclick=()=>panel(false);U.shade.onclick=()=>panel(false);
function hud(r,p){for(const k of['n','l','h','e','c','w'])if(!U[p+k])return;if(!r){U[p+'n'].textContent='WAITING';U[p+'l'].textContent='—';U[p+'c'].textContent='—';U[p+'w'].textContent='0W';U[p+'h'].style.width='0%';U[p+'e'].style.width='0%';return}const v=r.viewer,f=cfg(r.fighterId);U[p+'n'].textContent=v.name;U[p+'l'].textContent=`LV ${v.level}`;U[p+'c'].textContent=f.name;U[p+'w'].textContent=`${v.wins}W`;U[p+'h'].style.width=`${clamp(r.hp/r.maxHp*100,0,100)}%`;U[p+'e'].style.width=`${clamp(r.energy,0,100)}%`}
function ui(){U.q.textContent=S.queue.length;U.dq.textContent=`${S.queue.length} waiting`;U.fq.textContent=S.fightNo;hud(S.active[0],'l');hud(S.active[1],'r');if(S.round==='countdown'){U.rlabel.textContent='READY';U.timer.textContent=Math.max(1,Math.ceil(S.clock))}else if(S.round==='fighting'){U.rlabel.textContent=`FIGHT ${S.fightNo}`;U.timer.textContent=Math.ceil(S.clock)}else if(S.round==='finished'){U.rlabel.textContent='WINNER';U.timer.textContent='KO'}else{U.rlabel.textContent='NEXT BATTLE';U.timer.textContent='VS'}U.ql.innerHTML=S.queue.length?S.queue.slice(0,12).map((v,i)=>`<div class="queue-item"><i>${i+1}</i><div><b>${v.name}</b><span>${cfg(v.fighterId).name} · LV ${v.level}</span></div><span>${v.wins}W</span></div>`).join(''):'<div class="empty">No challengers yet.</div>';const rank=[...S.viewers.values()].sort((a,b)=>b.score-a.score||b.wins-a.wins||b.level-a.level).slice(0,8);U.lb.innerHTML=rank.length?rank.map((v,i)=>`<div class="rank-item"><i>${i+1}</i><div><b>${v.name}</b><span>${cfg(v.fighterId).rarity} · LV ${v.level}</span></div><span>${v.score}</span></div>`).join(''):'<div class="empty">Leaderboard starts with the first JOIN.</div>';const n=S.queue[0];U.next.innerHTML=n?`<b>NEXT: ${n.name}</b><span>${cfg(n.fighterId).name} · LV ${n.level}</span>`:'<b>JOIN THE LIVE</b><span>Viewers enter the battle queue automatically</span>'}
function test(type){const name=(U.test.value||'Viewer').slice(0,16),userId=`viewer:${name.toLowerCase()}`;if(type==='join')emit('join',{userId,username:name});if(type==='like')emit('like',{userId,username:name,count:10});if(type==='follow')emit('follow',{userId,username:name});if(type==='rose')emit('rose',{userId,username:name,count:1});const gifts={'gift-small':5,'gift-medium':50,'gift-high':250,'gift-legend':1000};if(gifts[type])emit('gift',{userId,username:name,giftName:type,diamondCount:gifts[type]});ui()}document.querySelectorAll('[data-test]').forEach(b=>b.onclick=()=>test(b.dataset.test));
U.start.onclick=()=>{S.started=true;U.load.classList.add('done');fillArena();if(new URLSearchParams(location.search).get('demo')==='1'){['ShadowKing','PinkStorm','NeoBlade','FireBoy'].forEach((n,i)=>emit('join',{userId:'demo:'+i,username:n}));emit('follow',{userId:'demo:0',username:'ShadowKing'});emit('rose',{userId:'demo:1',username:'PinkStorm'})}};
installBridge();startCombat($('#game'));setInterval(ui,100);load();
