import{S,cfg,clamp,emit as coreEmit,fillArena,installBridge,runtime,setArena,setAvailableFighters}from'./core.js?v=1.4.0';
import{startCombat}from'./combat-v14.js?v=1.4.0';
import{FX_ASSETS}from'./asset-effects.js?v=1.2.0';

const VERSION='1.4.0';
const MODULES=Array.from({length:9},(_,i)=>`./assets-${i}.js?v=${VERSION}`);
const RESCUE_MODULES=['asset-evil-wizard.js','asset-hero-knight.js','asset-huntress.js','asset-martial-champion.js','asset-martial-hero.js','asset-medieval-king.js','asset-evil-wizard-2.js','asset-new-roster.js','asset-medieval-warrior-2.js','asset-medieval-warrior-3.js'];
const EXTRA_FIGHTERS={
  medieval_warrior_2:{name:'Royal Vanguard',stats:{hp:164,attack:24,defense:15,speed:1.01,range:94},tier:2,rarity:'Rare',atlas:'assets/medieval_warrior_2.webp',animations:{idle:{y:0,frameW:150,frameH:150,frames:8,fps:7,loop:true},run:{y:150,frameW:150,frameH:150,frames:8,fps:11,loop:true},attack1:{y:300,frameW:150,frameH:150,frames:4,fps:12,loop:false},attack2:{y:450,frameW:150,frameH:150,frames:4,fps:12,loop:false},attack3:{y:600,frameW:150,frameH:150,frames:4,fps:13,loop:false},attack4:{y:750,frameW:150,frameH:150,frames:4,fps:13,loop:false},hurt:{y:900,frameW:150,frameH:150,frames:4,fps:12,loop:false},death:{y:1050,frameW:150,frameH:150,frames:6,fps:9,loop:false},jump:{y:1200,frameW:150,frameH:150,frames:2,fps:9,loop:false},fall:{y:1350,frameW:150,frameH:150,frames:2,fps:9,loop:false}}},
  medieval_warrior_3:{name:'Iron Warlord',stats:{hp:188,attack:30,defense:18,speed:.98,range:98},tier:3,rarity:'Epic',atlas:'assets/medieval_warrior_3.webp',animations:{idle:{y:0,frameW:135,frameH:135,frames:10,fps:7,loop:true},run:{y:135,frameW:135,frameH:135,frames:6,fps:11,loop:true},attack1:{y:270,frameW:135,frameH:135,frames:4,fps:12,loop:false},attack2:{y:405,frameW:135,frameH:135,frames:4,fps:12,loop:false},attack3:{y:540,frameW:135,frameH:135,frames:5,fps:13,loop:false},hurt:{y:675,frameW:135,frameH:135,frames:3,fps:12,loop:false},death:{y:810,frameW:135,frameH:135,frames:9,fps:9,loop:false},jump:{y:945,frameW:135,frameH:135,frames:2,fps:9,loop:false},fall:{y:1080,frameW:135,frameH:135,frames:2,fps:9,loop:false}}}
};
const ROSTER={0:['hero_knight','medieval_king','huntress_2','fire_wizard'],1:['street_mon','huntress','evil_wizard','hero_knight_prime'],2:['martial_hero','fantasy_warrior','medieval_warrior_2'],3:['martial_champion','evil_wizard_2','samurai_archer','wanderer_magician','medieval_warrior_3'],4:['samurai','samurai_commander','lightning_mage'],follow:['samurai_ronin']};
const ALL_ROSTER=Object.values(ROSTER).flat();
const tierCursor=[0,0,0,0,0];
const ASSETS={"./assets/street_mon.webp":"./assets/street_mon.webp"},HELD_URLS=new Set();
const key=src=>`./${String(src||'').replace(/^\.\//,'')}`,$=s=>document.querySelector(s);
const U={q:$('#queueCount'),fq:$('#fightCount'),dq:$('#drawerQueueCount'),ql:$('#queueList'),lb:$('#leaderboard'),next:$('#nextQueue'),arena:$('#arenaLabel'),ln:$('#leftName'),ll:$('#leftLevel'),lh:$('#leftHealth'),le:$('#leftEnergy'),lc:$('#leftClass'),lw:$('#leftWins'),rn:$('#rightName'),rl:$('#rightLevel'),rh:$('#rightHealth'),re:$('#rightEnergy'),rc:$('#rightClass'),rw:$('#rightWins'),rlabel:$('#roundLabel'),timer:$('#roundTimer'),drawer:$('#drawer'),shade:$('#drawerShade'),menu:$('#menuButton'),close:$('#closeDrawer'),load:$('#loading'),bar:$('#loadProgress'),text:$('#loadText'),start:$('#startButton')};
const patch=document.createElement('style');patch.textContent=`#game{image-rendering:auto!important}.versus-hud{top:max(40px,calc(28px + env(safe-area-inset-top)))!important}.arena-label{top:25%!important}@media(max-width:699px){.versus-hud{top:max(92px,calc(50px + env(safe-area-inset-top)))!important}.arena-label{top:24%!important}}@media(min-width:800px) and (orientation:landscape){.versus-hud{top:38px!important}.arena-label{top:24%!important}}`;document.head.append(patch);

async function json(url){const r=await fetch(`${url}?v=${VERSION}`,{cache:'no-store'});if(!r.ok)throw Error(`Failed ${url} (${r.status})`);return r.json()}
async function loadAssetModules(){const errors=[];for(let i=0;i<MODULES.length;i++){U.text.textContent=`Loading fighter pack ${i+1}/${MODULES.length}…`;U.bar.style.width=`${6+Math.round(i/MODULES.length*22)}%`;try{const mod=await import(MODULES[i]);const pack=mod[`A${i}`]||Object.values(mod).find(v=>v&&typeof v==='object'&&!Array.isArray(v));if(pack)Object.assign(ASSETS,pack);else errors.push(`pack ${i}: export missing`)}catch(e){errors.push(`pack ${i}: ${e?.message||e}`)}}for(const file of RESCUE_MODULES){try{const mod=await import(`./${file}?v=${VERSION}`);const pack=Object.values(mod).find(v=>v&&typeof v==='object'&&!Array.isArray(v));if(pack)Object.assign(ASSETS,pack)}catch(e){errors.push(`${file}: ${e?.message||e}`)}}if(errors.length)console.warn('[Fighter Arena v1.4] asset module notes',errors);return errors}
function releaseHeldUrls(){for(const u of HELD_URLS)try{URL.revokeObjectURL(u)}catch{}HELD_URLS.clear()}
function dataUriToBlobUrl(data){if(typeof data!=='string'||!data.startsWith('data:image/'))return null;const comma=data.indexOf(','),head=data.slice(0,comma),payload=data.slice(comma+1),mime=(head.match(/^data:([^;,]+)/)||[])[1]||'image/webp';if(!/;base64/i.test(head))return null;const raw=atob(payload),bytes=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)bytes[i]=raw.charCodeAt(i);return URL.createObjectURL(new Blob([bytes],{type:mime}))}
function imageFrom(url,label,timeout=9000){return new Promise((ok,no)=>{const im=new Image(),timer=setTimeout(()=>no(Error(`Image timeout: ${label}`)),timeout);im.decoding='async';im.onload=()=>{clearTimeout(timer);ok(im)};im.onerror=()=>{clearTimeout(timer);no(Error(`Image decode failed: ${label}`))};im.src=url})}
function requiredBounds(f){let w=1,h=1;for(const a of Object.values(f.animations||{})){if(!a?.frameW||!a?.frameH||!a?.frames)continue;w=Math.max(w,(a.x||0)+a.frameW*a.frames);h=Math.max(h,(a.y||0)+a.frameH)}return{w,h}}
function atlasFits(im,fighters){return fighters.every(f=>{const b=requiredBounds(f);return im.naturalWidth>=b.w&&im.naturalHeight>=b.h})}
async function decodeAtlas(src,fighters){let last=null;try{const im=await imageFrom(`${key(src)}?v=${VERSION}`,`${src} direct`,5000);if(atlasFits(im,fighters))return im;last=Error(`Direct atlas geometry mismatch ${src}`)}catch(e){last=e}const embedded=ASSETS[key(src)]||ASSETS[src];if(typeof embedded==='string'&&embedded.startsWith('data:image/')){let url=null;try{url=dataUriToBlobUrl(embedded);if(url){const im=await imageFrom(url,`${src} embedded`,10000);if(!atlasFits(im,fighters))throw Error(`Embedded atlas geometry mismatch ${im.naturalWidth}x${im.naturalHeight}`);HELD_URLS.add(url);return im}}catch(e){last=e;if(url)try{URL.revokeObjectURL(url)}catch{}}}throw last||Error(`Asset unavailable: ${src}`)}
async function loadFxAssets(){const failed=[];let i=0;for(const[name,data]of Object.entries(FX_ASSETS)){const url=dataUriToBlobUrl(data);try{const im=await imageFrom(url||data,`VFX ${name}`);S.images.set(`fx:${name}`,im)}catch{failed.push(name)}finally{if(url)URL.revokeObjectURL(url)}i++;U.bar.style.width=`${84+Math.round(i/Object.keys(FX_ASSETS).length*14)}%`}return failed}
let groups=null,loadedIds=new Set(),missingAtlases=new Set(),recoverTimer=null;
function publishAvailability(){setAvailableFighters([...loadedIds])}
async function loadFighterGroups({onlyMissing=false}={}){let i=0;const targets=[...groups.entries()].filter(([src])=>!onlyMissing||missingAtlases.has(src));for(const[src,fighters]of targets){U.text.textContent=`${onlyMissing?'Recovering':'Validating'} fighter ${i+1}/${targets.length}…`;try{const im=await decodeAtlas(src,fighters);S.images.set(src,im);S.images.set(key(src),im);for(const[id,f]of Object.entries(S.manifest.fighters))if(fighters.includes(f))loadedIds.add(id);missingAtlases.delete(src)}catch(e){missingAtlases.add(src);console.warn('[Fighter Arena v1.4] atlas pending',src,e)}i++;if(!onlyMissing)U.bar.style.width=`${30+Math.round(i/Math.max(1,targets.length)*53)}%`;publishAvailability()}}
function scheduleRecovery(){clearTimeout(recoverTimer);if(!missingAtlases.size)return;recoverTimer=setTimeout(async()=>{await loadFighterGroups({onlyMissing:true});if(missingAtlases.size)scheduleRecovery();else{U.text.textContent=`All ${loadedIds.size} fighters recovered · HD arenas ready`;if(S.started)S.fx?.toast?.('ALL FIGHTERS READY','#75ef9b')}ui()},10000)}

function nextTierFighter(t,exclude=''){const pool=(ROSTER[t]||[]).filter(id=>loadedIds.has(id)&&id!==exclude);if(!pool.length)return null;const n=tierCursor[t]++%pool.length;return pool[n]}
function syncRuntimeForViewer(v,newId){if(!v||!newId||!cfg(newId)||!loadedIds.has(newId))return;const idx=S.active.findIndex(r=>r?.viewer.id===v.id);v.fighterId=newId;v.highestTier=Math.max(v.highestTier||0,cfg(newId).tier||0);if(idx>=0){const old=S.active[idx],fresh=runtime(v,idx),ratio=old?.maxHp?clamp(old.hp/old.maxHp,.25,1):1;fresh.hp=fresh.maxHp*ratio;fresh.energy=old?.energy||0;fresh.shield=old?.shield||0;fresh.x=old?.x??fresh.x;fresh.inv=Math.max(.35,old?.inv||0);S.active[idx]=fresh}}
function forceTier(v,t){const opponent=S.active.find(r=>r&&r.viewer.id!==v.id)?.fighterId,id=nextTierFighter(t,opponent);if(id)syncRuntimeForViewer(v,id)}
function viewerFromPayload(p={},out=null){if(out?.id)return out;const raw=String(p.userId||p.id||'');if(raw&&S.viewers.has(raw))return S.viewers.get(raw);const name=String(p.username||p.uniqueId||p.name||'Viewer').replace(/[<>&\"']/g,'').trim().slice(0,16)||'Viewer';const fallback=`viewer:${name.toLowerCase().replace(/\s+/g,'-')}`;return S.viewers.get(fallback)||[...S.viewers.values()].find(v=>v.name===name)||null}
function emit(type,p={}){const t=String(type||'').toLowerCase(),out=coreEmit(type,p),v=viewerFromPayload(p,out);if(v&&['join','enter','viewerenter','member'].includes(t)&&!loadedIds.has(v.fighterId)){const id=nextTierFighter(0);if(id)syncRuntimeForViewer(v,id)}if(v&&t==='gift'&&!String(p.giftName||p.name||'').toLowerCase().includes('rose')){const d=Math.max(1,Number(p.diamondCount||p.value||p.coins||1))*Math.max(1,Number(p.repeatCount||1)),tier=d>=500?4:d>=100?3:d>=10?2:0;if(tier>=2)forceTier(v,tier)}return out}

async function load(){try{window.__fighterArenaReady=false;window.__fighterArenaLoadError=null;releaseHeldUrls();S.images.clear();loadedIds=new Set();missingAtlases=new Set();U.text.textContent='Loading fighter data…';U.bar.style.width='3%';const[f0,f1,f2,m]=await Promise.all(['./fighters-0.json','./fighters-1.json','./fighters-2.json','./manifest-core.json'].map(json));S.manifest={fighters:{...f0,...f1,...f2,...EXTRA_FIGHTERS},...m};const unknown=ALL_ROSTER.filter(id=>!S.manifest.fighters[id]);if(unknown.length)throw Error(`Roster config missing: ${unknown.join(', ')}`);const moduleErrors=await loadAssetModules();groups=new Map();for(const f of Object.values(S.manifest.fighters)){if(!groups.has(f.atlas))groups.set(f.atlas,[]);groups.get(f.atlas).push(f)}await loadFighterGroups();if(loadedIds.size<2){U.bar.style.width='83%';U.text.textContent=`Fighter retry required · ${loadedIds.size}/${ALL_ROSTER.length} ready`;U.start.disabled=false;U.start.textContent='RETRY FIGHTERS';U.start.dataset.retry='1';window.__fighterArenaAssetFailures={modules:moduleErrors,files:[...missingAtlases],vfx:[]};return}const failedFx=await loadFxAssets();setArena(0);U.bar.style.width='100%';const total=ALL_ROSTER.length,fxLoaded=Object.keys(FX_ASSETS).length-failedFx.length;U.text.textContent=missingAtlases.size?`${loadedIds.size}/${total} fighters ready · ${missingAtlases.size} recovering · ${S.manifest.arenas.length} Retina HD arenas`:`All ${total} fighters · ${fxLoaded}/${Object.keys(FX_ASSETS).length} VFX sheets · ${S.manifest.arenas.length} Retina HD arenas ready`;U.start.disabled=false;U.start.textContent='ENTER ARENA';U.start.dataset.retry='';window.__fighterArenaReady=true;window.__fighterArenaAssetFailures={modules:moduleErrors,files:[...missingAtlases],vfx:failedFx};window.__fighterArenaRoster={expected:ALL_ROSTER.length,loaded:[...loadedIds],missing:ALL_ROSTER.filter(id=>!loadedIds.has(id))};window.__fighterArenaSelectionPolicy={starters:[...ROSTER[0]],follow:ROSTER.follow[0],giftRare:[...ROSTER[2]],giftEpic:[...ROSTER[3]],giftMythic:[...ROSTER[4]]};scheduleRecovery()}catch(e){window.__fighterArenaLoadError=e;U.text.textContent=`Load error: ${e?.message||e}`;U.start.disabled=false;U.start.textContent='RETRY LOADING';U.start.dataset.retry='1';console.error(e)}}

const panel=open=>{U.drawer.classList.toggle('open',open);U.shade.classList.toggle('open',open);U.drawer.setAttribute('aria-hidden',String(!open))};U.menu.onclick=()=>panel(true);U.close.onclick=()=>panel(false);U.shade.onclick=()=>panel(false);
function hud(r,p){if(!r){U[p+'n'].textContent='WAITING';U[p+'l'].textContent='—';U[p+'c'].textContent='—';U[p+'w'].textContent='0W';U[p+'h'].style.width='0%';U[p+'e'].style.width='0%';return}const v=r.viewer,f=cfg(r.fighterId);U[p+'n'].textContent=v.name;U[p+'l'].textContent=`LV ${v.level}`;U[p+'c'].textContent=f?.name||r.fighterId;U[p+'w'].textContent=`${v.wins}W`;U[p+'h'].style.width=`${clamp(r.hp/r.maxHp*100,0,100)}%`;U[p+'e'].style.width=`${clamp(r.energy,0,100)}%`}
function ui(){U.q.textContent=S.queue.length;U.dq.textContent=`${S.queue.length} waiting`;U.fq.textContent=S.fightNo;hud(S.active[0],'l');hud(S.active[1],'r');if(S.round==='countdown'){U.rlabel.textContent='READY';U.timer.textContent=Math.max(1,Math.ceil(S.clock))}else if(S.round==='fighting'){U.rlabel.textContent=`FIGHT ${S.fightNo}`;U.timer.textContent='∞'}else if(S.round==='finished'){U.rlabel.textContent='WINNER';U.timer.textContent='KO'}else if(S.active.some(Boolean)){U.rlabel.textContent='WAITING';U.timer.textContent='IDLE'}else{U.rlabel.textContent='NEXT BATTLE';U.timer.textContent='VS'}U.ql.innerHTML=S.queue.length?S.queue.slice(0,12).map((v,i)=>`<div class="queue-item"><i>${i+1}</i><div><b>${v.name}</b><span>${cfg(v.fighterId)?.name||v.fighterId} · LV ${v.level}</span></div><span>${v.wins}W</span></div>`).join(''):'<div class="empty">No challengers yet.</div>';const rank=[...S.viewers.values()].sort((a,b)=>b.score-a.score||b.wins-a.wins||b.level-a.level).slice(0,8);U.lb.innerHTML=rank.length?rank.map((v,i)=>`<div class="rank-item"><i>${i+1}</i><div><b>${v.name}</b><span>${cfg(v.fighterId)?.rarity||'Fighter'} · LV ${v.level}</span></div><span>${v.score}</span></div>`).join(''):'<div class="empty">Leaderboard starts with the first JOIN.</div>';const q=S.queue[0],champ=S.active.find(Boolean);if(q)U.next.innerHTML=`<b>NEXT: ${q.name}</b><span>${cfg(q.fighterId)?.name||q.fighterId} · LV ${q.level}</span>`;else if(champ)U.next.innerHTML=`<b>${champ.viewer.name} IS WAITING</b><span>Waiting for the next viewer</span>`;else U.next.innerHTML='<b>JOIN THE LIVE</b><span>Viewers enter the battle queue automatically</span>'}
U.start.onclick=()=>{if(U.start.dataset.retry==='1'){U.start.dataset.retry='';U.start.disabled=true;U.start.textContent='ENTER ARENA';U.bar.style.width='0%';load();return}S.started=true;U.load.classList.add('done');fillArena()};
installBridge();if(window.FighterArenaBridge){window.FighterArenaBridge.version=VERSION;window.FighterArenaBridge.emit=emit;window.FighterArenaBridge.roster=()=>window.__fighterArenaRoster}window.dispatchFighterArenaEvent=emit;
startCombat($('#game'));setInterval(ui,200);load();
