(() => {
'use strict';
const LD=window.LD036;if(!LD)throw new Error('LD036 engine missing');
const {state,obstacles,WS,CENTER}=LD;
function navCornerNodes(respectZone=true){const out=[],p=LD.NAV_PAD+4;for(const o of obstacles){const pts=[{x:o.x-p,y:o.y-p},{x:o.x+o.w+p,y:o.y-p},{x:o.x-p,y:o.y+o.h+p},{x:o.x+o.w+p,y:o.y+o.h+p}];for(const q of pts){if(q.x<LD.PLAYER_R+3||q.x>LD.W-LD.PLAYER_R-3||q.y<LD.PLAYER_R+18||q.y>LD.H-LD.PLAYER_R-3)continue;if(LD.blocked(q.x,q.y,LD.NAV_PAD-2))continue;if(respectZone&&!LD.zoneSafe(q.x,q.y,10))continue;out.push(q)}}return out}
function pathLength(start,path){let s=0,prev=start;for(const p of path){s+=LD.dist(prev,p);prev=p}return s}
function findPath(start,goal,respectZone=true){if(!goal||LD.blocked(goal.x,goal.y,LD.PLAYER_R+2))return[];if(LD.lineClear(start,goal,LD.NAV_PAD))return[{x:goal.x,y:goal.y}];const nodes=[{x:start.x,y:start.y},{x:goal.x,y:goal.y},...navCornerNodes(respectZone)],n=nodes.length,edges=Array.from({length:n},()=>[]);for(let i=0;i<n;i++)for(let j=i+1;j<n;j++)if(LD.lineClear(nodes[i],nodes[j],LD.NAV_PAD)){const w=LD.dist(nodes[i],nodes[j]);edges[i].push([j,w]);edges[j].push([i,w])}const d=Array(n).fill(Infinity),prev=Array(n).fill(-1),used=Array(n).fill(false);d[0]=0;for(let k=0;k<n;k++){let u=-1,b=Infinity;for(let i=0;i<n;i++)if(!used[i]&&d[i]<b){b=d[i];u=i}if(u<0||u===1)break;used[u]=true;for(const[v,w]of edges[u])if(d[u]+w<d[v]){d[v]=d[u]+w;prev[v]=u}}if(!Number.isFinite(d[1]))return[];const ids=[];for(let u=1;u>0;u=prev[u]){if(u<0)return[];ids.push(u)}ids.reverse();return ids.map(i=>({x:nodes[i].x,y:nodes[i].y}))}
function validGoal(q){return q&&q.x>28&&q.x<LD.W-28&&q.y>38&&q.y<LD.H-28&&!LD.blocked(q.x,q.y,LD.PLAYER_R+2)&&LD.zoneSafe(q.x,q.y,22)}
function ring(t,r,offset,count=14){const a=[];for(let i=0;i<count;i++){const z=offset+i*Math.PI*2/count;a.push({x:t.x+Math.cos(z)*r,y:t.y+Math.sin(z)*r})}return a}
function pickFlank(p,t){const w=WS[p.weapon]||WS[0],r=LD.clamp(w.ideal,105,205),base=Math.atan2(p.y-t.y,p.x-t.x)+LD.rnd(.45,1)*(Math.random()<.5?-1:1);let best=null,score=Infinity;for(const q of ring(t,r,base)){if(!validGoal(q)||!LD.lineClear(q,t,LD.LOS_PAD+1)||LD.dist(p,q)<55)continue;const path=findPath(p,q,true);if(!path.length)continue;const s=pathLength(p,path)+Math.abs(LD.dist(q,t)-w.ideal)*.25;if(s<score){score=s;best={goal:q,path}}}return best}
function pickCover(p,t){let best=null,score=Infinity;for(const o of obstacles){const cx=o.x+o.w/2,cy=o.y+o.h/2,away=LD.norm(cx-t.x,cy-t.y),extent=Math.abs(away.x)*(o.w/2)+Math.abs(away.y)*(o.h/2),q={x:cx+away.x*(extent+LD.NAV_PAD+9),y:cy+away.y*(extent+LD.NAV_PAD+9)};if(!validGoal(q)||LD.lineClear(q,t,LD.LOS_PAD+3)||LD.dist(p,q)<45)continue;const path=findPath(p,q,true);if(!path.length)continue;const s=pathLength(p,path)+LD.dist(q,CENTER)*.015;if(s<score){score=s;best={goal:q,path}}}return best}
function pickRetreat(p,t){const away=LD.norm(p.x-t.x,p.y-t.y);for(const len of[135,105,80]){const q={x:LD.clamp(p.x+away.x*len,30,LD.W-30),y:LD.clamp(p.y+away.y*len,40,LD.H-30)};if(!validGoal(q))continue;const path=findPath(p,q,true);if(path.length)return{goal:q,path}}return null}
function pickCombat(p,t){const w=WS[p.weapon]||WS[0],d=LD.dist(p,t),base=Math.atan2(p.y-t.y,p.x-t.x),desired=LD.clamp(w.ideal,95,210),deltas=[.72,-.72,1.05,-1.05,1.35,-1.35,Math.PI*.5,-Math.PI*.5];if(d>w.ideal+70)deltas.unshift(0);if(d<w.ideal-45)deltas.unshift(Math.PI);let best=null,score=Infinity;for(const da of deltas){const r=desired+LD.rnd(-14,18),a=base+da,q={x:t.x+Math.cos(a)*r,y:t.y+Math.sin(a)*r};if(!validGoal(q)||!LD.lineClear(q,t,LD.LOS_PAD)||LD.dist(p,q)<58)continue;const path=findPath(p,q,true);if(!path.length)continue;const plen=pathLength(p,path),s=plen+Math.abs(plen-105)*.16+Math.abs(LD.dist(q,t)-w.ideal)*.12;if(s<score){score=s;best={goal:q,path}}}return best}
function initAI(p){return p.ai||(p.ai={mode:'hold',goal:null,path:[],pathIndex:0,planT:LD.rnd(.2,.55),holdT:0,lastX:p.x,lastY:p.y,stuck:0})}
function setPlan(ai,mode,plan,t){ai.mode=mode;ai.goal=plan?.goal||null;ai.path=plan?.path||[];ai.pathIndex=0;ai.planT=t;ai.holdT=0}
function planAI(p){const ai=initAI(p),t=p.target&&p.target.alive?p.target:LD.chooseTarget(p);p.target=t;const outside=Math.hypot(p.x-CENTER.x,p.y-CENTER.y)>state.zoneR-34;if(outside){const path=findPath(p,CENTER,false);setPlan(ai,'zone',{goal:CENTER,path:path.length?path:[CENTER]},.7);return}if(!t){setPlan(ai,'hold',null,.8);return}const hp=p.hp/Math.max(1,p.max),enemy=t.hp/Math.max(1,t.max),visible=LD.lineClear(p,t,LD.LOS_PAD),d=LD.dist(p,t);if((hp<.43||p.hitT>.72)&&d<315){const c=pickCover(p,t);if(c){setPlan(ai,'cover',c,LD.rnd(1.1,1.55));return}}if(!visible){const f=pickFlank(p,t);if(f){setPlan(ai,'flank',f,LD.rnd(1,1.45));return}setPlan(ai,'hold',null,.45);return}if(hp<.55&&enemy-hp>.24&&d<145){const r=pickRetreat(p,t);if(r){setPlan(ai,'retreat',r,LD.rnd(.9,1.3));return}}const c=pickCombat(p,t);if(c)setPlan(ai,'engage',c,LD.rnd(1.15,1.75));else{setPlan(ai,'hold',null,LD.rnd(.65,1));ai.holdT=LD.rnd(.35,.7)}}
function sepVelocity(p){let x=0,y=0,n=0;for(const q of state.players){if(!q.alive||q===p)continue;const dx=p.x-q.x,dy=p.y-q.y,d=Math.hypot(dx,dy);if(d>0&&d<30){const k=(30-d)/30;x+=dx/d*k;y+=dy/d*k;n++}}if(!n)return{x:0,y:0};const v=LD.norm(x/n,y/n);return{x:v.x*18,y:v.y*18}}
function waypoint(p){const ai=initAI(p);if(!ai.path.length)return null;while(ai.pathIndex<ai.path.length&&LD.dist(p,ai.path[ai.pathIndex])<14)ai.pathIndex++;if(ai.pathIndex>=ai.path.length){ai.path=[];ai.pathIndex=0;ai.holdT=LD.rnd(.22,.55);return null}for(let j=ai.path.length-1;j>ai.pathIndex;j--)if(LD.lineClear(p,ai.path[j],LD.NAV_PAD)){ai.pathIndex=j;break}return ai.path[ai.pathIndex]||null}
const approach=(c,t,d)=>c<t?Math.min(c+d,t):Math.max(c-d,t);
function shoot(p,t){const w=WS[p.weapon]||WS[0];if(p.shot>0||!t||!t.alive||LD.dist(p,t)>w.range||!LD.lineClear(p,t,LD.LOS_PAD))return;const base=Math.atan2(t.y-p.y,t.x-p.x),muzzle={x:p.x+Math.cos(base)*18,y:p.y+Math.sin(base)*18};if(LD.segmentBlocked(p,muzzle,3)||!LD.lineClear(muzzle,t,LD.LOS_PAD))return;p.shot=w.rate*(.94+Math.random()*.18);p.a=base;for(let i=0;i<w.count;i++){const a=base+(Math.random()-.5)*w.spread;state.bullets.push({x:muzzle.x,y:muzzle.y,vx:Math.cos(a)*w.speed,vy:Math.sin(a)*w.speed,life:1.35,owner:p,dmg:w.dmg*(1+(p.level-1)*.025),color:p.color})}p.flash=.06}
LD.movePlayer=(p,dt)=>{p.shot=Math.max(0,p.shot-dt);p.flash=Math.max(0,p.flash-dt);p.hitT=Math.max(0,p.hitT-dt);const ai=initAI(p);ai.planT-=dt;ai.holdT=Math.max(0,ai.holdT-dt);if(!p.target||!p.target.alive||ai.planT<=0)planAI(p);const wp=waypoint(p);if(!wp&&!ai.path.length&&ai.holdT<=0&&ai.mode!=='hold'&&ai.mode!=='cover')ai.planT=Math.min(ai.planT,.05);const sep=sepVelocity(p);let dx=sep.x,dy=sep.y,speed=0;if(wp){const v=LD.norm(wp.x-p.x,wp.y-p.y);speed=ai.mode==='zone'?92:ai.mode==='retreat'?82:ai.mode==='flank'?76:70;dx+=v.x*speed;dy+=v.y*speed}const ms=Math.hypot(dx,dy);if(ms>speed+20&&ms>0){const v=LD.norm(dx,dy);dx=v.x*(speed+20);dy=v.y*(speed+20)}const maxDelta=(wp?260:330)*dt;p.vx=approach(p.vx,dx,maxDelta);p.vy=approach(p.vy,dy,maxDelta);if(!wp&&Math.abs(p.vx)<3)p.vx=0;if(!wp&&Math.abs(p.vy)<3)p.vy=0;const ox=p.x,oy=p.y,nx=LD.clamp(p.x+p.vx*dt,LD.PLAYER_R,LD.W-LD.PLAYER_R);let collided=false;if(!LD.blocked(nx,p.y))p.x=nx;else{p.vx=0;collided=true}const ny=LD.clamp(p.y+p.vy*dt,LD.PLAYER_R+16,LD.H-LD.PLAYER_R);if(!LD.blocked(p.x,ny))p.y=ny;else{p.vy=0;collided=true}if(LD.blocked(p.x,p.y)){p.x=ox;p.y=oy;p.vx=p.vy=0;collided=true}const moved=Math.hypot(p.x-ai.lastX,p.y-ai.lastY);ai.lastX=p.x;ai.lastY=p.y;if(wp&&moved<.18)ai.stuck+=dt;else ai.stuck=Math.max(0,ai.stuck-dt*1.7);if(collided||ai.stuck>.55){ai.path=[];ai.pathIndex=0;ai.planT=.04;ai.stuck=0}const dz=Math.hypot(p.x-CENTER.x,p.y-CENTER.y);if(dz>state.zoneR-12){LD.damage(p,7*dt,null);ai.planT=.02}const t=p.target;if(t&&t.alive&&LD.lineClear(p,t,LD.LOS_PAD)){p.a=Math.atan2(t.y-p.y,t.x-p.x);shoot(p,t)}else if(Math.hypot(p.vx,p.vy)>8)p.a=Math.atan2(p.vy,p.vx)};
function hitSegment(ax,ay,bx,by,p){const vx=bx-ax,vy=by-ay,wx=p.x-ax,wy=p.y-ay,den=vx*vx+vy*vy||1,t=LD.clamp((wx*vx+wy*vy)/den,0,1),cx=ax+vx*t,cy=ay+vy*t;return Math.hypot(p.x-cx,p.y-cy)<LD.FIGHTER_HIT}
LD.updateBullets=dt=>{for(let i=state.bullets.length-1;i>=0;i--){const b=state.bullets[i];b.life-=dt;if(b.life<=0){state.bullets.splice(i,1);continue}const travel=Math.hypot(b.vx*dt,b.vy*dt),steps=Math.max(1,Math.ceil(travel/4)),sx=b.vx*dt/steps,sy=b.vy*dt/steps;let removed=false;for(let s=0;s<steps;s++){const ax=b.x,ay=b.y,bx=ax+sx,by=ay+sy;if(bx<0||bx>LD.W||by<0||by>LD.H||LD.segmentBlocked({x:ax,y:ay},{x:bx,y:by},2)||LD.blocked(bx,by,2)){state.bullets.splice(i,1);removed=true;break}const hit=state.players.find(p=>p.alive&&p!==b.owner&&hitSegment(ax,ay,bx,by,p));if(hit){LD.damage(hit,b.dmg,b.owner);state.bullets.splice(i,1);removed=true;break}b.x=bx;b.y=by}if(removed)continue}};
LD.findPath=findPath;
})();
