(() => {
  'use strict';
  const params=new URLSearchParams(location.search), JOIN=new Set(['join','play','entra','gioca','drop','dropzone']), API='https://tik.tools/api/live/connect';
  const liveUser=String(params.get('liveUser')||params.get('tiktokUser')||'').replace(/^@/,'').trim(), useCloud=!!liveUser&&params.get('bridge')!=='off', joined=new Set();
  let socket=null,timer=null,attempt=0,stopped=false;
  const obj=v=>!!v&&typeof v==='object'&&!Array.isArray(v), clean=v=>String(v||'').replace(/^@/,'').trim().slice(0,32)||'Viewer';
  function state(text,s='ready'){document.documentElement.dataset.dropzoneBridge=s;let e=document.querySelector('#bridgeState');if(e)e.textContent=`LIVE bridge · ${text}`}
  function identity(d){let u=obj(d?.user)?d.user:{},username=clean(u.uniqueId||u.unique_id||d?.uniqueId||d?.unique_id||d?.user_unique_id||u.nickname||d?.nickname||d?.username),userId=String(u.secUid||u.sec_uid||u.id||d?.senderUserId||d?.sender_user_id||d?.userId||d?.user_id||`viewer:${username.toLowerCase()}`);return{userId,username,uniqueId:username}}
  function command(comment){let first=String(comment||'').trim().toLowerCase().split(/\s+/)[0].replace(/^[!/.#]+/,'');return JOIN.has(first)?first:''}
  function normalize(raw){if(!obj(raw))return null;if(raw.type&&raw.payload&&['join','like','follow','gift'].includes(String(raw.type).toLowerCase()))return{type:String(raw.type).toLowerCase(),payload:raw.payload};let d=obj(raw.data)?raw.data:raw,n=String(raw.event||raw.type||d.type||'').toLowerCase().replace(/[\s_-]+/g,'');if(!n)return null;let base=identity(d);if(n.includes('chat')||n.includes('comment')){let comment=String(d.comment??d.text??d.content??'').trim(),cmd=command(comment);return cmd?{type:'join',payload:{...base,comment,command:cmd}}:null}if(n.includes('like'))return{type:'like',payload:{...base,count:Math.max(1,Number(d.likeCount??d.like_count??d.count??1)||1)}};if(n.includes('follow')||(n.includes('social')&&String(d.action||'').toLowerCase().includes('follow')))return{type:'follow',payload:base};if(n.includes('gift'))return{type:'gift',payload:{...base,giftName:String(d.giftName||d.gift_name||d.gift?.name||'gift'),diamondCount:Math.max(1,Number(d.diamondCount??d.diamond_count??d.gift?.diamondCount??1)||1),repeatCount:Math.max(1,Number(d.repeatCount??d.repeat_count??d.count??1)||1)}};return null}
  function key(p={}){return String(p.userId||p.uniqueId||p.username||'').toLowerCase()}
  function emit(type,payload={}){let k=key(payload);if(type==='join'){if(k)joined.add(k)}else if(!k||!joined.has(k))return false;window.dispatchEvent(new CustomEvent('live-dropzone:event',{detail:{type,payload}}));return true}
  function ingest(raw){if(Array.isArray(raw)){raw.forEach(ingest);return}let e=normalize(raw);if(e)emit(e.type,e.payload);return e}
  window.addEventListener('message',e=>{if(e.source!==window&&!obj(e.data))return;ingest(e.data)});
  function retry(){if(!useCloud||stopped)return;let d=[1800,3000,5000,8000,12000][Math.min(attempt++,4)];clearTimeout(timer);timer=setTimeout(connect,d)}
  async function connect(){if(!useCloud||stopped)return;clearTimeout(timer);state(`connessione @${liveUser}…`,'connecting');try{let r=await fetch(`${API}?uniqueId=${encodeURIComponent(liveUser)}`,{cache:'no-store',credentials:'omit'}),t=await r.json();if(!r.ok||!t?.token||!t?.wsUrl)throw new Error(t?.message||`cloud ${r.status}`);if(t.stream?.alive===false)throw Object.assign(new Error('not live'),{code:'NOT_LIVE'});let u=new URL(t.wsUrl);u.searchParams.set('uniqueId',liveUser);u.searchParams.set('jwtKey',t.token);socket=new WebSocket(u.toString());socket.addEventListener('open',()=>{attempt=0;state(`@${liveUser} online`,'online')});socket.addEventListener('message',e=>{try{ingest(JSON.parse(e.data))}catch{}});socket.addEventListener('close',retry,{once:true});socket.addEventListener('error',()=>{try{socket?.close()}catch{retry()}},{once:true})}catch(e){state(e?.code==='NOT_LIVE'?`@${liveUser} non è LIVE`:`retry @${liveUser}`,'waiting');retry()}}
  window.LiveDropzoneBridge=Object.freeze({emit,ingest,normalize,get socket(){return socket},get liveUser(){return liveUser},get joinedCount(){return joined.size},disconnect(){stopped=true;clearTimeout(timer);try{socket?.close()}catch{}socket=null;state('disconnesso','off')}});
  if(params.get('demo')==='1')state('DEMO locale','demo');else if(useCloud)connect();else state('pronto · nessuna connessione attiva','ready');
})();
