(() => {
'use strict';
const $=s=>document.querySelector(s),canvas=$('#gameCanvas'),ctx=canvas.getContext('2d',{alpha:false});
const LD=window.LD036={version:'0.3.6',W:960,H:540,MAX:18,DEMO:new URLSearchParams(location.search).get('demo')==='1',FIGHTER_W:38,FIGHTER_HIT:11,PLAYER_R:13,NAV_PAD:18,LOS_PAD:6,CENTER:{x:480,y:270},canvas,ctx,source:null,started:false,idSeed:1};
ctx.imageSmoothingEnabled=true;
LD.ui={alive:$('#aliveCount'),timer:$('#zoneTimer'),board:$('#leaderboardList'),feed:$('#killFeed'),queue:$('#queueCount'),wait:$('#waitingOverlay'),banner:$('#roundBanner'),bk:$('#roundBannerKicker'),bn:$('#roundBannerName'),mode:$('#modeBadge'),demo:$('#demoPanel')};
LD.COLORS=['#ffb11f','#61c7ff','#f04c2b','#f4f4f4','#28455f','#78905b','#d4bb62','#c69814','#1bbc7d','#929292','#b76b56','#ff5a1e','#c6cdd1','#e9edf1','#73965e','#4f8dd8'];
LD.names=['NIGHTHAWK','LUNA_PLAYS','FASTFURY','PIXELPANDA','SILENTFOX','BLAZE_ON','GHOST_77','QUEENBEE','ICYBOY','DRAGONYT','ROOKIE99','NOVA','KRAKEN','VOLT','RAVEN','ASTRA'];
LD.obstacles=[{x:95,y:78,w:150,h:42},{x:355,y:58,w:112,h:58},{x:700,y:74,w:158,h:42},{x:220,y:176,w:54,h:120},{x:423,y:170,w:118,h:48},{x:685,y:160,w:58,h:122},{x:95,y:342,w:152,h:44},{x:350,y:350,w:115,h:58},{x:704,y:338,w:154,h:46},{x:518,y:276,w:62,h:122}];
LD.WS=[{speed:440,rate:.74,dmg:16,spread:.045,count:1,ideal:145,range:310},{speed:470,rate:.55,dmg:14,spread:.07,count:1,ideal:155,range:325},{speed:420,rate:.92,dmg:9,spread:.22,count:4,ideal:92,range:220},{speed:520,rate:.34,dmg:11,spread:.09,count:1,ideal:190,range:365},{speed:570,rate:.22,dmg:10,spread:.12,count:1,ideal:205,range:390}];
LD.state={players:[],bullets:[],fx:[],pickups:[],queue:[],feed:[],round:1,time:0,zoneT:110,zoneR:455,ended:false,last:performance.now(),lastUI:0};
LD.clamp=(v,a,b)=>Math.max(a,Math.min(b,v));LD.rnd=(a,b)=>a+Math.random()*(b-a);LD.dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
LD.norm=(x,y)=>{const l=Math.hypot(x,y)||1;return{x:x/l,y:y/l}};
LD.insideRect=(x,y,r,o)=>x+r>o.x&&x-r<o.x+o.w&&y+r>o.y&&y-r<o.y+o.h;
LD.blocked=(x,y,r=LD.PLAYER_R)=>LD.obstacles.some(o=>LD.insideRect(x,y,r,o));
LD.zoneSafe=(x,y,m=24)=>Math.hypot(x-LD.CENTER.x,y-LD.CENTER.y)<Math.max(70,LD.state.zoneR-m);
LD.segmentHitsRect=(ax,ay,bx,by,o,pad=0)=>{const minX=o.x-pad,maxX=o.x+o.w+pad,minY=o.y-pad,maxY=o.y+o.h+pad;let t0=0,t1=1,dx=bx-ax,dy=by-ay;const P=[-dx,dx,-dy,dy],Q=[ax-minX,maxX-ax,ay-minY,maxY-ay];for(let i=0;i<4;i++){if(Math.abs(P[i])<1e-8){if(Q[i]<0)return false;continue}const r=Q[i]/P[i];if(P[i]<0){if(r>t1)return false;if(r>t0)t0=r}else{if(r<t0)return false;if(r<t1)t1=r}}return true};
LD.segmentBlocked=(a,b,pad=0)=>LD.obstacles.some(o=>LD.segmentHitsRect(a.x,a.y,b.x,b.y,o,pad));
LD.lineClear=(a,b,pad=LD.LOS_PAD)=>!LD.segmentBlocked(a,b,pad);
const cleanName=v=>String(v||'Viewer').replace(/^@/,'').trim().slice(0,18)||'Viewer',keyOf=(p={})=>String(p.userId||p.uniqueId||p.username||'').toLowerCase();
LD.find=p=>{const k=keyOf(p);return LD.state.players.find(x=>x.key===k||x.name.toLowerCase()===k)};
LD.safeSpawn=()=>{for(let i=0;i<160;i++){const q={x:LD.rnd(55,LD.W-55),y:LD.rnd(55,LD.H-45)};if(!LD.blocked(q.x,q.y,24)&&Math.hypot(q.x-LD.CENTER.x,q.y-LD.CENTER.y)<LD.state.zoneR-38)return q}return{x:LD.CENTER.x,y:LD.CENTER.y}};
LD.burst=(x,y,color,n=6)=>{for(let i=0;i<n;i++){const a=LD.rnd(0,Math.PI*2),s=LD.rnd(20,105);LD.state.fx.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:LD.rnd(.15,.55),max:.55,color})}};
LD.add=(payload={})=>{const e=LD.find(payload);if(e)return e;const name=cleanName(payload.username||payload.uniqueId),key=String(payload.userId||payload.uniqueId||name).toLowerCase();if(LD.state.ended||LD.state.players.filter(p=>p.alive).length>=LD.MAX||LD.state.zoneT<18){if(!LD.state.queue.some(q=>q.key===key))LD.state.queue.push({key,name,payload});LD.syncUI?.();return null}const s=LD.safeSpawn(),skin=(LD.idSeed-1)%16,p={id:LD.idSeed++,key,name,x:s.x,y:s.y,vx:0,vy:0,a:LD.rnd(0,Math.PI*2),hp:100,max:100,shield:0,level:1,weapon:0,kills:0,alive:true,shot:LD.rnd(.2,.8),target:null,skin,color:LD.COLORS[skin],flash:0,followed:false,score:0,walkPhase:LD.rnd(0,Math.PI*2),ai:null,hitT:0};LD.state.players.push(p);LD.ui.wait.hidden=true;LD.burst(p.x,p.y,p.color,10);LD.syncUI?.();return p};
LD.heal=(p,n)=>{if(!p||!p.alive)return;p.hp=LD.clamp(p.hp+n,0,p.max);LD.burst(p.x,p.y,'#5aff8b',5)};
LD.upgrade=(p,n=1)=>{if(!p||!p.alive)return;p.level=LD.clamp(p.level+n,1,12);p.max=100+(p.level-1)*8;p.hp=LD.clamp(p.hp+18,0,p.max);p.weapon=LD.clamp(Math.floor((p.level-1)/2),0,4);p.shield=LD.clamp(p.shield+12,0,65);LD.burst(p.x,p.y,'#ffd34f',10)};
LD.damage=(p,n,owner)=>{if(!p||!p.alive)return;const sh=Math.min(p.shield,n);p.shield-=sh;n-=sh;p.hp-=n;p.hitT=1.2;LD.burst(p.x,p.y,n>20?'#ff725b':'#fff',4);if(p.hp<=0){p.alive=false;p.hp=0;p.vx=p.vy=0;if(owner&&owner!==p){owner.kills++;owner.score+=100}LD.state.feed.unshift(`${owner?.name||'ZONA'} ✕ ${p.name}`);LD.state.feed=LD.state.feed.slice(0,5);LD.burst(p.x,p.y,'#ff4a43',18);const alive=LD.state.players.filter(x=>x.alive);if(alive.length===1&&LD.state.players.length>1)LD.finish?.(alive[0])}};
LD.airstrike=owner=>{for(let i=0;i<3;i++)setTimeout(()=>{const enemies=LD.state.players.filter(p=>p.alive&&p!==owner);if(!enemies.length)return;const t=enemies[(Math.random()*enemies.length)|0];LD.burst(t.x,t.y,'#ff713d',24);LD.damage(t,34,owner)},i*180)};
LD.gift=(p,d=1,name='gift')=>{if(!p||!p.alive)return;if(/rose|rosa/i.test(name)){LD.upgrade(p,1);return}if(d>=100){LD.airstrike(p);LD.upgrade(p,2)}else if(d>=20){p.weapon=LD.clamp(p.weapon+1,0,4);p.shield=LD.clamp(p.shield+30,0,80);LD.burst(p.x,p.y,'#c979ff',14)}else{LD.heal(p,20+d*.4);p.shield=LD.clamp(p.shield+10,0,60)}};
LD.event=(type,payload={})=>{const p=LD.find(payload);if(type==='join')LD.add(payload);else if(type==='like')LD.heal(p,Math.min(24,2+Math.sqrt(Math.max(1,+payload.count||1))*2.2));else if(type==='follow'&&p&&!p.followed){p.followed=true;p.weapon=LD.clamp(p.weapon+1,0,4);p.shield=LD.clamp(p.shield+28,0,70);LD.burst(p.x,p.y,'#6cf26e',12)}else if(type==='gift')LD.gift(p,Math.max(1,+payload.diamondCount||1)*Math.max(1,+payload.repeatCount||1),payload.giftName)};
LD.chooseTarget=p=>{let best=null,bestScore=1e9;for(const q of LD.state.players){if(!q.alive||q===p)continue;const visible=LD.lineClear(p,q,LD.LOS_PAD),d=LD.dist(p,q),weak=(1-q.hp/Math.max(1,q.max))*65,score=d+(visible?0:145)-weak+(q.weapon||0)*3;if(score<bestScore){bestScore=score;best=q}}return best};
window.addEventListener('live-dropzone:event',e=>LD.event(e.detail?.type,e.detail?.payload));
})();
