(() => {
'use strict';
const $=s=>document.querySelector(s),canvas=$('#gameCanvas'),ctx=canvas.getContext('2d',{alpha:false});
const W=960,H=540,MAX=18,DEMO=new URLSearchParams(location.search).get('demo')==='1',FIGHTER_W=38,FIGHTER_HIT=11,PLAYER_R=13,CENTER={x:W/2,y:H/2};
ctx.imageSmoothingEnabled=true;
const ui={alive:$('#aliveCount'),timer:$('#zoneTimer'),board:$('#leaderboardList'),feed:$('#killFeed'),queue:$('#queueCount'),wait:$('#waitingOverlay'),banner:$('#roundBanner'),bk:$('#roundBannerKicker'),bn:$('#roundBannerName'),mode:$('#modeBadge'),demo:$('#demoPanel')};
const COLORS=['#ffb11f','#61c7ff','#f04c2b','#f4f4f4','#28455f','#78905b','#d4bb62','#c69814','#1bbc7d','#929292','#b76b56','#ff5a1e','#c6cdd1','#e9edf1','#73965e','#4f8dd8'];
const names=['NIGHTHAWK','LUNA_PLAYS','FASTFURY','PIXELPANDA','SILENTFOX','BLAZE_ON','GHOST_77','QUEENBEE','ICYBOY','DRAGONYT','ROOKIE99','NOVA','KRAKEN','VOLT','RAVEN','ASTRA'];
const obstacles=[{x:95,y:78,w:150,h:42},{x:355,y:58,w:112,h:58},{x:700,y:74,w:158,h:42},{x:220,y:176,w:54,h:120},{x:423,y:170,w:118,h:48},{x:685,y:160,w:58,h:122},{x:95,y:342,w:152,h:44},{x:350,y:350,w:115,h:58},{x:704,y:338,w:154,h:46},{x:518,y:276,w:62,h:122}];
const state={players:[],bullets:[],fx:[],pickups:[],queue:[],feed:[],round:1,time:0,zoneT:110,zoneR:455,ended:false,last:performance.now(),lastUI:0};
let idSeed=1,source=null,started=false;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),rnd=(a,b)=>a+Math.random()*(b-a),dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
function norm(x,y){const l=Math.hypot(x,y)||1;return{x:x/l,y:y/l}}function insideRect(x,y,r,o){return x+r>o.x&&x-r<o.x+o.w&&y+r>o.y&&y-r<o.y+o.h}function blocked(x,y,r=PLAYER_R){return obstacles.some(o=>insideRect(x,y,r,o))}function zoneSafe(x,y,m=24){return Math.hypot(x-CENTER.x,y-CENTER.y)<Math.max(70,state.zoneR-m)}
function cleanName(v){return String(v||'Viewer').replace(/^@/,'').trim().slice(0,18)||'Viewer'}function keyOf(p={}){return String(p.userId||p.uniqueId||p.username||'').toLowerCase()}function find(p){const k=keyOf(p);return state.players.find(x=>x.key===k||x.name.toLowerCase()===k)}
function safeSpawn(){for(let i=0;i<120;i++){const q={x:rnd(55,W-55),y:rnd(55,H-45)};if(!blocked(q.x,q.y,22)&&Math.hypot(q.x-CENTER.x,q.y-CENTER.y)<state.zoneR-38)return q}return{x:CENTER.x,y:CENTER.y}}
function add(payload={}){const e=find(payload);if(e)return e;const name=cleanName(payload.username||payload.uniqueId),key=String(payload.userId||payload.uniqueId||name).toLowerCase();if(state.ended||state.players.filter(p=>p.alive).length>=MAX||state.zoneT<18){if(!state.queue.some(q=>q.key===key))state.queue.push({key,name,payload});syncUI();return null}const s=safeSpawn(),skin=(idSeed-1)%16,p={id:idSeed++,key,name,x:s.x,y:s.y,vx:0,vy:0,a:rnd(0,Math.PI*2),hp:100,max:100,shield:0,level:1,weapon:0,kills:0,alive:true,shot:rnd(.2,.8),target:null,skin,color:COLORS[skin],flash:0,followed:false,score:0,walkPhase:rnd(0,Math.PI*2),ai:null,hitT:0};state.players.push(p);ui.wait.hidden=true;burst(p.x,p.y,p.color,10);syncUI();return p}
function heal(p,n){if(!p||!p.alive)return;p.hp=clamp(p.hp+n,0,p.max);burst(p.x,p.y,'#5aff8b',5)}function upgrade(p,n=1){if(!p||!p.alive)return;p.level=clamp(p.level+n,1,12);p.max=100+(p.level-1)*8;p.hp=clamp(p.hp+18,0,p.max);p.weapon=clamp(Math.floor((p.level-1)/2),0,4);p.shield=clamp(p.shield+12,0,65);burst(p.x,p.y,'#ffd34f',10)}
function gift(p,d=1,name='gift'){if(!p||!p.alive)return;if(/rose|rosa/i.test(name)){upgrade(p,1);return}if(d>=100){airstrike(p);upgrade(p,2)}else if(d>=20){p.weapon=clamp(p.weapon+1,0,4);p.shield=clamp(p.shield+30,0,80);burst(p.x,p.y,'#c979ff',14)}else{heal(p,20+d*.4);p.shield=clamp(p.shield+10,0,60)}}
function airstrike(owner){for(let i=0;i<3;i++)setTimeout(()=>{const enemies=state.players.filter(p=>p.alive&&p!==owner);if(!enemies.length)return;const t=enemies[(Math.random()*enemies.length)|0];burst(t.x,t.y,'#ff713d',24);damage(t,34,owner)},i*180)}
function event(type,payload={}){const p=find(payload);if(type==='join')add(payload);else if(type==='like')heal(p,Math.min(24,2+Math.sqrt(Math.max(1,+payload.count||1))*2.2));else if(type==='follow'&&p&&!p.followed){p.followed=true;p.weapon=clamp(p.weapon+1,0,4);p.shield=clamp(p.shield+28,0,70);burst(p.x,p.y,'#6cf26e',12)}else if(type==='gift')gift(p,Math.max(1,+payload.diamondCount||1)*Math.max(1,+payload.repeatCount||1),payload.giftName)}
window.addEventListener('live-dropzone:event',e=>event(e.detail?.type,e.detail?.payload));
const WS=[{speed:440,rate:.74,dmg:16,spread:.045,count:1,ideal:145,range:310},{speed:470,rate:.55,dmg:14,spread:.07,count:1,ideal:155,range:325},{speed:420,rate:.92,dmg:9,spread:.22,count:4,ideal:92,range:220},{speed:520,rate:.34,dmg:11,spread:.09,count:1,ideal:190,range:365},{speed:570,rate:.22,dmg:10,spread:.12,count:1,ideal:205,range:390}];
function segmentHitsRect(ax,ay,bx,by,o,pad=3){const minX=o.x-pad,maxX=o.x+o.w+pad,minY=o.y-pad,maxY=o.y+o.h+pad;let t0=0,t1=1,dx=bx-ax,dy=by-ay;const P=[-dx,dx,-dy,dy],Q=[ax-minX,maxX-ax,ay-minY,maxY-ay];for(let i=0;i<4;i++){if(Math.abs(P[i])<1e-7){if(Q[i]<0)return false;continue}const r=Q[i]/P[i];if(P[i]<0){if(r>t1)return false;if(r>t0)t0=r}else{if(r<t0)return false;if(r<t1)t1=r}}return true}
function lineClear(a,b,pad=3){return !obstacles.some(o=>segmentHitsRect(a.x,a.y,b.x,b.y,o,pad))}
function shoot(p,t){const w=WS[p.weapon]||WS[0];if(p.shot>0||!t||!lineClear(p,t,2)||dist(p,t)>w.range)return;p.shot=w.rate*(.94+Math.random()*.18);p.a=Math.atan2(t.y-p.y,t.x-p.x);for(let i=0;i<w.count;i++){const a=p.a+(Math.random()-.5)*w.spread;state.bullets.push({x:p.x+Math.cos(a)*27,y:p.y+Math.sin(a)*27,vx:Math.cos(a)*w.speed,vy:Math.sin(a)*w.speed,life:1.35,owner:p,dmg:w.dmg*(1+(p.level-1)*.025),color:p.color})}p.flash=.06}
function damage(p,n,owner){if(!p||!p.alive)return;const sh=Math.min(p.shield,n);p.shield-=sh;n-=sh;p.hp-=n;p.hitT=1.2;burst(p.x,p.y,n>20?'#ff725b':'#fff',4);if(p.hp<=0){p.alive=false;p.hp=0;p.vx=p.vy=0;if(owner&&owner!==p){owner.kills++;owner.score+=100}state.feed.unshift(`${owner?.name||'ZONA'} ✕ ${p.name}`);state.feed=state.feed.slice(0,5);burst(p.x,p.y,'#ff4a43',18);const alive=state.players.filter(x=>x.alive);if(alive.length===1&&state.players.length>1)finish(alive[0])}}
function chooseTarget(p){let best=null,score=1e9;for(const q of state.players){if(!q.alive||q===p)continue;const s=dist(p,q)-(1-q.hp/Math.max(1,q.max))*70+((q.weapon||0)*8+(q.level||1)*2)*.25;if(s<score){score=s;best=q}}return best}
function separation(p){let x=0,y=0;for(const q of state.players){if(!q.alive||q===p)continue;const dx=p.x-q.x,dy=p.y-q.y,d=Math.hypot(dx,dy);if(d>0&&d<34){const k=(34-d)/34;x+=dx/d*k;y+=dy/d*k}}return{x,y}}
function obstacleAvoidance(p,d){let ax=0,ay=0,look=44,fx=p.x+d.x*look,fy=p.y+d.y*look;for(const o of obstacles){const nx=clamp(fx,o.x-PLAYER_R-5,o.x+o.w+PLAYER_R+5),ny=clamp(fy,o.y-PLAYER_R-5,o.y+o.h+PLAYER_R+5);let dx=fx-nx,dy=fy-ny,dd=Math.hypot(dx,dy);if(dd<30){if(dd<1){dx=fx-(o.x+o.w/2);dy=fy-(o.y+o.h/2);dd=Math.hypot(dx,dy)||1}const k=(30-dd)/30;ax+=dx/dd*k*1.8;ay+=dy/dd*k*1.8}}return{x:ax,y:ay}}
function coverPoint(p,t){let best=null,score=1e9;for(const o of obstacles){const cx=o.x+o.w/2,cy=o.y+o.h/2,away=norm(cx-t.x,cy-t.y),extent=Math.abs(away.x)*(o.w/2)+Math.abs(away.y)*(o.h/2),q={x:cx+away.x*(extent+25),y:cy+away.y*(extent+25)};if(q.x<25||q.x>W-25||q.y<35||q.y>H-25||blocked(q.x,q.y)||!zoneSafe(q.x,q.y,28)||lineClear(q,t,8))continue;const pd=Math.hypot(q.x-p.x,q.y-p.y);if(pd>255)continue;const s=pd+Math.hypot(q.x-CENTER.x,q.y-CENTER.y)*.02;if(s<score){score=s;best=q}}return best}
function flankPoint(p,t,side){const to=norm(t.x-p.x,t.y-p.y),perp={x:-to.y*side,y:to.x*side},q={x:clamp(t.x-to.x*115+perp.x*90,30,W-30),y:clamp(t.y-to.y*115+perp.y*90,38,H-30)};return blocked(q.x,q.y)||!zoneSafe(q.x,q.y,28)?null:q}
function initAI(p){return p.ai||(p.ai={mode:'engage',goal:null,decision:0,strafe:Math.random()<.5?-1:1,lastX:p.x,lastY:p.y,stuck:0})}
function decide(p){const ai=initAI(p),t=p.target&&p.target.alive?p.target:chooseTarget(p);p.target=t;ai.decision=rnd(.28,.52);if(!t){ai.mode='idle';ai.goal=null;return}const d=dist(p,t),hp=p.hp/Math.max(1,p.max),visible=lineClear(p,t,4),enemyHp=t.hp/Math.max(1,t.max),outside=Math.hypot(p.x-CENTER.x,p.y-CENTER.y)>state.zoneR-36;if(outside){ai.mode='zone';ai.goal=CENTER;return}if((hp<.42||p.hitT>.55)&&d<310){const c=coverPoint(p,t);if(c){ai.mode='cover';ai.goal=c;return}}if(!visible){ai.mode='flank';ai.strafe*=-1;ai.goal=flankPoint(p,t,ai.strafe)||{x:t.x,y:t.y};return}if(hp<.58&&enemyHp-hp>.28&&d<130){ai.mode='retreat';ai.goal=null;return}ai.mode='engage';ai.goal=null;if(Math.random()<.25)ai.strafe*=-1}
function desiredFor(p){const ai=initAI(p),t=p.target;if(!t||!t.alive)return{x:0,y:0,speed:0};if(ai.mode==='zone'){const v=norm(CENTER.x-p.x,CENTER.y-p.y);return{x:v.x,y:v.y,speed:90}}if(ai.mode==='cover'&&ai.goal){const d=Math.hypot(ai.goal.x-p.x,ai.goal.y-p.y);if(d<12){if(p.hitT<.35&&lineClear(p,t,3)){ai.mode='engage';ai.decision=.15}return{x:0,y:0,speed:0}}const v=norm(ai.goal.x-p.x,ai.goal.y-p.y);return{x:v.x,y:v.y,speed:70}}if(ai.mode==='flank'&&ai.goal){if(Math.hypot(ai.goal.x-p.x,ai.goal.y-p.y)<18){ai.mode='engage';ai.decision=.1}const v=norm(ai.goal.x-p.x,ai.goal.y-p.y);return{x:v.x,y:v.y,speed:68}}const dx=t.x-p.x,dy=t.y-p.y,d=Math.hypot(dx,dy)||1,dir={x:dx/d,y:dy/d};if(ai.mode==='retreat')return{x:-dir.x,y:-dir.y,speed:76};const w=WS[p.weapon]||WS[0],perp={x:-dir.y*ai.strafe,y:dir.x*ai.strafe};let radial=d>w.ideal+38?1:d<w.ideal-28?-.78:.08;const v=norm(dir.x*radial+perp.x*.34,dir.y*radial+perp.y*.34);return{x:v.x,y:v.y,speed:p.weapon===2?72:62}}
function movePlayer(p,dt){p.shot=Math.max(0,p.shot-dt);p.flash=Math.max(0,p.flash-dt);p.hitT=Math.max(0,p.hitT-dt);const ai=initAI(p);ai.decision-=dt;const moved=Math.hypot(p.x-ai.lastX,p.y-ai.lastY);if(Math.hypot(p.vx,p.vy)>28&&moved<.45)ai.stuck+=dt;else ai.stuck=Math.max(0,ai.stuck-dt*1.5);ai.lastX=p.x;ai.lastY=p.y;if(ai.stuck>.7){ai.strafe*=-1;ai.mode='flank';ai.goal=p.target?flankPoint(p,p.target,ai.strafe):null;ai.decision=.45;ai.stuck=0}if(ai.decision<=0||!p.target||!p.target.alive)decide(p);const d=desiredFor(p),sep=separation(p),avoid=obstacleAvoidance(p,d),v=norm(d.x+sep.x*.65+avoid.x,d.y+sep.y*.65+avoid.y),tvx=d.speed?v.x*d.speed:0,tvy=d.speed?v.y*d.speed:0,response=clamp(dt*5.2,0,1);p.vx+=(tvx-p.vx)*response;p.vy+=(tvy-p.vy)*response;const ox=p.x,oy=p.y,nx=clamp(p.x+p.vx*dt,PLAYER_R,W-PLAYER_R);if(!blocked(nx,p.y))p.x=nx;else p.vx*=.25;const ny=clamp(p.y+p.vy*dt,PLAYER_R+16,H-PLAYER_R);if(!blocked(p.x,ny))p.y=ny;else p.vy*=.25;if(blocked(p.x,p.y)){p.x=ox;p.y=oy;p.vx*=.15;p.vy*=.15}const dz=Math.hypot(p.x-CENTER.x,p.y-CENTER.y);if(dz>state.zoneR-12){const z=norm(CENTER.x-p.x,CENTER.y-p.y);p.vx+=z.x*65*dt;p.vy+=z.y*65*dt;damage(p,7*dt,null)}if(p.target&&p.target.alive){p.a=Math.atan2(p.target.y-p.y,p.target.x-p.x);const w=WS[p.weapon]||WS[0];if(dist(p,p.target)<w.range&&lineClear(p,p.target,3))shoot(p,p.target)}}
function updateBullets(dt){for(let i=state.bullets.length-1;i>=0;i--){const b=state.bullets[i];b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt;if(b.life<=0||b.x<0||b.x>W||b.y<0||b.y>H||blocked(b.x,b.y,2)){state.bullets.splice(i,1);continue}const hit=state.players.find(p=>p.alive&&p!==b.owner&&Math.hypot(p.x-b.x,p.y-b.y)<FIGHTER_HIT);if(hit){damage(hit,b.dmg,b.owner);state.bullets.splice(i,1)}}}
function burst(x,y,color,n=6){for(let i=0;i<n;i++){const a=rnd(0,Math.PI*2),s=rnd(20,105);state.fx.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:rnd(.15,.55),max:.55,color})}}function updateFx(dt){for(let i=state.fx.length-1;i>=0;i--){const f=state.fx[i];f.x+=f.vx*dt;f.y+=f.vy*dt;f.vx*=.94;f.vy*=.94;f.life-=dt;if(f.life<=0)state.fx.splice(i,1)}}
function spawnPickups(){state.pickups=[];for(const k of [0,3,4,5,3,4,0,5,3]){const s=safeSpawn();state.pickups.push({x:s.x,y:s.y,k,up:true,resp:0})}}function pickups(dt){for(const a of state.pickups){if(!a.up){a.resp-=dt;if(a.resp<=0){const s=safeSpawn();a.x=s.x;a.y=s.y;a.up=true}continue}const p=state.players.find(q=>q.alive&&Math.hypot(q.x-a.x,q.y-a.y)<23);if(!p)continue;a.up=false;a.resp=rnd(12,22);if(a.k===3)heal(p,30);else if(a.k===4){p.shot=0;p.score+=15;burst(p.x,p.y,'#ffdc46',6)}else if(a.k===0){p.shield=clamp(p.shield+25,0,80);p.score+=25;burst(p.x,p.y,'#4dcaff',8)}else{p.weapon=clamp(p.weapon+1,0,4);p.score+=35;burst(p.x,p.y,'#ff9d31',10)}}}
function update(dt){if(!state.ended&&state.players.some(p=>p.alive)){state.time+=dt;state.zoneT=Math.max(0,110-state.time);const t=clamp(state.time/110,0,1);state.zoneR=455-310*Math.pow(t,1.12);for(const p of state.players)if(p.alive)movePlayer(p,dt);updateBullets(dt);pickups(dt)}updateFx(dt)}
function sourceSprite(img,sx,sy,sw,sh,dx,dy,dw,dh,rot=0,alpha=1){if(!img||!img.complete||!img.naturalWidth)return false;ctx.save();ctx.globalAlpha=alpha;ctx.translate(dx,dy);ctx.rotate(rot);ctx.drawImage(img,sx,sy,sw,sh,-dw/2,-dh/2,dw,dh);ctx.restore();return true}function tile(index,dx,dy,dw,dh,rot=0,alpha=1){if(!source)return false;const c=source.tileCell,sx=index%4*c,sy=Math.floor(index/4)*c;return sourceSprite(source.tiles,sx,sy,c,c,dx,dy,dw,dh,rot,alpha)}
function fighterSprite(skin,dx,dy,rot,alpha=1,bob=0){if(!source)return false;const cw=source.fighterCellW,ch=source.fighterCellH,sx=skin%4*cw,sy=Math.floor(skin/4)*ch,scale=FIGHTER_W/cw,drawH=ch*scale,pivotX=source.fighterPivotX*scale,pivotY=source.fighterPivotY*scale;ctx.save();ctx.globalAlpha=alpha;ctx.translate(dx,dy+bob);ctx.rotate(rot);ctx.drawImage(source.fighters,sx,sy,cw,ch,-pivotX,-pivotY,FIGHTER_W,drawH);ctx.restore();return true}
function floor(){ctx.fillStyle='#56616b';ctx.fillRect(0,0,W,H);if(source){const cell=96;let row=0;for(let y=0;y<H;y+=cell,row++){let col=0;for(let x=0;x<W;x+=cell,col++)tile((col+row*3)%4,x+cell/2,y+cell/2,cell+1,cell+1)}ctx.fillStyle='rgba(8,11,15,.12)';ctx.fillRect(0,0,W,H);for(let i=0;i<obstacles.length;i++){const o=obstacles[i],ratio=o.w/o.h,asset=ratio>1.55?4:ratio<.75?5:i%2?6:7;ctx.save();ctx.shadowColor='rgba(0,0,0,.55)';ctx.shadowBlur=7;ctx.shadowOffsetY=4;tile(asset,o.x+o.w/2,o.y+o.h/2,o.w,o.h);ctx.restore()}}else{ctx.fillStyle='#172636';for(const o of obstacles)ctx.fillRect(o.x,o.y,o.w,o.h)}}
function drawZone(){ctx.save();ctx.fillStyle='rgba(207,18,35,.28)';ctx.beginPath();ctx.rect(0,0,W,H);ctx.arc(CENTER.x,CENTER.y,state.zoneR,0,Math.PI*2,true);ctx.fill('evenodd');ctx.strokeStyle='rgba(255,72,45,.96)';ctx.shadowColor='#ff341f';ctx.shadowBlur=14;ctx.lineWidth=4;ctx.beginPath();ctx.arc(CENTER.x,CENTER.y,state.zoneR,0,Math.PI*2);ctx.stroke();ctx.restore()}
function pickupTileIndex(k){if(k===3)return 11;if(k===4)return 12;if(k===5)return 13;return 8}function drawPickup(a){if(!a.up)return;const pulse=1+Math.sin(performance.now()/180+a.x)*.08,index=pickupTileIndex(a.k);ctx.save();ctx.shadowColor=a.k===3?'#61ff83':a.k===4?'#ffda42':a.k===5?'#ff9d31':'#44c8ff';ctx.shadowBlur=10;const ok=tile(index,a.x,a.y,30*pulse,30*pulse);ctx.restore();if(!ok){ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(a.x,a.y,6,0,Math.PI*2);ctx.fill()}}
function drawPlayer(p){const bodyRot=p.a-Math.PI/2,moving=Math.hypot(p.vx,p.vy)>10,bob=moving?Math.sin(state.time*10+p.walkPhase)*.7:0;ctx.save();ctx.translate(p.x,p.y+4);ctx.fillStyle='rgba(0,0,0,.32)';ctx.beginPath();ctx.ellipse(0,0,14,6,0,0,Math.PI*2);ctx.fill();if(p.shield>0){ctx.strokeStyle='rgba(83,198,255,.75)';ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,-2,20,0,Math.PI*2);ctx.stroke()}ctx.restore();const alpha=p.alive?1:.22,drawn=fighterSprite(p.skin,p.x,p.y,bodyRot,alpha,bob);if(!drawn){ctx.globalAlpha=alpha;ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x,p.y,13,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1}if(p.alive&&p.flash>0){const mx=p.x+Math.cos(p.a)*34,my=p.y+Math.sin(p.a)*34;ctx.save();ctx.fillStyle='#fff5b8';ctx.shadowColor='#ffb52e';ctx.shadowBlur=8;ctx.beginPath();ctx.arc(mx,my,4,0,Math.PI*2);ctx.fill();ctx.restore()}ctx.textAlign='center';ctx.font='800 9px system-ui';ctx.lineWidth=3;ctx.strokeStyle='rgba(0,0,0,.9)';ctx.strokeText(p.name,p.x,p.y-31);ctx.fillStyle=p.color;ctx.fillText(p.name,p.x,p.y-31);if(p.alive){const w=38,h=5,x=p.x-w/2,y=p.y-25;ctx.fillStyle='#0c0d0f';ctx.fillRect(x,y,w,h);ctx.fillStyle=p.hp/p.max>.35?'#64ee62':'#ff4c49';ctx.fillRect(x+1,y+1,(w-2)*clamp(p.hp/p.max,0,1),h-2)}}
function render(){floor();for(const a of state.pickups)drawPickup(a);drawZone();for(const b of state.bullets){ctx.strokeStyle=b.color;ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(b.x,b.y);ctx.lineTo(b.x-b.vx*.02,b.y-b.vy*.02);ctx.stroke()}for(const p of state.players)drawPlayer(p);for(const f of state.fx){ctx.globalAlpha=clamp(f.life/f.max,0,1);ctx.fillStyle=f.color;ctx.fillRect(f.x-1.3,f.y-1.3,2.6,2.6)}ctx.globalAlpha=1}
function syncUI(){const alive=state.players.filter(p=>p.alive);ui.alive.textContent=alive.length;const m=Math.floor(state.zoneT/60),s=Math.floor(state.zoneT%60);ui.timer.textContent=`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`;ui.queue.textContent=state.queue.length;const top=[...state.players].sort((a,b)=>(b.kills*100+b.score+b.hp)-(a.kills*100+a.score+a.hp)).slice(0,3);ui.board.innerHTML=top.map((p,i)=>`<li><span class="rank">${i+1}</span><span class="name">${p.name}</span><span class="kills">☠ ${p.kills}</span></li>`).join('');ui.feed.innerHTML=state.feed.map(x=>`<div class="kill-line">${x}</div>`).join('');ui.wait.hidden=state.players.length>0}
function finish(w){if(state.ended)return;state.ended=true;state.bullets.length=0;ui.bk.textContent='WINNER';ui.bn.textContent=w?.name||'—';ui.banner.hidden=false;setTimeout(nextRound,5200)}function nextRound(){const roster=[...state.players.map(p=>({key:p.key,name:p.name,payload:{userId:p.key,username:p.name}})),...state.queue];state.players=[];state.queue=[];state.feed=[];state.time=0;state.zoneT=110;state.zoneR=455;state.ended=false;state.round++;ui.banner.hidden=true;spawnPickups();for(const q of roster.slice(0,MAX))add(q.payload);for(const q of roster.slice(MAX))state.queue.push(q);syncUI()}
function frame(now){const dt=Math.min(.033,(now-state.last)/1000||.016);state.last=now;update(dt);render();if(now-state.lastUI>200){state.lastUI=now;syncUI()}requestAnimationFrame(frame)}
function demoSeed(){ui.mode.textContent='DEMO';ui.mode.classList.add('demo');ui.demo.hidden=false;for(let i=0;i<12;i++)add({userId:`demo:${i}`,username:names[i]});ui.demo.addEventListener('click',e=>{const b=e.target.closest('button[data-demo]');if(!b)return;const alive=state.players.filter(x=>x.alive),p=alive[(Math.random()*Math.max(1,alive.length))|0],type=b.dataset.demo;if(type==='join')add({userId:`demo:${Date.now()}`,username:names[(idSeed-1)%names.length]+idSeed});else if(type==='rose')event('gift',{userId:p?.key,username:p?.name,giftName:'Rose',diamondCount:1});else if(type==='gift')event('gift',{userId:p?.key,username:p?.name,giftName:'Power Gift',diamondCount:120});else event(type,{userId:p?.key,username:p?.name,count:25})})}
function failAssetBoot(error){console.error('[LIVE DROPZONE] v0.3.5 horizontal boot failed',error);const h2=ui.wait?.querySelector('h2'),p=ui.wait?.querySelector('p');if(h2)h2.textContent='ERRORE PREFAB';if(p)p.textContent='ricarica la pagina';render()}
function boot(a){if(started)return;started=true;source=a;spawnPickups();if(DEMO)demoSeed();syncUI();window.LiveDropzone=Object.freeze({state,add,event,finish,nextRound,assetMode:'complete-prefab-atlas-v033',format:'horizontal-16x9',version:'0.3.5'});requestAnimationFrame(frame)}
if(window.LiveDropzoneSourceReady)window.LiveDropzoneSourceReady.then(boot).catch(failAssetBoot);else failAssetBoot(new Error('asset-loader-v033.js non caricato'));
})();
