(() => {
'use strict';
const $=s=>document.querySelector(s), canvas=$('#gameCanvas'), ctx=canvas.getContext('2d',{alpha:false});
const W=540,H=800,C=12,MAX=18,DEMO=new URLSearchParams(location.search).get('demo')==='1';
const atlas=new Image(); atlas.src=window.LIVE_DROPZONE_ASSETS?.pack||''; ctx.imageSmoothingEnabled=false;
const ui={alive:$('#aliveCount'),timer:$('#zoneTimer'),board:$('#leaderboardList'),feed:$('#killFeed'),queue:$('#queueCount'),wait:$('#waitingOverlay'),banner:$('#roundBanner'),bk:$('#roundBannerKicker'),bn:$('#roundBannerName'),mode:$('#modeBadge'),demo:$('#demoPanel')};
const COLORS=['#ffb11f','#61c7ff','#f04c2b','#f4f4f4','#28455f','#78905b','#d4bb62','#c69814','#1bbc7d','#929292','#b76b56','#ff5a1e','#c6cdd1','#e9edf1','#73965e','#4f8dd8'];
const names=['NIGHTHAWK','LUNA_PLAYS','FASTFURY','PIXELPANDA','SILENTFOX','BLAZE_ON','GHOST_77','QUEENBEE','ICYBOY','DRAGONYT','ROOKIE99','NOVA','KRAKEN','VOLT','RAVEN','ASTRA'];
const obstacles=[{x:55,y:105,w:95,h:44},{x:390,y:100,w:96,h:44},{x:210,y:180,w:50,h:92},{x:305,y:245,w:108,h:45},{x:70,y:330,w:58,h:90},{x:170,y:385,w:92,h:45},{x:333,y:405,w:58,h:103},{x:430,y:520,w:62,h:62},{x:78,y:588,w:93,h:43},{x:230,y:610,w:60,h:90}];
const state={players:[],bullets:[],fx:[],pickups:[],queue:[],feed:[],round:1,time:0,zoneT:96,zoneR:355,ended:false,last:performance.now(),lastUI:0};
let idSeed=1;
function clamp(v,a,b){return Math.max(a,Math.min(b,v))} function rnd(a,b){return a+Math.random()*(b-a)} function dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}
function blocked(x,y,r=16){return obstacles.some(o=>x+r>o.x&&x-r<o.x+o.w&&y+r>o.y&&y-r<o.y+o.h)}
function safeSpawn(){for(let i=0;i<80;i++){let p={x:rnd(45,W-45),y:rnd(85,H-55)};if(!blocked(p.x,p.y,22)&&Math.hypot(p.x-W/2,p.y-H/2)<state.zoneR-28)return p}return{x:W/2,y:H/2}}
function cleanName(v){return String(v||'Viewer').replace(/^@/,'').trim().slice(0,18)||'Viewer'}
function find(payload){let key=String(payload?.userId||payload?.uniqueId||payload?.username||'').toLowerCase();return state.players.find(p=>p.key===key||p.name.toLowerCase()===key)}
function add(payload={}){let existing=find(payload);if(existing)return existing;let name=cleanName(payload.username||payload.uniqueId),key=String(payload.userId||payload.uniqueId||name).toLowerCase();if(state.ended||state.players.filter(p=>p.alive).length>=MAX||state.zoneT<18){if(!state.queue.some(q=>q.key===key))state.queue.push({key,name,payload});syncUI();return null}let s=safeSpawn(),skin=(idSeed-1)%16,p={id:idSeed++,key,name,x:s.x,y:s.y,vx:0,vy:0,a:rnd(0,Math.PI*2),hp:100,max:100,shield:0,level:1,weapon:0,kills:0,alive:true,shot:rnd(.2,.8),think:0,target:null,skin,color:COLORS[skin],flash:0,followed:false,score:0};state.players.push(p);ui.wait.hidden=true;burst(p.x,p.y,p.color,12);syncUI();return p}
function heal(p,n){if(!p||!p.alive)return;p.hp=clamp(p.hp+n,0,p.max);burst(p.x,p.y,'#5aff8b',5)}
function upgrade(p,n=1){if(!p||!p.alive)return;p.level=clamp(p.level+n,1,12);p.max=100+(p.level-1)*8;p.hp=clamp(p.hp+18,0,p.max);p.weapon=clamp(Math.floor((p.level-1)/2),0,4);p.shield=clamp(p.shield+12,0,65);burst(p.x,p.y,'#ffd34f',10)}
function gift(p,d=1,name='gift'){if(!p||!p.alive)return;if(/rose|rosa/i.test(name)){upgrade(p,1);return}if(d>=100){airstrike(p);upgrade(p,2)}else if(d>=20){p.weapon=clamp(p.weapon+1,0,4);p.shield=clamp(p.shield+30,0,80);burst(p.x,p.y,'#c979ff',14)}else{heal(p,20+d*.4);p.shield=clamp(p.shield+10,0,60)}}
function airstrike(owner){for(let i=0;i<3;i++)setTimeout(()=>{let enemies=state.players.filter(p=>p.alive&&p!==owner);if(!enemies.length)return;let t=enemies[(Math.random()*enemies.length)|0];burst(t.x,t.y,'#ff713d',24);damage(t,34,owner)},i*180)}
function event(type,payload={}){let p=find(payload);if(type==='join')add(payload);else if(type==='like'){p=p||add(payload);heal(p,Math.min(24,2+Math.sqrt(Math.max(1,+payload.count||1))*2.2))}else if(type==='follow'){p=p||add(payload);if(p&&!p.followed){p.followed=true;p.weapon=clamp(p.weapon+1,0,4);p.shield=clamp(p.shield+28,0,70);burst(p.x,p.y,'#6cf26e',12)}}else if(type==='gift'){p=p||add(payload);gift(p,Math.max(1,+payload.diamondCount||1)*Math.max(1,+payload.repeatCount||1),payload.giftName)}}
window.addEventListener('live-dropzone:event',e=>event(e.detail?.type,e.detail?.payload));
const WS=[{speed:440,rate:.74,dmg:16,spread:.045,count:1},{speed:470,rate:.55,dmg:14,spread:.07,count:1},{speed:420,rate:.92,dmg:9,spread:.22,count:4},{speed:520,rate:.34,dmg:11,spread:.09,count:1},{speed:570,rate:.22,dmg:10,spread:.12,count:1}];
function shoot(p,t){let w=WS[p.weapon]||WS[0];if(p.shot>0||!t)return;p.shot=w.rate*(.94+Math.random()*.18);p.a=Math.atan2(t.y-p.y,t.x-p.x);for(let i=0;i<w.count;i++){let a=p.a+(Math.random()-.5)*w.spread;state.bullets.push({x:p.x+Math.cos(a)*19,y:p.y+Math.sin(a)*19,vx:Math.cos(a)*w.speed,vy:Math.sin(a)*w.speed,life:1.25,owner:p,dmg:w.dmg*(1+(p.level-1)*.025),color:p.color})}p.flash=.06}
function damage(p,n,owner){if(!p||!p.alive)return;let sh=Math.min(p.shield,n);p.shield-=sh;n-=sh;p.hp-=n;burst(p.x,p.y,n>20?'#ff725b':'#ffffff',4);if(p.hp<=0){p.alive=false;p.hp=0;p.vx=p.vy=0;if(owner&&owner!==p){owner.kills++;owner.score+=100}state.feed.unshift(`${owner?.name||'ZONA'} ✕ ${p.name}`);state.feed=state.feed.slice(0,5);burst(p.x,p.y,'#ff4a43',18);let alive=state.players.filter(x=>x.alive);if(alive.length===1&&state.players.length>1)finish(alive[0])}}
function nearest(p){let best=null,bd=1e9;for(let q of state.players){if(!q.alive||q===p)continue;let d=(p.x-q.x)**2+(p.y-q.y)**2;if(d<bd){bd=d;best=q}}return best}
function movePlayer(p,dt){p.shot=Math.max(0,p.shot-dt);p.flash=Math.max(0,p.flash-dt);p.think-=dt;if(p.think<=0){p.think=rnd(.18,.5);p.target=nearest(p);if(p.target){let a=Math.atan2(p.target.y-p.y,p.target.x-p.x),d=dist(p,p.target),strafe=(Math.random()-.5)*1.8;let ideal=p.weapon===2?105:150,dir=d>ideal+35?1:d<ideal-35?-1:.15;p.vx=(Math.cos(a)*dir+Math.cos(a+Math.PI/2)*strafe*.45)*rnd(45,72);p.vy=(Math.sin(a)*dir+Math.sin(a+Math.PI/2)*strafe*.45)*rnd(45,72);p.a=a}}let ox=p.x,oy=p.y;p.x=clamp(p.x+p.vx*dt,18,W-18);p.y=clamp(p.y+p.vy*dt,54,H-18);if(blocked(p.x,p.y,15)){p.x=ox;p.y=oy;p.vx*=-.7;p.vy*=-.7}let cx=p.x-W/2,cy=p.y-H/2,dz=Math.hypot(cx,cy);if(dz>state.zoneR-16){let a=Math.atan2(cy,cx);p.x-=Math.cos(a)*85*dt;p.y-=Math.sin(a)*85*dt;damage(p,8*dt,null)}if(p.target&&p.target.alive&&dist(p,p.target)<310)shoot(p,p.target)}
function bulletHitWall(b){return blocked(b.x,b.y,2)}
function updateBullets(dt){for(let i=state.bullets.length-1;i>=0;i--){let b=state.bullets[i];b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt;if(b.life<=0||b.x<0||b.x>W||b.y<0||b.y>H||bulletHitWall(b)){state.bullets.splice(i,1);continue}let hit=state.players.find(p=>p.alive&&p!==b.owner&&Math.hypot(p.x-b.x,p.y-b.y)<15);if(hit){damage(hit,b.dmg,b.owner);state.bullets.splice(i,1)}}}
function burst(x,y,color,n=6){for(let i=0;i<n;i++){let a=rnd(0,Math.PI*2),s=rnd(20,105);state.fx.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:rnd(.15,.55),max:.55,color})}}
function updateFx(dt){for(let i=state.fx.length-1;i>=0;i--){let f=state.fx[i];f.x+=f.vx*dt;f.y+=f.vy*dt;f.vx*=.94;f.vy*=.94;f.life-=dt;if(f.life<=0)state.fx.splice(i,1)}}
function spawnPickups(){state.pickups=[];let kinds=[0,3,4,5,3,4,0];for(let k of kinds){let s=safeSpawn();state.pickups.push({x:s.x,y:s.y,k,up:true,resp:0})}}
function pickups(dt){for(let a of state.pickups){if(!a.up){a.resp-=dt;if(a.resp<=0){let s=safeSpawn();a.x=s.x;a.y=s.y;a.up=true}continue}let p=state.players.find(q=>q.alive&&Math.hypot(q.x-a.x,q.y-a.y)<25);if(!p)continue;a.up=false;a.resp=rnd(12,22);if(a.k===3)heal(p,30);else if(a.k===4){p.shot=0;p.score+=15;burst(p.x,p.y,'#ffdc46',6)}else if(a.k===0){p.shield=clamp(p.shield+25,0,80);p.score+=25;burst(p.x,p.y,'#4dcaff',8)}else{p.weapon=clamp(p.weapon+1,0,4);p.score+=35;burst(p.x,p.y,'#ff9d31',10)}}}
function update(dt){if(!state.ended&&state.players.some(p=>p.alive)){state.time+=dt;state.zoneT=Math.max(0,96-state.time);let t=clamp(state.time/96,0,1);state.zoneR=355-(230*Math.pow(t,1.15));for(let p of state.players)if(p.alive)movePlayer(p,dt);updateBullets(dt);pickups(dt)}updateFx(dt)}
function sprite(sx,sy,dx,dy,dw,dh,rot=0){if(!atlas.complete||!atlas.naturalWidth)return false;ctx.save();ctx.translate(dx,dy);ctx.rotate(rot);ctx.drawImage(atlas,sx,sy,C,C,-dw/2,-dh/2,dw,dh);ctx.restore();return true}
function floor(){ctx.fillStyle='#2a3038';ctx.fillRect(0,0,W,H);ctx.strokeStyle='rgba(255,255,255,.035)';ctx.lineWidth=1;for(let x=0;x<W;x+=34){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke()}for(let y=0;y<H;y+=34){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}for(let o of obstacles){ctx.fillStyle='#172636';ctx.fillRect(o.x,o.y,o.w,o.h);ctx.strokeStyle='#d69d22';ctx.lineWidth=2;ctx.strokeRect(o.x+.5,o.y+.5,o.w-1,o.h-1);ctx.fillStyle='rgba(255,255,255,.04)';ctx.fillRect(o.x+5,o.y+5,o.w-10,7)}}
function drawZone(){ctx.save();ctx.fillStyle='rgba(207,18,35,.30)';ctx.beginPath();ctx.rect(0,0,W,H);ctx.arc(W/2,H/2,state.zoneR,0,Math.PI*2,true);ctx.fill('evenodd');ctx.strokeStyle='rgba(255,72,45,.96)';ctx.shadowColor='#ff341f';ctx.shadowBlur=16;ctx.lineWidth=4;ctx.beginPath();ctx.arc(W/2,H/2,state.zoneR,0,Math.PI*2);ctx.stroke();ctx.restore()}
function drawPickup(a){if(!a.up)return;let pulse=1+Math.sin(performance.now()/180+a.x)*.08;ctx.save();ctx.shadowColor=a.k===3?'#61ff83':a.k===4?'#ffda42':'#44c8ff';ctx.shadowBlur=10;sprite(a.k*C,5*C,a.x,a.y,25*pulse,25*pulse,0);ctx.restore()}
function drawPlayer(p){if(!p.alive){ctx.globalAlpha=.18;sprite((p.skin%4)*C,Math.floor(p.skin/4)*C,p.x,p.y,34,34,p.a);ctx.globalAlpha=1;return}ctx.save();ctx.translate(p.x,p.y);ctx.fillStyle='rgba(0,0,0,.35)';ctx.beginPath();ctx.ellipse(0,8,17,9,0,0,Math.PI*2);ctx.fill();if(p.shield>0){ctx.strokeStyle='rgba(83,198,255,.68)';ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,0,21,0,Math.PI*2);ctx.stroke()}ctx.restore();sprite((p.skin%4)*C,Math.floor(p.skin/4)*C,p.x,p.y,37,37,p.a);sprite(p.weapon*C,4*C,p.x+Math.cos(p.a)*10,p.y+Math.sin(p.a)*10,31,15,p.a);if(p.flash>0){ctx.fillStyle='#fff5b8';ctx.beginPath();ctx.arc(p.x+Math.cos(p.a)*26,p.y+Math.sin(p.a)*26,4,0,Math.PI*2);ctx.fill()}ctx.textAlign='center';ctx.font='700 10px system-ui';ctx.lineWidth=3;ctx.strokeStyle='rgba(0,0,0,.9)';ctx.strokeText(p.name,p.x,p.y-27);ctx.fillStyle=p.color;ctx.fillText(p.name,p.x,p.y-27);let w=42,h=5,x=p.x-w/2,y=p.y-20;ctx.fillStyle='#111';ctx.fillRect(x,y,w,h);ctx.fillStyle=p.hp/p.max>.35?'#64ee62':'#ff4c49';ctx.fillRect(x+1,y+1,(w-2)*clamp(p.hp/p.max,0,1),h-2)}
function render(){floor();for(let a of state.pickups)drawPickup(a);drawZone();for(let b of state.bullets){ctx.strokeStyle=b.color;ctx.lineWidth=2.2;ctx.beginPath();ctx.moveTo(b.x,b.y);ctx.lineTo(b.x-b.vx*.025,b.y-b.vy*.025);ctx.stroke()}for(let p of state.players)drawPlayer(p);for(let f of state.fx){ctx.globalAlpha=clamp(f.life/f.max,0,1);ctx.fillStyle=f.color;ctx.fillRect(f.x-1.5,f.y-1.5,3,3)}ctx.globalAlpha=1}
function syncUI(){let alive=state.players.filter(p=>p.alive);ui.alive.textContent=alive.length;let m=Math.floor(state.zoneT/60),s=Math.floor(state.zoneT%60);ui.timer.textContent=`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`;ui.queue.textContent=state.queue.length;let top=[...state.players].sort((a,b)=>(b.kills*100+b.score+b.hp)-(a.kills*100+a.score+a.hp)).slice(0,3);ui.board.innerHTML=top.map((p,i)=>`<li><span class="rank">${i+1}</span><span class="name">${p.name}</span><span class="kills">☠ ${p.kills}</span></li>`).join('');ui.feed.innerHTML=state.feed.map(x=>`<div class="kill-line">${x}</div>`).join('');ui.wait.hidden=state.players.length>0}
function finish(w){if(state.ended)return;state.ended=true;state.bullets.length=0;ui.bk.textContent='WINNER';ui.bn.textContent=w?.name||'—';ui.banner.hidden=false;setTimeout(nextRound,5200)}
function nextRound(){let roster=[...state.players.map(p=>({key:p.key,name:p.name,payload:{userId:p.key,username:p.name}})),...state.queue];state.players=[];state.queue=[];state.feed=[];state.time=0;state.zoneT=96;state.zoneR=355;state.ended=false;state.round++;ui.banner.hidden=true;spawnPickups();for(let q of roster.slice(0,MAX))add(q.payload);for(let q of roster.slice(MAX))state.queue.push(q);syncUI()}
function frame(now){let dt=Math.min(.033,(now-state.last)/1000||.016);state.last=now;update(dt);render();if(now-state.lastUI>200){state.lastUI=now;syncUI()}requestAnimationFrame(frame)}
function demoSeed(){ui.mode.textContent='DEMO';ui.mode.classList.add('demo');ui.demo.hidden=false;for(let i=0;i<12;i++)add({userId:`demo:${i}`,username:names[i]});ui.demo.addEventListener('click',e=>{let t=e.target.closest('button[data-demo]');if(!t)return;let p=state.players.filter(x=>x.alive)[(Math.random()*Math.max(1,state.players.filter(x=>x.alive).length))|0];let type=t.dataset.demo;if(type==='join')add({userId:`demo:${Date.now()}`,username:names[(idSeed-1)%names.length]+idSeed});else if(type==='rose')event('gift',{userId:p?.key,username:p?.name,giftName:'Rose',diamondCount:1});else if(type==='gift')event('gift',{userId:p?.key,username:p?.name,giftName:'Power Gift',diamondCount:120});else event(type,{userId:p?.key,username:p?.name,count:25})})}
spawnPickups();if(DEMO)demoSeed();syncUI();window.LiveDropzone=Object.freeze({state,add,event,finish,nextRound});requestAnimationFrame(frame);
})();
