(() => {
'use strict';
const LD=window.LD036;if(!LD||!LD.movePlayer)throw new Error('LD036 AI missing');const {ctx,state,ui}=LD;
LD.updateFx=dt=>{for(let i=state.fx.length-1;i>=0;i--){const f=state.fx[i];f.x+=f.vx*dt;f.y+=f.vy*dt;f.vx*=.94;f.vy*=.94;f.life-=dt;if(f.life<=0)state.fx.splice(i,1)}};
LD.spawnPickups=()=>{state.pickups=[];for(const k of[0,3,4,5,3,4,0,5,3]){const s=LD.safeSpawn();state.pickups.push({x:s.x,y:s.y,k,up:true,resp:0})}};
LD.pickups=dt=>{for(const a of state.pickups){if(!a.up){a.resp-=dt;if(a.resp<=0){const s=LD.safeSpawn();a.x=s.x;a.y=s.y;a.up=true}continue}const p=state.players.find(q=>q.alive&&Math.hypot(q.x-a.x,q.y-a.y)<23);if(!p)continue;a.up=false;a.resp=LD.rnd(12,22);if(a.k===3)LD.heal(p,30);else if(a.k===4){p.shot=0;p.score+=15;LD.burst(p.x,p.y,'#ffdc46',6)}else if(a.k===0){p.shield=LD.clamp(p.shield+25,0,80);p.score+=25;LD.burst(p.x,p.y,'#4dcaff',8)}else{p.weapon=LD.clamp(p.weapon+1,0,4);p.score+=35;LD.burst(p.x,p.y,'#ff9d31',10)}}};
function sourceSprite(img,sx,sy,sw,sh,dx,dy,dw,dh,rot=0,alpha=1){if(!img||!img.complete||!img.naturalWidth)return false;ctx.save();ctx.globalAlpha=alpha;ctx.translate(dx,dy);ctx.rotate(rot);ctx.drawImage(img,sx,sy,sw,sh,-dw/2,-dh/2,dw,dh);ctx.restore();return true}
function tile(index,dx,dy,dw,dh,rot=0,alpha=1){if(!LD.source)return false;const c=LD.source.tileCell,sx=index%4*c,sy=Math.floor(index/4)*c;return sourceSprite(LD.source.tiles,sx,sy,c,c,dx,dy,dw,dh,rot,alpha)}
function fighterSprite(skin,dx,dy,rot,alpha=1,bob=0){if(!LD.source)return false;const cw=LD.source.fighterCellW,ch=LD.source.fighterCellH,sx=skin%4*cw,sy=Math.floor(skin/4)*ch,scale=LD.FIGHTER_W/cw,drawH=ch*scale,pivotX=LD.source.fighterPivotX*scale,pivotY=LD.source.fighterPivotY*scale;ctx.save();ctx.globalAlpha=alpha;ctx.translate(dx,dy+bob);ctx.rotate(rot);ctx.drawImage(LD.source.fighters,sx,sy,cw,ch,-pivotX,-pivotY,LD.FIGHTER_W,drawH);ctx.restore();return true}
function floor(){ctx.fillStyle='#56616b';ctx.fillRect(0,0,LD.W,LD.H);if(LD.source){const cell=96;let row=0;for(let y=0;y<LD.H;y+=cell,row++){let col=0;for(let x=0;x<LD.W;x+=cell,col++)tile((col+row*3)%4,x+cell/2,y+cell/2,cell+1,cell+1)}ctx.fillStyle='rgba(8,11,15,.12)';ctx.fillRect(0,0,LD.W,LD.H);for(let i=0;i<LD.obstacles.length;i++){const o=LD.obstacles[i],ratio=o.w/o.h,asset=ratio>1.55?4:ratio<.75?5:i%2?6:7;ctx.save();ctx.shadowColor='rgba(0,0,0,.55)';ctx.shadowBlur=7;ctx.shadowOffsetY=4;tile(asset,o.x+o.w/2,o.y+o.h/2,o.w,o.h);ctx.restore()}}else{ctx.fillStyle='#172636';for(const o of LD.obstacles)ctx.fillRect(o.x,o.y,o.w,o.h)}}
function drawZone(){ctx.save();ctx.fillStyle='rgba(207,18,35,.28)';ctx.beginPath();ctx.rect(0,0,LD.W,LD.H);ctx.arc(LD.CENTER.x,LD.CENTER.y,state.zoneR,0,Math.PI*2,true);ctx.fill('evenodd');ctx.strokeStyle='rgba(255,72,45,.96)';ctx.shadowColor='#ff341f';ctx.shadowBlur=14;ctx.lineWidth=4;ctx.beginPath();ctx.arc(LD.CENTER.x,LD.CENTER.y,state.zoneR,0,Math.PI*2);ctx.stroke();ctx.restore()}
const pickupIndex=k=>k===3?11:k===4?12:k===5?13:8;
function drawPickup(a){if(!a.up)return;const pulse=1+Math.sin(performance.now()/180+a.x)*.08;ctx.save();ctx.shadowColor=a.k===3?'#61ff83':a.k===4?'#ffda42':a.k===5?'#ff9d31':'#44c8ff';ctx.shadowBlur=10;const ok=tile(pickupIndex(a.k),a.x,a.y,30*pulse,30*pulse);ctx.restore();if(!ok){ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(a.x,a.y,6,0,Math.PI*2);ctx.fill()}}
function drawPlayer(p){const rot=p.a-Math.PI/2,moving=Math.hypot(p.vx,p.vy)>10,bob=moving?Math.sin(state.time*10+p.walkPhase)*.7:0;ctx.save();ctx.translate(p.x,p.y+4);ctx.fillStyle='rgba(0,0,0,.32)';ctx.beginPath();ctx.ellipse(0,0,14,6,0,0,Math.PI*2);ctx.fill();if(p.shield>0){ctx.strokeStyle='rgba(83,198,255,.75)';ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,-2,20,0,Math.PI*2);ctx.stroke()}ctx.restore();const alpha=p.alive?1:.22,drawn=fighterSprite(p.skin,p.x,p.y,rot,alpha,bob);if(!drawn){ctx.globalAlpha=alpha;ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x,p.y,13,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1}if(p.alive&&p.flash>0){const mx=p.x+Math.cos(p.a)*28,my=p.y+Math.sin(p.a)*28;ctx.save();ctx.fillStyle='#fff5b8';ctx.shadowColor='#ffb52e';ctx.shadowBlur=8;ctx.beginPath();ctx.arc(mx,my,4,0,Math.PI*2);ctx.fill();ctx.restore()}ctx.textAlign='center';ctx.font='800 9px system-ui';ctx.lineWidth=3;ctx.strokeStyle='rgba(0,0,0,.9)';ctx.strokeText(p.name,p.x,p.y-31);ctx.fillStyle=p.color;ctx.fillText(p.name,p.x,p.y-31);if(p.alive){const w=38,h=5,x=p.x-w/2,y=p.y-25;ctx.fillStyle='#0c0d0f';ctx.fillRect(x,y,w,h);ctx.fillStyle=p.hp/p.max>.35?'#64ee62':'#ff4c49';ctx.fillRect(x+1,y+1,(w-2)*LD.clamp(p.hp/p.max,0,1),h-2)}}
function render(){floor();for(const a of state.pickups)drawPickup(a);drawZone();for(const b of state.bullets){ctx.strokeStyle=b.color;ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(b.x,b.y);ctx.lineTo(b.x-b.vx*.02,b.y-b.vy*.02);ctx.stroke()}for(const p of state.players)drawPlayer(p);for(const f of state.fx){ctx.globalAlpha=LD.clamp(f.life/f.max,0,1);ctx.fillStyle=f.color;ctx.fillRect(f.x-1.3,f.y-1.3,2.6,2.6)}ctx.globalAlpha=1}
LD.syncUI=()=>{const alive=state.players.filter(p=>p.alive);ui.alive.textContent=alive.length;const m=Math.floor(state.zoneT/60),s=Math.floor(state.zoneT%60);ui.timer.textContent=`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`;ui.queue.textContent=state.queue.length;const top=[...state.players].sort((a,b)=>(b.kills*100+b.score+b.hp)-(a.kills*100+a.score+a.hp)).slice(0,3);ui.board.innerHTML=top.map((p,i)=>`<li><span class="rank">${i+1}</span><span class="name">${p.name}</span><span class="kills">☠ ${p.kills}</span></li>`).join('');ui.feed.innerHTML=state.feed.map(x=>`<div class="kill-line">${x}</div>`).join('');ui.wait.hidden=state.players.length>0};
LD.finish=w=>{if(state.ended)return;state.ended=true;state.bullets.length=0;ui.bk.textContent='WINNER';ui.bn.textContent=w?.name||'—';ui.banner.hidden=false;setTimeout(LD.nextRound,5200)};
LD.nextRound=()=>{const roster=[...state.players.map(p=>({key:p.key,name:p.name,payload:{userId:p.key,username:p.name}})),...state.queue];state.players=[];state.queue=[];state.feed=[];state.time=0;state.zoneT=110;state.zoneR=455;state.ended=false;state.round++;ui.banner.hidden=true;LD.spawnPickups();for(const q of roster.slice(0,LD.MAX))LD.add(q.payload);for(const q of roster.slice(LD.MAX))state.queue.push(q);LD.syncUI()};
function update(dt){if(!state.ended&&state.players.some(p=>p.alive)){state.time+=dt;state.zoneT=Math.max(0,110-state.time);const t=LD.clamp(state.time/110,0,1);state.zoneR=455-310*Math.pow(t,1.12);for(const p of state.players)if(p.alive)LD.movePlayer(p,dt);LD.updateBullets(dt);LD.pickups(dt)}LD.updateFx(dt)}
function frame(now){const dt=Math.min(.033,(now-state.last)/1000||.016);state.last=now;update(dt);render();if(now-state.lastUI>200){state.lastUI=now;LD.syncUI()}requestAnimationFrame(frame)}
function demoSeed(){ui.mode.textContent='DEMO';ui.mode.classList.add('demo');ui.demo.hidden=false;for(let i=0;i<12;i++)LD.add({userId:`demo:${i}`,username:LD.names[i]});ui.demo.addEventListener('click',e=>{const b=e.target.closest('button[data-demo]');if(!b)return;const alive=state.players.filter(x=>x.alive),p=alive[(Math.random()*Math.max(1,alive.length))|0],type=b.dataset.demo;if(type==='join')LD.add({userId:`demo:${Date.now()}`,username:LD.names[(LD.idSeed-1)%LD.names.length]+LD.idSeed});else if(type==='rose')LD.event('gift',{userId:p?.key,username:p?.name,giftName:'Rose',diamondCount:1});else if(type==='gift')LD.event('gift',{userId:p?.key,username:p?.name,giftName:'Power Gift',diamondCount:120});else LD.event(type,{userId:p?.key,username:p?.name,count:25})})}
function fail(error){console.error('[LIVE DROPZONE] v0.3.6 waypoint/LOS boot failed',error);const h=ui.wait?.querySelector('h2'),p=ui.wait?.querySelector('p');if(h)h.textContent='ERRORE PREFAB';if(p)p.textContent='ricarica la pagina';render()}
function boot(a){if(LD.started)return;LD.started=true;LD.source=a;LD.spawnPickups();if(LD.DEMO)demoSeed();LD.syncUI();window.LiveDropzone=Object.freeze({state,add:LD.add,event:LD.event,finish:LD.finish,nextRound:LD.nextRound,assetMode:'complete-prefab-atlas-v033',format:'horizontal-16x9',version:'0.3.6'});requestAnimationFrame(frame)}
if(window.LiveDropzoneSourceReady)window.LiveDropzoneSourceReady.then(boot).catch(fail);else fail(new Error('asset-loader-v033.js non caricato'));
})();
