import {Simulation,fmt,clamp} from './sim.js';
import {WorldMap} from './map.js';
const $=s=>document.querySelector(s);const sim=new Simulation();const map=new WorldMap($('#worldMap'),sim);let selected=null,autoTimer=null,autoJoinTimers=[],autoInteractions=0,uiTick=0;
const els={loading:$('#loading'),nationName:$('#nationName'),nationStatus:$('#nationStatus'),ownerLine:$('#ownerLine'),viewers:$('#viewersVal'),power:$('#powerVal'),fuel:$('#fuelVal'),army:$('#armyVal'),supply:$('#supplyVal'),mob:$('#mobVal'),ready:$('#readyVal'),fuelBar:$('#fuelBar'),armyBar:$('#armyBar'),supplyBar:$('#supplyBar'),mobBar:$('#mobBar'),readyBar:$('#readyBar'),rank:$('#ranking'),campaigns:$('#campaigns'),campaignCount:$('#campaignCount'),active:$('#activeLabel'),war:$('#warLabel'),ticker:$('#tickerText'),joinCard:$('#joinCard'),joinNation:$('#joinNation'),joinViewer:$('#joinViewer'),testStatus:$('#testStatus'),testInfo:$('#testInfo'),victory:$('#victory'),winnerName:$('#winnerName'),winnerStats:$('#winnerStats')};
function setTicker(t){els.ticker.textContent=t}
function showSelected(n){selected=n;if(!n){els.nationName.textContent='Select a nation';return}els.nationName.textContent=n.name;els.nationStatus.textContent=n.alive?(n.viewers.size?'SUPPORTED':'DORMANT'):'FALLEN';els.nationStatus.style.color=n.viewers.size?n.color:'';els.ownerLine.textContent=n.viewers.size?`${n.viewers.size} supporter${n.viewers.size===1?'':'s'} · ${n.territories.size} territor${n.territories.size===1?'y':'ies'}`:'No LIVE supporters · defensive only';els.viewers.textContent=n.viewers.size;els.power.textContent=fmt(sim.livePower(n));els.fuel.textContent=Math.round(n.fuel);els.army.textContent=fmt(n.army);els.supply.textContent=Math.round(n.supply);els.mob.textContent=Math.round(n.mobilization)+'%';els.ready.textContent=Math.round(n.readiness)+'%';els.fuelBar.style.width=clamp(n.fuel/2.5,0,100)+'%';els.armyBar.style.width=clamp(n.army/5,0,100)+'%';els.supplyBar.style.width=clamp(n.supply/2.5,0,100)+'%';els.mobBar.style.width=n.mobilization+'%';els.readyBar.style.width=n.readiness+'%'}
function renderRanking(){const list=[...sim.nations.values()].filter(n=>n.alive&&n.viewers.size).sort((a,b)=>sim.livePower(b)-sim.livePower(a)).slice(0,5);els.rank.innerHTML=list.length?list.map((n,i)=>`<div class="rankRow"><i class="swatch" style="background:${n.color}"></i><div><b>${i+1}. ${n.name}</b><small>${n.viewers.size} viewers · ${n.territories.size} territories</small></div><strong>${fmt(sim.livePower(n))}</strong></div>`).join(''):'<div class="empty">No supported nations yet.</div>';els.active.textContent=`${list.length} ACTIVE`}
function renderCampaigns(){els.campaignCount.textContent=sim.campaigns.length;els.war.textContent=`${sim.campaigns.length} WARS`;els.campaigns.innerHTML=sim.campaigns.length?sim.campaigns.map(c=>`<div class="campaignRow"><div><b>${c.attacker} → ${c.defender}</b><small>${c.phase} · ${Math.max(0,Math.round(c.progress))}%</small><div class="campaignProgress"><i style="width:${Math.max(0,c.progress)}%"></i></div></div><strong>${Math.round(c.progress)}%</strong></div>`).join(''):'<div class="empty">No active campaigns.</div>'}
function refresh(){map.update();if(selected)showSelected(selected);renderRanking();renderCampaigns()}
function join(viewer,nationName){if(!sim.join(viewer,nationName)){setTicker(`Could not join ${nationName}. Check the country name.`);return false}return true}
function currentViewer(){return $('#viewerInput').value.trim()||'TestViewer'}
function currentNation(){return $('#nationInput').value.trim()||'Italy'}
function support(type,value=1){const v=currentViewer();if(!sim.viewers.has(v))join(v,currentNation());sim.event(v,type,value);refresh()}
function stopAuto(){clearInterval(autoTimer);autoTimer=null;autoJoinTimers.forEach(clearTimeout);autoJoinTimers=[];$('#autoTestBtn').textContent='▶ AUTO TEST · 10 VIEWERS';$('#autoTestBtn').classList.remove('autoRunning');els.testStatus.textContent='IDLE';els.testInfo.textContent=`Stopped · ${autoInteractions} interactions generated`}
function startAuto(){if(autoTimer)return stopAuto();sim.speed=4;document.querySelectorAll('.speed').forEach(b=>b.classList.toggle('active',b.dataset.speed==='4'));const roster=[['Atlas_01','Italy'],['Luna_ITA','Italy'],['RomaKing','Italy'],['Azzurro','Italy'],['ParisLive','France'],['HexaFR','France'],['BleuWave','France'],['BerlinBoss','Germany'],['RhineWolf','Germany'],['NovaDE','Germany']];autoInteractions=0;els.testStatus.textContent='RUNNING';$('#autoTestBtn').textContent='■ STOP AUTO TEST';$('#autoTestBtn').classList.add('autoRunning');roster.forEach(([v,n],i)=>autoJoinTimers.push(setTimeout(()=>{join(v,n);els.testInfo.textContent=`${i+1}/10 viewers joined · ${autoInteractions} interactions`},i*900)));autoTimer=setInterval(()=>{const [v]=roster[Math.floor(Math.random()*roster.length)];if(!sim.viewers.has(v))return;const r=Math.random();if(r<.68)sim.event(v,'like',5+Math.floor(Math.random()*35));else if(r<.78)sim.event(v,'share');else if(r<.86)sim.event(v,'rose');else if(r<.93)sim.event(v,'follow');else sim.event(v,'gift',[100,500,1000,2000][Math.floor(Math.random()*4)]);autoInteractions++;els.testInfo.textContent=`10 viewers · ${autoInteractions} interactions`;refresh()},520)}
async function boot(){try{const data=await map.load();sim.init(data.features,data.neighbors);els.loading.classList.add('hidden');setTicker('World ready. JOIN a nation to activate it.');const italy=sim.nation('Italy');if(italy){selected=italy;map.select(italy.home);showSelected(italy)}requestAnimationFrame(loop)}catch(e){els.loading.innerHTML=`<b>Map could not load</b><span>${String(e.message||e)}</span>`}}
let last=performance.now();function loop(t){const dt=Math.min(.1,(t-last)/1000);last=t;sim.tick(dt);if(++uiTick%6===0)refresh();requestAnimationFrame(loop)}
sim.on(e=>{if(e.type==='join'){selected=e.nation;showSelected(selected);els.joinNation.textContent=e.nation.name.toUpperCase();els.joinViewer.textContent=`@${e.viewer} joined`;els.joinCard.classList.remove('hidden');map.focusJoin(e.nation,e.viewer);setTimeout(()=>els.joinCard.classList.add('hidden'),2400)}if(e.type==='select'){selected=e.nation;showSelected(selected)}if(e.type==='feed')setTicker(e.text);if(e.type==='capture'||e.type==='warstart'||e.type==='warend')refresh();if(e.type==='victory'){stopAuto();els.winnerName.textContent=`${e.winner.name.toUpperCase()} WINS`;els.winnerStats.textContent=`${e.winner.territories.size} territories · Army ${fmt(e.winner.army)} · Live Power ${fmt(sim.livePower(e.winner))}`;els.victory.classList.remove('hidden');setTicker(`${e.winner.name} has conquered the world.`)}});
$('#joinBtn').addEventListener('click',()=>join(currentViewer(),currentNation()));document.querySelectorAll('[data-event]').forEach(b=>b.addEventListener('click',()=>support(b.dataset.event)));document.querySelectorAll('[data-gift]').forEach(b=>b.addEventListener('click',()=>support('gift',+b.dataset.gift)));$('#autoTestBtn').addEventListener('click',startAuto);document.querySelectorAll('.speed').forEach(b=>b.addEventListener('click',()=>{sim.speed=+b.dataset.speed;document.querySelectorAll('.speed').forEach(x=>x.classList.toggle('active',x===b))}));$('#pauseBtn').addEventListener('click',()=>{sim.paused=!sim.paused;$('#app').classList.toggle('paused',sim.paused);$('#pauseBtn').textContent=sim.paused?'▶':'II'});$('#restartBtn').addEventListener('click',()=>{els.victory.classList.add('hidden');sim.resetOwnership();selected=sim.nation('Italy');map.select(selected.home);showSelected(selected);refresh();setTicker('New world started. Waiting for LIVE supporters.')});
window.WorldConflict={receiveTikTokEvent(ev){const type=(ev.type||ev.event||'').toLowerCase(),viewer=ev.username||ev.user||ev.uniqueId||'Viewer';if(type==='join'||type==='comment'){const text=ev.comment||ev.text||'';const m=text.match(/^\s*join\s+(.+)/i);if(m)return join(viewer,m[1])}if(type==='like'){if(!sim.viewers.has(viewer))return false;return sim.event(viewer,'like',ev.count||ev.likeCount||1)}if(type==='follow'||type==='share'||type==='rose')return sim.event(viewer,type,1);if(type==='gift')return sim.event(viewer,'gift',ev.coins||ev.diamondCount||ev.value||1);return false},sim};
boot();
