const D3='https://cdn.jsdelivr.net/npm/d3@7.9.0/+esm';
const TOPO='https://cdn.jsdelivr.net/npm/topojson-client@3.1.0/+esm';
const WORLD='https://cdn.jsdelivr.net/npm/world-atlas@2.0.2/countries-50m.json/+esm';
export class WorldMap{
  constructor(svg,sim){this.svg=svg;this.sim=sim;this.viewport=svg.querySelector('#viewport');this.countriesG=svg.querySelector('#countries');this.warG=svg.querySelector('#warLayer');this.labelsG=svg.querySelector('#labelLayer');this.paths=[];this.homeTransform='';this.selected=null;this.flashTimer=null}
  async load(){const [d3,topo,{default:world}]=await Promise.all([import(D3),import(TOPO),import(WORLD)]);this.d3=d3;this.topo=topo;this.world=world;this.features=topo.feature(world,world.objects.countries).features.filter(f=>f.properties?.name!=='Antarctica');const geoms=world.objects.countries.geometries;const allNeighbors=topo.neighbors(geoms);const idIndex=new Map(geoms.map((g,i)=>[String(g.id),i]));const keep=new Set(this.features.map(f=>String(f.id)));const oldToNew=new Map();this.features.forEach((f,i)=>oldToNew.set(idIndex.get(String(f.id)),i));this.neighbors=this.features.map(f=>{const old=idIndex.get(String(f.id));return (allNeighbors[old]||[]).filter(n=>keep.has(String(geoms[n].id))).map(n=>oldToNew.get(n)).filter(Number.isInteger)});this.projection=d3.geoNaturalEarth1().fitExtent([[18,18],[1382,682]],{type:'FeatureCollection',features:this.features});this.path=d3.geoPath(this.projection);this.render();return {features:this.features,neighbors:this.neighbors}}
  render(){this.countriesG.innerHTML='';this.paths=[];this.features.forEach((f,i)=>{const p=document.createElementNS('http://www.w3.org/2000/svg','path');p.setAttribute('d',this.path(f));p.setAttribute('class','country');p.dataset.index=i;p.dataset.name=f.properties?.name||'';p.addEventListener('click',()=>this.select(i,true));this.countriesG.appendChild(p);this.paths[i]=p});this.update(true)}
  update(force=false){if(!this.features)return;this.paths.forEach((p,i)=>{const ownerName=this.sim.territoryOwner.get(i);const owner=this.sim.nations.get(ownerName);const original=this.sim.nations.get(this.features[i].properties?.name);const supported=owner?.viewers.size>0;const atwar=this.sim.campaigns.some(c=>c.target===i||c.attacker===ownerName);p.style.fill=supported?owner.color:(ownerName!==original?.name?owner?.color:'#64746b');p.classList.toggle('supported',supported||ownerName!==original?.name);p.classList.toggle('atwar',atwar);p.classList.toggle('selected',i===this.selected)});this.drawCampaigns();this.drawLabels()}
  drawLabels(){this.labelsG.innerHTML='';const active=[...this.sim.nations.values()].filter(n=>n.alive&&n.viewers.size>0).slice(0,12);for(const n of active){const idx=[...n.territories][0];if(idx==null)continue;const c=this.path.centroid(this.features[idx]);if(!Number.isFinite(c[0]))continue;const t=document.createElementNS('http://www.w3.org/2000/svg','text');t.setAttribute('x',c[0]);t.setAttribute('y',c[1]);t.setAttribute('text-anchor','middle');t.setAttribute('class','countryLabel');t.textContent=n.name.toUpperCase();this.labelsG.appendChild(t)}}
  drawCampaigns(){this.warG.innerHTML='';for(const c of this.sim.campaigns){const f=this.features[c.target];if(!f)continue;const bbox=this.path.bounds(f),cent=this.path.centroid(f),w=Math.max(1,bbox[1][0]-bbox[0][0]),h=Math.max(1,bbox[1][1]-bbox[0][1]);const clipId='clip-'+c.id.replace(/[^a-z0-9]/gi,'');const clip=document.createElementNS('http://www.w3.org/2000/svg','clipPath');clip.id=clipId;const cp=document.createElementNS('http://www.w3.org/2000/svg','path');cp.setAttribute('d',this.path(f));clip.appendChild(cp);this.warG.appendChild(clip);const r=document.createElementNS('http://www.w3.org/2000/svg','rect');r.setAttribute('x',bbox[0][0]);r.setAttribute('y',bbox[0][1]);r.setAttribute('width',w*(c.progress/100));r.setAttribute('height',h);r.setAttribute('fill',this.sim.nations.get(c.attacker)?.color||'#fff');r.setAttribute('fill-opacity','.72');r.setAttribute('clip-path',`url(#${clipId})`);r.setAttribute('class','warOverlay');this.warG.appendChild(r);const x=bbox[0][0]+w*(c.progress/100);const line=document.createElementNS('http://www.w3.org/2000/svg','line');line.setAttribute('x1',x);line.setAttribute('x2',x);line.setAttribute('y1',bbox[0][1]);line.setAttribute('y2',bbox[1][1]);line.setAttribute('clip-path',`url(#${clipId})`);line.setAttribute('class','frontLine');this.warG.appendChild(line);const dot=document.createElementNS('http://www.w3.org/2000/svg','circle');dot.setAttribute('cx',cent[0]);dot.setAttribute('cy',cent[1]);dot.setAttribute('r',c.phase==='SIEGE'||c.phase==='BREAKTHROUGH'?10:5);dot.setAttribute('class',c.phase==='SIEGE'||c.phase==='BREAKTHROUGH'?'siegeRing':'strategic');this.warG.appendChild(dot)}}
  select(i,user=false){this.selected=i;this.update();if(user)this.sim.emit('select',{index:i,nation:this.sim.nations.get(this.sim.territoryOwner.get(i))})}
  focusJoin(nation,viewer){const idx=[...nation.territories][0]??nation.home;const p=this.paths[idx];if(!p)return;this.select(idx);p.classList.remove('join-flash');void p.getBBox();p.classList.add('join-flash');const b=p.getBBox(),cx=b.x+b.width/2,cy=b.y+b.height/2,k=Math.min(5.5,Math.max(1.55,Math.min(1100/Math.max(40,b.width),520/Math.max(30,b.height))));this.viewport.style.transition='transform .65s cubic-bezier(.2,.8,.2,1)';this.viewport.style.transformOrigin='0 0';this.viewport.style.transform=`translate(${700-cx*k}px,${350-cy*k}px) scale(${k})`;clearTimeout(this.flashTimer);this.flashTimer=setTimeout(()=>{p.classList.remove('join-flash');this.viewport.style.transform='translate(0px,0px) scale(1)'},2600)}
}
