export const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
export const fmt=n=>n>=1e6?(n/1e6).toFixed(1)+'M':n>=1e3?(n/1e3).toFixed(1)+'K':Math.round(n).toString();
const hash=s=>{let h=2166136261;for(const c of s)h=Math.imul(h^c.charCodeAt(0),16777619);return h>>>0};
export const colorFor=name=>`hsl(${hash(name)%360} 58% 48%)`;

export class Simulation{
  constructor(){this.speed=1;this.paused=false;this.gameOver=false;this.nations=new Map();this.territoryOwner=new Map();this.viewers=new Map();this.followed=new Set();this.campaigns=[];this.cooldowns=new Map();this.listeners=new Set();this.now=0}
  init(features,neighbors){this.features=features;this.neighbors=neighbors;this.nations.clear();this.territoryOwner.clear();this.viewers.clear();this.followed.clear();this.campaigns=[];this.cooldowns.clear();this.now=0;this.gameOver=false;features.forEach((f,i)=>{const name=f.properties?.name||`Nation ${f.id}`;this.nations.set(name,{name,color:colorFor(name),home:i,territories:new Set([i]),viewers:new Set(),fuel:0,army:80+Math.random()*70,manpower:90+Math.random()*90,supply:45,industry:15+Math.random()*15,warSupport:35,command:0,mobilization:0,readiness:0,likes:0,contribution:0,alive:true});this.territoryOwner.set(i,name)});this.emit('init')}
  on(fn){this.listeners.add(fn);return()=>this.listeners.delete(fn)} emit(type,data={}){this.listeners.forEach(fn=>fn({type,...data}))}
  nation(name){if(!name)return null;const q=name.trim().toLowerCase();return [...this.nations.values()].find(n=>n.name.toLowerCase()===q)||[...this.nations.values()].find(n=>n.name.toLowerCase().startsWith(q))||null}
  livePower(n){return Math.round(n.viewers.size*180+n.fuel*7+n.army*1.8+n.supply*2+n.command*4+n.readiness*5+n.industry*4+n.contribution)}
  join(viewer,nationName){if(this.gameOver)return false;const n=this.nation(nationName);if(!n||!n.alive)return false;const old=this.viewers.get(viewer);if(old&&old!==n.name)this.nations.get(old)?.viewers.delete(viewer);this.viewers.set(viewer,n.name);n.viewers.add(viewer);n.fuel+=18;n.manpower+=12;n.command+=8;n.mobilization+=4;n.warSupport+=2;n.contribution+=30;this.emit('join',{viewer,nation:n});this.emit('feed',{text:`${viewer} joined ${n.name}. Live power is rising.`});return true}
  event(viewer,type,value=1){if(this.gameOver)return false;const nationName=this.viewers.get(viewer);if(!nationName)return false;const n=this.nations.get(nationName);if(!n?.alive)return false;
    if(type==='like'){const count=clamp(value,1,500);n.likes+=count;n.fuel+=count*.42;n.manpower+=count*.11;n.supply+=count*.08;n.command+=count*.025;n.contribution+=count*.18}
    if(type==='follow'){if(this.followed.has(viewer))return false;this.followed.add(viewer);n.fuel+=42;n.manpower+=38;n.supply+=28;n.industry+=7;n.command+=18;n.mobilization+=12;n.readiness+=9;n.warSupport+=8;n.contribution+=150;this.emit('feed',{text:`${viewer} followed: ${n.name} receives a major development boost.`})}
    if(type==='share'){n.fuel+=14;n.supply+=22;n.industry+=2.5;n.command+=5;n.contribution+=45}
    if(type==='rose'){n.fuel+=8;n.manpower+=16;n.army+=7;n.supply+=5;n.contribution+=25}
    if(type==='gift'){const coins=clamp(value,1,100000);const scale=Math.sqrt(coins);n.fuel+=scale*2.4;n.supply+=scale*1.8;n.manpower+=scale*1.7;n.army+=scale*.9;n.command+=scale*.75;n.mobilization+=scale*.35;n.readiness+=scale*.35;n.warSupport+=scale*.2;n.contribution+=coins*.45;const c=this.campaigns.find(c=>c.attacker===n.name||c.defender===n.name);if(c){const surge=clamp(Math.log10(coins+10)*3,3,18);if(c.attacker===n.name)c.surgeA=Math.max(c.surgeA||0,surge);else c.surgeD=Math.max(c.surgeD||0,surge);this.emit('feed',{text:`Gift surge! ${n.name} gains ${c.attacker===n.name?'offensive':'defensive'} momentum.`})}}
    this.normalize(n);this.emit('support',{viewer,nation:n,event:type,value});return true}
  normalize(n){n.fuel=clamp(n.fuel,0,250);n.supply=clamp(n.supply,0,250);n.command=clamp(n.command,0,120);n.mobilization=clamp(n.mobilization,0,100);n.readiness=clamp(n.readiness,0,100);n.warSupport=clamp(n.warSupport,0,100);n.industry=clamp(n.industry,0,100);n.army=Math.max(0,n.army);n.manpower=Math.max(0,n.manpower)}
  tick(dt){if(this.paused||this.gameOver)return;dt*=this.speed;this.now+=dt;for(const n of this.nations.values()){if(!n.alive)continue;const active=n.viewers.size>0;if(active){const recruit=Math.min(n.manpower,dt*(.3+n.industry*.012+n.viewers.size*.08));n.manpower-=recruit;n.army+=recruit*.72;n.supply+=dt*(.45+n.industry*.018+n.viewers.size*.05);n.fuel+=dt*(.08*n.viewers.size);n.command+=dt*(.08*n.viewers.size);n.mobilization+=dt*(.06*n.viewers.size+n.fuel*.0007);n.readiness+=dt*(.045*n.viewers.size+n.mobilization*.0009);n.industry+=dt*.01*n.viewers.size}else{n.supply+=dt*.08;n.army+=dt*.015}this.normalize(n)}
    this.updateCampaigns(dt);this.tryWars();this.cooldowns.forEach((v,k)=>{if(v<=this.now)this.cooldowns.delete(k)});this.emit('tick')}
  hasAttack(name){return this.campaigns.some(c=>c.attacker===name)}
  adjacentEnemyTerritories(n){const out=new Set();for(const t of n.territories){for(const nb of this.neighbors[t]||[]){if(this.territoryOwner.get(nb)!==n.name)out.add(nb)}}return [...out]}
  tryWars(){if(this.campaigns.length>=4)return;for(const n of this.nations.values()){if(!n.alive||n.viewers.size===0||this.hasAttack(n.name)||this.cooldowns.has(n.name))continue;if(n.fuel<62||n.command<34||n.mobilization<48||n.readiness<40||n.army<95)continue;const targets=this.adjacentEnemyTerritories(n);if(!targets.length)continue;if(Math.random()>.015*this.speed)continue;targets.sort((a,b)=>this.defenseOf(a)-this.defenseOf(b));this.startCampaign(n.name,targets[0])}}
  defenseOf(t){const owner=this.nations.get(this.territoryOwner.get(t));if(!owner)return 1;return owner.army/(Math.max(1,owner.territories.size))+owner.supply*.35+owner.warSupport*.25+owner.viewers.size*18}
  startCampaign(attacker,target){const a=this.nations.get(attacker);const defender=this.territoryOwner.get(target);if(!a||defender===attacker)return false;const d=this.nations.get(defender);a.fuel-=25;a.command-=18;a.supply-=15;a.mobilization=Math.max(0,a.mobilization-8);this.campaigns.push({id:crypto.randomUUID?.()||Math.random().toString(36),attacker,defender,target,progress:0,phase:'MOBILIZING',surgeA:0,surgeD:0});this.emit('warstart',{attacker:a,defender:d,target});this.emit('feed',{text:`${attacker} begins a campaign against ${defender}.`});return true}
  updateCampaigns(dt){for(let i=this.campaigns.length-1;i>=0;i--){const c=this.campaigns[i],a=this.nations.get(c.attacker),d=this.nations.get(c.defender);if(!a?.alive||!d?.alive||a.viewers.size===0){c.progress-=dt*2.2;if(c.progress<=-12){this.abort(c,'support collapsed');this.campaigns.splice(i,1)}continue}const shareA=Math.max(25,a.army/Math.max(1,a.territories.size)),shareD=Math.max(20,d.army/Math.max(1,d.territories.size));const liveA=1+a.viewers.size*.13+a.readiness*.004+(c.surgeA||0)*.025,liveD=1+d.viewers.size*.16+d.warSupport*.004+(c.surgeD||0)*.03;const fuelOk=a.fuel>2&&a.supply>2;a.fuel=Math.max(0,a.fuel-dt*(.8+shareA*.002));a.supply=Math.max(0,a.supply-dt*(.65+shareA*.0018));d.supply=Math.max(0,d.supply-dt*(.25+shareD*.001));const balance=(shareA*liveA)/(shareD*liveD+1);let delta=(balance-.78)*dt*1.7;if(!fuelOk)delta-=dt*2.8;c.progress=clamp(c.progress+delta,-15,100);a.army=Math.max(1,a.army-dt*(.08+shareD*.0018));d.army=Math.max(1,d.army-dt*(.07+shareA*.0016));c.surgeA=Math.max(0,(c.surgeA||0)-dt*.8);c.surgeD=Math.max(0,(c.surgeD||0)-dt*.8);c.phase=c.progress<12?'MOBILIZING':c.progress<38?'BORDER CLASH':c.progress<67?'SIEGE':c.progress<88?'BREAKTHROUGH':'OCCUPATION';if(c.progress>=100){this.capture(c);this.campaigns.splice(i,1)}}}
  abort(c,reason){this.cooldowns.set(c.attacker,this.now+18);this.emit('feed',{text:`${c.attacker} abandons the campaign: ${reason}.`});this.emit('warend',{campaign:c})}
  capture(c){const a=this.nations.get(c.attacker),d=this.nations.get(c.defender);if(!a||!d)return;this.territoryOwner.set(c.target,a.name);a.territories.add(c.target);d.territories.delete(c.target);a.warSupport=clamp(a.warSupport+7,0,100);a.readiness=clamp(a.readiness-8,0,100);d.warSupport=clamp(d.warSupport-12,0,100);this.cooldowns.set(a.name,this.now+8);if(d.territories.size===0){d.alive=false;d.viewers.forEach(v=>this.viewers.delete(v));d.viewers.clear();this.emit('feed',{text:`${d.name} has fallen. ${a.name} annexes its last territory.`})}else this.emit('feed',{text:`${a.name} captures territory from ${d.name}.`});this.emit('capture',{campaign:c,attacker:a,defender:d,target:c.target});this.checkVictory()}
  checkVictory(){const owners=new Set(this.territoryOwner.values());if(owners.size===1){const winner=this.nations.get([...owners][0]);this.gameOver=true;this.paused=true;this.campaigns=[];this.emit('victory',{winner})}}
  resetOwnership(){this.features.forEach((f,i)=>{const name=f.properties?.name||`Nation ${f.id}`;this.territoryOwner.set(i,name)});for(const n of this.nations.values()){n.territories=new Set([n.home]);n.viewers.clear();n.fuel=0;n.command=0;n.mobilization=0;n.readiness=0;n.likes=0;n.contribution=0;n.alive=true;n.army=80+Math.random()*70;n.manpower=90+Math.random()*90;n.supply=45;n.industry=15+Math.random()*15;n.warSupport=35}this.viewers.clear();this.followed.clear();this.campaigns=[];this.cooldowns.clear();this.gameOver=false;this.paused=false;this.now=0;this.emit('reset')}
}
