(() => {
  'use strict';

  const ASSET_ROOT = '../kingdom-war-2/';
  const WORLD = { w: 1920, h: 1080 };
  const WORLD_TILT = .72;
  const TEAM_DEFS = [
    ['RED', '#f04f49', 'Crimson Crown', 280, 270],
    ['BLUE', '#2b9ff2', 'Azure League', 460, 610],
    ['GREEN', '#31c665', 'Verdant Realm', 975, 535],
    ['YELLOW', '#f0bd28', 'Golden Principality', 980, 285],
    ['PURPLE', '#a665e8', 'Violet Empire', 1350, 315],
    ['ORANGE', '#f18736', 'Amber Isles', 1510, 760]
  ];
  const BUILD_SCALE = { castle:.48,keep:.43,house_a:.42,house_b:.42,house_c:.42,farm:.46,warehouse:.44,market:.43,windmill:.43,barracks:.44,forge:.44,stable:.44,watchtower:.42,stone_tower:.42,church:.42,silo:.42,wall:.4,gate:.4 };
  const BUILD_COST = { house_a:[35,8],house_b:[35,8],house_c:[35,8],farm:[28,5],warehouse:[50,25],market:[55,20],windmill:[70,30],barracks:[80,45],forge:[75,40],stable:[65,25],watchtower:[45,38],stone_tower:[30,70],church:[65,55],silo:[55,20] };
  const ROLE_SPRITES = { farmer:['villagers','Peasant'],builder:['villagers','Worker'],lumberjack:['villagers','Worker'],miner:['villagers','Worker'],merchant:['villagers','NobleMan'],colonist:['villagers','VillagerWoman'],civilian:['villagers','VillagerMan'],guard:['humans','ShieldMan'],infantry:['humans','SwordMan'],archer:['humans','ArcherMan'],cavalry:['humans','HorseMan'] };
  const VILLAGE_NAMES = ['Ravenford','Stonehaven','Oakwatch','Dawnmere','Brightwater','Wolfpine','Highfield','Moonbrook','Northpass','Ironwood','Goldmeadow','Westharbor'];
  const SUPPORT_STEPS = [500,2000,5000,10000];
  const params = new URLSearchParams(location.search);
  const mode = params.get('mode') === 'live' ? 'live' : 'test';
  const canvas = document.querySelector('#world');
  const ctx = canvas.getContext('2d', { alpha:false });
  const state = {
    seed: Math.floor(Math.random()*1e9), time:0, year:1, kingdoms:[], agents:[], armies:[], roads:[], members:new Map(), history:[], vote:null,
    buildings:{}, folk:{}, tintedBuildings:{}, tintedFolk:{}, folkManifest:null, terrain:null, terrainGrid:null, territory:null, territoryDirty:true, territoryAt:0, hudAt:0, events:[], selected:null, last:performance.now(), fps:60,
    camera:{x:WORLD.w/2,y:WORLD.h/2,z:.55,tx:WORLD.w/2,ty:WORLD.h/2,tz:.55,manualUntil:0,event:null}, nextEvent:45, nextVote:25, nextDiplomacy:20
  };

  const $ = s => document.querySelector(s);
  const clamp = (v,a,b) => Math.max(a,Math.min(b,v));
  const rand = (a,b) => a+Math.random()*(b-a);
  const pick = a => a[(Math.random()*a.length)|0];
  const dist = (a,b) => Math.hypot(a.x-b.x,a.y-b.y);
  const keyUser = v => String(v||'Viewer').trim().toLowerCase();
  const fmt = n => n>=1000?`${(n/1000).toFixed(1)}K`:String(Math.max(0,Math.floor(n)));
  const hash = (x,y,s=state.seed) => { let n=(x*374761393+y*668265263+s*69069)|0;n=(n^(n>>13))*1274126177;return ((n^(n>>16))>>>0)/4294967295; };
  const smooth = t => t*t*(3-2*t);
  function noise(x,y,scale=90){const X=Math.floor(x/scale),Y=Math.floor(y/scale),fx=smooth(x/scale-X),fy=smooth(y/scale-Y);const a=hash(X,Y),b=hash(X+1,Y),c=hash(X,Y+1),d=hash(X+1,Y+1);return (a+(b-a)*fx)*(1-fy)+(c+(d-c)*fx)*fy;}
  function fbm(x,y){return noise(x,y,190)*.52+noise(x,y,83)*.3+noise(x,y,34)*.18;}
  const CONTINENTS = [
    [[75,250],[120,170],[205,105],[330,100],[430,155],[470,235],[425,300],[370,320],[335,395],[280,370],[230,315],[145,315],[92,280]],
    [[330,365],[385,382],[425,430],[395,465],[350,420]],
    [[395,445],[490,435],[550,500],[548,610],[505,760],[435,930],[390,790],[370,625]],
    [[465,95],[535,70],[590,125],[565,225],[500,245],[455,175]],
    [[770,245],[840,185],[930,170],[1000,190],[1080,145],[1230,130],[1400,150],[1565,205],[1660,285],[1620,360],[1510,410],[1390,375],[1305,430],[1215,390],[1130,420],[1050,360],[965,370],[900,325],[805,320]],
    [[865,375],[1015,350],[1115,425],[1110,555],[1035,735],[955,760],[885,650],[850,505]],
    [[1095,410],[1180,405],[1245,475],[1195,540],[1115,500]],
    [[1215,425],[1320,420],[1390,500],[1340,580],[1280,535]],
    [[1370,465],[1450,500],[1495,590],[1450,650],[1395,585]],
    [[1425,710],[1530,675],[1645,715],[1705,795],[1650,870],[1510,885],[1405,820]],
    [[1730,790],[1775,760],[1800,820],[1760,875]],
    [[1110,745],[1140,720],[1160,790],[1125,850]],
    [[1600,390],[1620,330],[1640,385],[1620,445]]
  ];
  const MOUNTAIN_RANGES = [
    [[205,150],[230,230],[265,320],[300,390]],
    [[470,470],[475,570],[455,690],[430,830]],
    [[900,300],[970,285],[1050,300]],
    [[1190,405],[1270,390],[1360,410],[1430,425]],
    [[1470,230],[1540,270],[1580,330]],
    [[975,540],[990,630],[1015,700]]
  ];
  function pointInPolygon(x,y,poly){let inside=false;for(let i=0,j=poly.length-1;i<poly.length;j=i++){const a=poly[i],b=poly[j];if(((a[1]>y)!==(b[1]>y))&&(x<(b[0]-a[0])*(y-a[1])/(b[1]-a[1])+a[0]))inside=!inside;}return inside;}
  function segmentDistance(x,y,a,b){const dx=b[0]-a[0],dy=b[1]-a[1],l=dx*dx+dy*dy||1,t=clamp(((x-a[0])*dx+(y-a[1])*dy)/l,0,1);return Math.hypot(x-(a[0]+dx*t),y-(a[1]+dy*t));}
  function coastDistance(x,y){let best=1e9,inside=false;for(const poly of CONTINENTS){if(pointInPolygon(x,y,poly))inside=true;for(let i=0;i<poly.length;i++)best=Math.min(best,segmentDistance(x,y,poly[i],poly[(i+1)%poly.length]));}return inside?best:-best;}
  function ridgeStrength(x,y){let best=1e9;for(const line of MOUNTAIN_RANGES)for(let i=1;i<line.length;i++)best=Math.min(best,segmentDistance(x,y,line[i-1],line[i]));return clamp(1-best/46,0,1);}
  function coastShape(x,y){return coastDistance(x,y)+(fbm(x,y)-.5)*58+(noise(x+220,y-170,26)-.5)*18;}
  function heightAt(x,y){const coast=coastShape(x,y);if(coast<0)return -.08-clamp(-coast/150,0,.32);return .06+clamp(coast/220,0,.25)+ridgeStrength(x,y)*.32+(noise(x+90,y-45,46)-.5)*.06;}
  function rawTerrainAt(x,y){const coast=coastShape(x,y),lat=Math.abs(y/WORLD.h-.5)*2,m=fbm(x+500,y-300),ridge=ridgeStrength(x,y);if(coast<-38)return 'ocean';if(coast<0)return 'coast';if(lat>.84||ridge>.8)return 'snow';if(ridge>.34)return 'mountain';const desert=(x>835&&x<1115&&y>410&&y<570)||(x>1110&&x<1245&&y>405&&y<530)||(x>1430&&x<1685&&y>720&&y<855)||(x>1270&&x<1480&&y>265&&y<370);if(desert&&m<.63)return 'desert';if(m>.54&&lat<.78)return 'forest';return 'grass';}
  const TERRAIN_NAMES=['ocean','coast','grass','forest','desert','mountain','snow'];
  function terrainAt(x,y){const grid=state.terrainGrid;if(!grid)return rawTerrainAt(x,y);const gx=clamp(Math.floor(x/WORLD.w*grid.w),0,grid.w-1),gy=clamp(Math.floor(y/WORLD.h*grid.h),0,grid.h-1);return TERRAIN_NAMES[grid.data[gy*grid.w+gx]];}
  function land(x,y){return !['ocean','coast'].includes(terrainAt(x,y));}
  function nearestLand(x,y){if(land(x,y))return{x,y};for(let r=10;r<220;r+=10)for(let a=0;a<Math.PI*2;a+=.35){const p={x:clamp(x+Math.cos(a)*r,20,WORLD.w-20),y:clamp(y+Math.sin(a)*r,20,WORLD.h-20)};if(land(p.x,p.y)&&terrainAt(p.x,p.y)!=='mountain')return p;}return{x:WORLD.w/2,y:WORLD.h/2};}
  function toast(text){const n=document.createElement('div');n.className='toast';n.textContent=text;$('#toasts').appendChild(n);setTimeout(()=>n.remove(),3300);}
  function history(text){state.history.unshift({year:state.year,text});state.history.splice(7);$('#historyRows').innerHTML=state.history.slice(0,5).map(h=>`<div class="history-row"><b>Year ${h.year} — </b>${escapeHtml(h.text)}</div>`).join('');}
  function escapeHtml(v){return String(v).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':'&quot;',"'":"&#39;"}[m]));}
  function eventBanner(type,title,text,focus){$('#eventType').textContent=type;$('#eventTitle').textContent=title;$('#eventText').textContent=text;$('#eventCard').classList.remove('hidden');setTimeout(()=>$('#eventCard').classList.add('hidden'),5000);if(focus)directCamera(focus.x,focus.y,.95,7);}
  function directCamera(x,y,z=.9,seconds=7){state.camera.event={until:state.time+seconds};state.camera.tx=x;state.camera.ty=y;state.camera.tz=z;}

  async function image(src){return new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=reject;img.src=src;});}
  function teamTint(img,color){
    const out=document.createElement('canvas');out.width=img.width;out.height=img.height;const c=out.getContext('2d',{willReadFrequently:true});c.drawImage(img,0,0);const data=c.getImageData(0,0,out.width,out.height),rgb=color.match(/\w\w/g).map(v=>parseInt(v,16));
    for(let i=0;i<data.data.length;i+=4){const r=data.data[i],g=data.data[i+1],b=data.data[i+2];if(data.data[i+3]>10&&b>r*1.08&&b>g*1.04){const light=clamp((r+g+b)/510,.24,1.15),shade=Math.max(.45,b/255);data.data[i]=clamp(rgb[0]*light*shade,0,255);data.data[i+1]=clamp(rgb[1]*light*shade,0,255);data.data[i+2]=clamp(rgb[2]*light*shade,0,255);}}
    c.putImageData(data,0,0);return out;
  }
  async function loadAssets(){
    const [bm,fm]=await Promise.all([fetch(`${ASSET_ROOT}assets/buildings/manifest.json`).then(r=>r.json()),fetch(`${ASSET_ROOT}assets/minifolks/manifest.json`).then(r=>r.json())]);
    state.folkManifest=fm;
    await Promise.all(Object.entries(bm).map(async([name,d])=>state.buildings[name]=await image(`${ASSET_ROOT}${d.file}`)));
    const wanted=new Set(Object.values(ROLE_SPRITES).map(([g,n])=>`${g}:${n}`));
    await Promise.all([...wanted].map(async token=>{const[g,n]=token.split(':'),def=fm.groups[g].characters[n];state.folk[token]=await image(`${ASSET_ROOT}${fm.groups[g].path}${def.file}`);}));
    for(const [key,color] of TEAM_DEFS){for(const [name,img] of Object.entries(state.buildings))state.tintedBuildings[`${key}:${name}`]=teamTint(img,color);for(const [name,img] of Object.entries(state.folk))state.tintedFolk[`${key}:${name}`]=teamTint(img,color);}
  }

  function makeTerrain(){
    const low=document.createElement('canvas');low.width=320;low.height=180;const c=low.getContext('2d'),im=c.createImageData(low.width,low.height);
    const colors={ocean:[15,55,82],coast:[32,104,127],grass:[101,157,91],forest:[50,111,70],desert:[196,166,103],mountain:[126,120,105],snow:[220,228,216]};
    for(let y=0;y<low.height;y++)for(let x=0;x<low.width;x++){const wx=x/low.width*WORLD.w,wy=y/low.height*WORLD.h,t=rawTerrainAt(wx,wy),p=(y*low.width+x)*4,col=colors[t],relief=noise(wx-14,wy-18,52)-noise(wx+14,wy+18,52),light=clamp(.94+relief*.46+(t==='snow'?.08:0),.72,1.16),grain=(noise(wx,wy,18)-.5)*9;im.data[p]=clamp(col[0]*light+grain,0,255);im.data[p+1]=clamp(col[1]*light+grain,0,255);im.data[p+2]=clamp(col[2]*light+grain,0,255);im.data[p+3]=255;}c.putImageData(im,0,0);
    const out=document.createElement('canvas');out.width=WORLD.w;out.height=WORLD.h;const o=out.getContext('2d');o.imageSmoothingEnabled=true;o.drawImage(low,0,0,out.width,out.height);
    o.save();o.lineCap='round';for(const line of MOUNTAIN_RANGES){o.strokeStyle='rgba(72,66,57,.28)';o.lineWidth=18;o.beginPath();o.moveTo(line[0][0],line[0][1]);for(let i=1;i<line.length;i++)o.lineTo(line[i][0],line[i][1]);o.stroke();o.strokeStyle='rgba(238,229,202,.2)';o.lineWidth=5;o.stroke();}o.restore();
    const rivers=[[[285,225],[305,300],[330,395]],[[505,520],[455,555],[390,585]],[[990,650],[980,530],[975,390]],[[1280,365],[1380,375],[1490,360]],[[1320,430],[1390,455],[1460,475]]];o.save();o.lineCap='round';o.strokeStyle='rgba(103,190,211,.62)';o.lineWidth=4;for(const river of rivers){o.beginPath();o.moveTo(river[0][0],river[0][1]);for(let i=1;i<river.length;i++)o.lineTo(river[i][0],river[i][1]);o.stroke();}o.restore();
    const grid={w:160,h:90,data:new Uint8Array(160*90)};for(let gy=0;gy<grid.h;gy++)for(let gx=0;gx<grid.w;gx++)grid.data[gy*grid.w+gx]=TERRAIN_NAMES.indexOf(rawTerrainAt((gx+.5)/grid.w*WORLD.w,(gy+.5)/grid.h*WORLD.h));state.terrainGrid=grid;
    state.terrain=out;state.territory=document.createElement('canvas');state.territory.width=240;state.territory.height=135;
  }

  function createSettlement(k,name,x,y,capital=false){
    const p=nearestLand(x,y),s={id:`s${k.id}-${k.settlements.length}`,name,x:p.x,y:p.y,capital,level:capital?'Capital':'Village',population:capital?18:6,popCap:capital?30:12,buildings:[],danger:0};k.settlements.push(s);
    const initial=capital?['castle','house_a','house_b','house_c','farm','farm','warehouse']:['keep','house_a','farm','warehouse'];
    initial.forEach((type,i)=>addBuilding(k,s,type,true,i));state.territoryDirty=true;history(`${k.name} founded ${name}.`);return s;
  }
  function addBuilding(k,s,type,instant=false,slot=null){
    if(!state.buildings[type])return null;const n=slot??s.buildings.length,a=n*2.399+rand(-.22,.22),r=type==='castle'||type==='keep'?0:45+Math.sqrt(n)*20+rand(-8,8);const b={id:`b${k.id}-${s.id}-${Date.now()}-${n}`,type,x:s.x+Math.cos(a)*r,y:s.y+Math.sin(a)*r,done:instant,progress:instant?1:0,buildTime:rand(7,13)};b.y=clamp(b.y,20,WORLD.h-20);b.x=clamp(b.x,20,WORLD.w-20);s.buildings.push(b);if(!instant){const builder=k.agents.find(a=>a.role==='builder'&&!a.assignment);if(builder){builder.assignment=b;builder.target={x:b.x,y:b.y};builder.action='walk';}}return b;
  }
  function spawnAgent(k,s,role='civilian',at){const p=at||{x:s.x+rand(-18,18),y:s.y+rand(-12,12)},a={id:`a${k.id}-${k.agentSeq++}`,kingdom:k,settlement:s,role,x:p.x,y:p.y,target:null,speed:role==='cavalry'?42:rand(18,28),action:'idle',phase:rand(0,10),wait:rand(1,5),hp:100,assignment:null};k.agents.push(a);state.agents.push(a);return a;}
  function seedKingdoms(){
    TEAM_DEFS.forEach(([key,color,name,x,y],id)=>{const k={id,key,color,name,settlements:[],agents:[],agentSeq:0,resources:{food:330,wood:260,stone:160,gold:80,iron:20,knowledge:5},military:18,happiness:72,influence:0,support:0,rewards:new Set(),members:new Set(),relations:new Map(),alive:true,priority:'balanced',lastBuild:0,lastVillage:0,lastWar:0};state.kingdoms.push(k);const s=createSettlement(k,`${key[0]}${key.slice(1).toLowerCase()}hold`,x,y,true);['farmer','farmer','farmer','builder','lumberjack','miner','merchant','guard','civilian','civilian','civilian','civilian'].forEach(role=>spawnAgent(k,s,role));});
    for(const a of state.kingdoms)for(const b of state.kingdoms)if(a!==b)a.relations.set(b.id,Math.floor(rand(-12,18)));
  }

  function kingdomPop(k){return k.settlements.reduce((n,s)=>n+s.population,0);}
  function kingdomPower(k){return kingdomPop(k)*1.5+k.military*2+k.settlements.length*18+k.resources.gold*.06;}
  function buildCounts(k){const c={};for(const s of k.settlements)for(const b of s.buildings)if(b.done)c[b.type]=(c[b.type]||0)+1;return c;}
  function nearestSettlement(k,p){return k.settlements.filter(s=>s.population>0).sort((a,b)=>dist(a,p)-dist(b,p))[0];}
  function walkAgent(a,dt){if(!a.target)return false;const dx=a.target.x-a.x,dy=a.target.y-a.y,d=Math.hypot(dx,dy);if(d<3){a.x=a.target.x;a.y=a.target.y;a.target=null;a.action='idle';return true;}const step=Math.min(d,a.speed*dt);a.x+=dx/d*step;a.y+=dy/d*step;a.action='walk';return false;}
  function routine(a,dt){
    if(walkAgent(a,dt)){if(a.role==='colonist'&&a.colony){foundVillage(a);return;}if(a.role==='merchant'&&a.trade){completeTrade(a);return;}if(a.assignment){a.action='work';a.wait=3;}}
    if(a.target)return;a.wait-=dt;if(a.wait>0)return;
    const s=a.settlement;if(!s)return;
    if(a.assignment&&!a.assignment.done){a.target={x:a.assignment.x,y:a.assignment.y};a.action='walk';a.wait=2;return;}
    const role=a.role;
    if(role==='farmer'){const farm=s.buildings.find(b=>b.type==='farm'&&b.done),store=s.buildings.find(b=>b.type==='warehouse'&&b.done);a.target=farm&&Math.random()<.65?farm:store||{x:s.x,y:s.y};}
    else if(role==='lumberjack'){a.target={x:s.x+rand(-120,120),y:s.y+rand(-90,90)};if(terrainAt(a.target.x,a.target.y)!=='forest')a.target={x:s.x+rand(-55,55),y:s.y+rand(-45,45)};}
    else if(role==='miner'){a.target={x:s.x+rand(-130,130),y:s.y+rand(-100,100)};}
    else if(['guard','infantry','archer','cavalry'].includes(role)){a.target={x:s.x+rand(-65,65),y:s.y+rand(-48,48)};}
    else a.target={x:s.x+rand(-45,45),y:s.y+rand(-34,34)};
    a.action='walk';a.wait=rand(2,5);
  }

  function updateKingdom(k,dt){
    const c=buildCounts(k),pop=kingdomPop(k),mult=1+(k.support>=500?.05:0)+(k.support>=2000?.1:0);
    k.resources.food+=((c.farm||0)*.7*mult-pop*.035)*dt;k.resources.wood+=((c.windmill||0)*.18+(k.agents.filter(a=>a.role==='lumberjack').length*.16)*mult)*dt;k.resources.stone+=k.agents.filter(a=>a.role==='miner').length*.08*dt;k.resources.gold+=((c.market||0)*.2+(c.warehouse||0)*.04)*dt;
    k.resources.food=Math.max(0,k.resources.food);k.happiness=clamp(k.happiness+(k.resources.food>pop*2?.012:-.08)*dt,20,100);
    for(const s of k.settlements){for(const b of s.buildings)if(!b.done){b.progress+=dt/b.buildTime;if(b.progress>=1){b.done=true;b.progress=1;const builder=k.agents.find(a=>a.assignment===b);if(builder)builder.assignment=null;eventBanner('CONSTRUCTION',`${s.name}: ${b.type.replace('_',' ')} completed`,`${k.key} continues to grow.`,b);}}
      if(s.population<s.popCap&&k.resources.food>pop*1.8&&k.happiness>45&&Math.random()<dt*.012){s.population++;k.resources.food-=2;if(k.agents.length<36)spawnAgent(k,s,pick(['civilian','farmer','builder']));}
    }
    k.lastBuild-=dt;k.lastVillage-=dt;k.lastWar-=dt;
    if(k.lastBuild<=0){const cap=k.settlements.reduce((n,s)=>n+s.popCap,0),food=k.resources.food;let type=food<pop*2.5?'farm':pop>=cap-3?pick(['house_a','house_b','house_c']):pop>35&&!(c.barracks)?'barracks':pick(['market','warehouse','windmill','forge','stable','watchtower']);const cost=BUILD_COST[type]||[40,20];if(k.resources.wood>=cost[0]&&k.resources.stone>=cost[1]){const s=pick(k.settlements);k.resources.wood-=cost[0];k.resources.stone-=cost[1];addBuilding(k,s,type,false);if(type.startsWith('house'))s.popCap+=5;k.lastBuild=rand(7,13);}else k.lastBuild=4;}
    if(k.lastVillage<=0&&pop>30+k.settlements.length*14&&k.settlements.length<4&&k.resources.food>180){sendColonists(k);k.lastVillage=55;}
  }

  function findExpansion(k){const home=pick(k.settlements);for(let i=0;i<120;i++){const a=rand(0,Math.PI*2),r=rand(150,290),p=nearestLand(home.x+Math.cos(a)*r,home.y+Math.sin(a)*r);if(dist(p,home)>130&&terrainAt(p.x,p.y)!=='mountain'&&state.kingdoms.every(o=>o===k||o.settlements.every(s=>dist(s,p)>115)))return p;}return null;}
  function sendColonists(k){const p=findExpansion(k);if(!p)return;const home=k.settlements[0],a=spawnAgent(k,home,'colonist',{x:home.x,y:home.y});a.target=p;a.speed=31;a.colony={x:p.x,y:p.y,name:VILLAGE_NAMES[(k.id*3+k.settlements.length+state.year)%VILLAGE_NAMES.length]};k.resources.food-=70;k.resources.wood-=65;history(`${k.name} sent colonists toward ${a.colony.name}.`);eventBanner('NEW EXPEDITION',`${k.key} colonists depart`,a.colony.name,a);}
  function foundVillage(a){const k=a.kingdom,c=a.colony,s=createSettlement(k,c.name,c.x,c.y,false);a.colony=null;a.role='builder';a.settlement=s;k.resources.food+=25;state.roads.push({a:k.settlements[0],b:s,k});eventBanner('NEW SETTLEMENT',`${c.name} founded`,`${k.name} established a new village.`,s);}
  function routeIsLand(a,b){let landSamples=0;for(let i=0;i<=20;i++){const t=i/20;if(land(a.x+(b.x-a.x)*t,a.y+(b.y-a.y)*t))landSamples++;}return landSamples>=18;}
  function planLandRoute(a,b){
    const cell=48,cols=Math.ceil(WORLD.w/cell),rows=Math.ceil(WORLD.h/cell),key=(x,y)=>y*cols+x,start={x:clamp(Math.floor(a.x/cell),0,cols-1),y:clamp(Math.floor(a.y/cell),0,rows-1)},goal={x:clamp(Math.floor(b.x/cell),0,cols-1),y:clamp(Math.floor(b.y/cell),0,rows-1)},open=[start],came=new Map(),cost=new Map([[key(start.x,start.y),0]]),dirs=[[1,0],[-1,0],[0,1],[0,-1],[1,1],[1,-1],[-1,1],[-1,-1]];
    let found=null,loops=0;while(open.length&&loops++<5000){open.sort((u,v)=>(cost.get(key(u.x,u.y))+Math.hypot(goal.x-u.x,goal.y-u.y))-(cost.get(key(v.x,v.y))+Math.hypot(goal.x-v.x,goal.y-v.y)));const cur=open.shift();if(Math.abs(cur.x-goal.x)<=1&&Math.abs(cur.y-goal.y)<=1){found=cur;break;}for(const[dX,dY]of dirs){const nx=cur.x+dX,ny=cur.y+dY;if(nx<0||ny<0||nx>=cols||ny>=rows)continue;const wx=(nx+.5)*cell,wy=(ny+.5)*cell,t=terrainAt(wx,wy);if(t==='ocean'||t==='coast')continue;const nk=key(nx,ny),step=(dX&&dY?1.42:1)*(t==='mountain'?2.8:t==='forest'?1.35:1),next=(cost.get(key(cur.x,cur.y))||0)+step;if(next<(cost.get(nk)??1e9)){cost.set(nk,next);came.set(nk,cur);if(!open.some(q=>q.x===nx&&q.y===ny))open.push({x:nx,y:ny});}}}
    if(!found)return null;const cells=[];let cur=found;while(cur){cells.push({x:(cur.x+.5)*cell,y:(cur.y+.5)*cell});cur=came.get(key(cur.x,cur.y));}cells.reverse();const route=[{x:a.x,y:a.y}];for(let i=2;i<cells.length-1;i+=2)route.push(cells[i]);route.push({x:b.x,y:b.y});return route;
  }
  function launchTrade(a,b,viewer){const source=a.settlements[0],target=b.settlements[0];if(!routeIsLand(source,target))return false;const m=spawnAgent(a,source,'merchant');m.target={x:target.x,y:target.y};m.speed=34;m.trade={from:a,to:b,viewer};eventBanner('TRADE CARAVAN',`${a.key} → ${b.key}`,viewer?`@${viewer} opened the route.`:'Merchants carry food and gold.',m);return true;}
  function completeTrade(a){const t=a.trade;if(!t)return;t.from.resources.gold+=22;t.to.resources.food+=45;t.to.relations.set(t.from.id,clamp((t.to.relations.get(t.from.id)||0)+4,-100,100));a.trade=null;a.kingdom.agents=a.kingdom.agents.filter(x=>x!==a);state.agents=state.agents.filter(x=>x!==a);}

  function startWar(a,b){if(!a.alive||!b.alive||state.armies.some(w=>!w.done&&((w.a===a&&w.b===b)||(w.a===b&&w.b===a))))return;const source=nearestSettlement(a,b.settlements[0]),target=nearestSettlement(b,source),path=planLandRoute(source,target);if(!path){a.relations.set(b.id,Math.min(-45,a.relations.get(b.id)||0));return eventBanner('MARITIME STANDOFF',`${a.key} cannot reach ${b.key}`,'Naval invasion technology has not been developed yet.',source);}const army={id:`w${Date.now()}`,a,b,source,target,path,pathIndex:1,x:source.x,y:source.y,state:'march',strength:Math.max(8,Math.floor(a.military*.55)),troops:[],battle:0,done:false,heading:0};for(let i=0;i<Math.min(14,army.strength);i++){const row=Math.floor(i/4),col=i%4-1.5;army.troops.push({x:army.x+col*10,y:army.y+row*9,ox:col*11,oy:row*10+10,role:i%5===0?'archer':i%7===0?'cavalry':'infantry',phase:rand(0,10),battleAngle:i/14*Math.PI*2});}state.armies.push(army);a.relations.set(b.id,-100);b.relations.set(a.id,-100);history(`${a.name} declared war on ${b.name}.`);eventBanner('WAR DECLARED',`${a.key} attacks ${b.key}`,`An army marches toward ${target.name}.`,source);directCamera(source.x,source.y,1.05,10);}
  function updateArmy(w,dt){
    if(w.done)return;if(!w.a.alive||!w.b.alive){w.done=true;return;}
    if(w.state==='march'){
      const waypoint=w.path[w.pathIndex]||w.target,dx=waypoint.x-w.x,dy=waypoint.y-w.y,d=Math.hypot(dx,dy);if(d<8&&w.pathIndex<w.path.length-1){w.pathIndex++;return;}if(d<8){w.state='battle';w.battle=0;eventBanner('BATTLE',`${w.target.name} under attack`,`${w.a.key} and ${w.b.key} clash.`,w.target);for(const a of w.b.agents)if(a.settlement===w.target&&!['guard','infantry'].includes(a.role)){const refuge=w.b.settlements.find(s=>s!==w.target);if(refuge){a.target={x:refuge.x,y:refuge.y};a.action='flee';}}return;}
      const speed=terrainAt(w.x,w.y)==='mountain'?16:28,nx=dx/Math.max(d,.001),ny=dy/Math.max(d,.001);w.heading=Math.atan2(ny,nx);w.x+=nx*Math.min(d,speed*dt);w.y+=ny*Math.min(d,speed*dt);for(const t of w.troops){const tx=w.x+Math.cos(w.heading)*(-t.oy)-Math.sin(w.heading)*t.ox,ty=w.y+Math.sin(w.heading)*(-t.oy)+Math.cos(w.heading)*t.ox,smoothStep=1-Math.exp(-dt*7);t.x+=(tx-t.x)*smoothStep;t.y+=(ty-t.y)*smoothStep;}
    }else if(w.state==='battle'){
      w.battle+=dt;for(const t of w.troops){const angle=t.battleAngle+w.battle*.35,r=22+(t.oy%20),tx=w.target.x+Math.cos(angle)*r,ty=w.target.y+Math.sin(angle)*r*.55,smoothStep=1-Math.exp(-dt*5);t.x+=(tx-t.x)*smoothStep;t.y+=(ty-t.y)*smoothStep;}
      if(w.battle>14){const attack=w.strength*(.8+Math.random()*.4),defense=w.b.military*.45+w.target.population*1.2+w.target.buildings.filter(b=>['watchtower','stone_tower','wall'].includes(b.type)).length*8;if(attack>defense)conquer(w.a,w.b,w.target);else{w.a.military=Math.max(6,w.a.military-w.strength*.35);history(`${w.b.name} defended ${w.target.name}.`);}w.done=true;state.camera.event=null;}
    }
  }
  function conquer(winner,loser,s){s.population=Math.max(3,Math.floor(s.population*.72));loser.settlements=loser.settlements.filter(x=>x!==s);winner.settlements.push(s);for(const a of loser.agents.filter(a=>a.settlement===s)){a.kingdom=winner;a.role='civilian';winner.agents.push(a);}loser.agents=loser.agents.filter(a=>a.settlement!==s);s.buildings.forEach(b=>b.damage=.35);state.territoryDirty=true;history(`${s.name} was conquered by ${winner.name}; the city survived.`);eventBanner('CITY CONQUERED',`${winner.key} captured ${s.name}`,'Banners change and reconstruction begins.',s);if(!loser.settlements.length){loser.alive=false;history(`${loser.name} collapsed.`);if(state.kingdoms.filter(k=>k.alive).length===1)victory(winner);}}
  function victory(k){eventBanner('WORLD VICTORY',`${k.name} rules the world`,'A new world will begin shortly.',k.settlements[0]);setTimeout(()=>location.reload(),12000);}

  function randomEvent(){const alive=state.kingdoms.filter(k=>k.alive),k=pick(alive),events=[['GOOD HARVEST',()=>k.resources.food+=180,'Farms overflow with grain.'],['DROUGHT',()=>k.resources.food=Math.max(0,k.resources.food*.72),'Fields dry beneath a hard sun.'],['MIGRATION',()=>{const s=pick(k.settlements);s.population=Math.min(s.popCap,s.population+4);},'Families arrive from distant lands.'],['IRON DISCOVERY',()=>k.resources.iron+=55,'Miners uncover a rich vein.'],['TRADE BOOM',()=>k.resources.gold+=90,'Markets fill with foreign merchants.'],['FAMINE',()=>{const s=pick(k.settlements);s.population=Math.max(3,s.population-2);k.resources.food*=.55;},'Food stores run dangerously low.']];const e=pick(events);e[1]();history(`${k.name}: ${e[0].toLowerCase()}.`);eventBanner('WORLD EVENT',e[0],`${k.key} — ${e[2]}`,pick(k.settlements));if(['DROUGHT','FAMINE'].includes(e[0]))startVote(k,'crisis');}
  function diplomacy(){const alive=state.kingdoms.filter(k=>k.alive),a=pick(alive),b=pick(alive.filter(k=>k!==a));if(!b)return;let rel=a.relations.get(b.id)||0;rel=clamp(rel+rand(-6,7),-100,100);a.relations.set(b.id,rel);b.relations.set(a.id,rel);if(rel>55&&Math.random()<.35){history(`${a.name} and ${b.name} signed a trade pact.`);launchTrade(a,b);}else if(rel<-62&&a.lastWar<=0&&state.year>8&&Math.random()<.32){startWar(a,b);a.lastWar=55;}}

  function member(username){return state.members.get(keyUser(username));}
  function team(key){const token=String(key||'').replace(/^!/,'').toUpperCase();return state.kingdoms.find(k=>k.key===token||k.name.toUpperCase()===token);}
  function join(username,key){if(member(username))return toast(`@${username} already supports ${member(username).kingdom.key}`);const k=team(key)||state.kingdoms.filter(k=>k.alive).sort((a,b)=>a.members.size-b.members.size)[0];if(!k)return;const m={username:String(username).slice(0,24),kingdom:k,activity:0,role:null};state.members.set(keyUser(username),m);k.members.add(keyUser(username));k.influence+=2;toast(`@${username} joined ${k.key}`);eventBanner('NEW SUPPORTER',`@${username} → ${k.key}`,`${k.name} gains influence.`,k.settlements[0]);}
  function roleCheck(m){if(m.role)return;const roles=[[18,'Architect'],[35,'Merchant'],[55,'Governor'],[80,'General'],[120,'Priest'],[170,'King / Queen']];const unlocked=roles.filter(([n])=>m.activity>=n).at(-1);if(unlocked){m.role=unlocked[1];history(`@${m.username} became ${m.role} of ${m.kingdom.name}.`);toast(`👑 @${m.username} — ${m.role}`);}}
  function likes(username,count=1){const m=member(username);if(!m)return toast(`@${username}: choose a kingdom first`);const k=m.kingdom,old=k.support,n=clamp(Number(count)||1,1,100000);k.support+=n;k.influence+=n/100;m.activity+=Math.min(15,n/100);for(const step of SUPPORT_STEPS)if(old<step&&k.support>=step&&!k.rewards.has(step)){k.rewards.add(step);if(step===500){k.resources.wood+=80;k.resources.food+=90;}if(step===2000)k.resources.food+=260;if(step===5000){const s=k.settlements[0];s.popCap+=8;s.population+=5;}if(step===10000){k.resources.food+=700;k.resources.wood+=550;k.resources.stone+=420;k.happiness=100;}history(`${k.name} reached ${fmt(step)} support.`);eventBanner('SUPPORT MILESTONE',`${k.key} · ${fmt(step)} likes`,step===10000?'A Golden Age begins.':'The kingdom receives a controlled boost.',k.settlements[0]);}roleCheck(m);}
  function follow(username){const m=member(username);if(!m)return toast(`@${username}: choose a kingdom first`);let seen;try{seen=new Set(JSON.parse(localStorage.getItem('wkl-followed')||'[]'));}catch{seen=new Set();}const u=keyUser(username);if(seen.has(u))return;seen.add(u);try{localStorage.setItem('wkl-followed',JSON.stringify([...seen].slice(-1000)));}catch{}const s=m.kingdom.settlements[0];s.population=Math.min(s.popCap,s.population+1);spawnAgent(m.kingdom,s,'builder');m.activity+=12;roleCheck(m);eventBanner('FOLLOW',`@${username} brought a specialist`,`${m.kingdom.key} welcomes a new builder.`,s);}
  function share(username){const m=member(username);if(!m)return toast(`@${username}: choose a kingdom first`);const others=state.kingdoms.filter(k=>k.alive&&k!==m.kingdom).sort((a,b)=>(m.kingdom.relations.get(b.id)||0)-(m.kingdom.relations.get(a.id)||0));if(others[0])launchTrade(m.kingdom,others[0],username);m.activity+=6;roleCheck(m);}
  function gift(username,name='Gift',repeat=1,meta={}){const m=member(username);if(!m)return toast(`@${username}: choose a kingdom first`);const k=m.kingdom,n=Math.max(1,Number(repeat)||1),value=Number(meta.diamonds||meta.value||0)*n,g=String(name).toLowerCase();let tier=value>=1000||/universe|dragon|lion/.test(g)?'large':value>=100||/money gun|firework|car|jet/.test(g)?'medium':'small';if(tier==='small'){k.resources.food+=55*n;k.resources.wood+=25*n;spawnAgent(k,k.settlements[0],'merchant');}else if(tier==='medium'){k.resources.wood+=180*n;k.resources.stone+=120*n;k.military+=12*n;addBuilding(k,k.settlements[0],'watchtower',false);}else{k.resources.food+=600*n;k.resources.wood+=520*n;k.resources.stone+=420*n;k.military+=45*n;k.happiness=100;for(let i=0;i<6;i++)spawnAgent(k,k.settlements[0],i%3?'infantry':'archer');}m.activity+=tier==='large'?60:tier==='medium'?25:5;roleCheck(m);eventBanner(`${tier.toUpperCase()} GIFT`,`@${username} strengthened ${k.key}`,name,k.settlements[0]);}

  function voteTemplate(k,kind){const war=state.armies.find(w=>!w.done&&(w.a===k||w.b===k));if(kind==='crisis'||k.resources.food<kingdomPop(k)*1.5)return{kind:'crisis',q:'Food reserves are falling. What is the priority?',o:[['EXPAND FARMS',()=>{k.resources.food+=160;addBuilding(k,k.settlements[0],'farm',false);}],['IMPORT FOOD',()=>{k.resources.food+=130;k.resources.gold=Math.max(0,k.resources.gold-25);}],['SEIZE FERTILE LAND',()=>{const t=state.kingdoms.filter(x=>x.alive&&x!==k).sort((a,b)=>kingdomPower(a)-kingdomPower(b))[0];if(t)startWar(k,t);}]]};if(war)return{kind:'war',q:'Our armies are mobilized. Choose the strategy.',o:[['ATTACK',()=>w.a===k?w.strength+=8:k.military+=8],['DEFEND',()=>{k.military+=8;k.resources.stone+=80;}],['PEACE',()=>w.done=true]]};return{kind:'development',q:'Choose the next civilization priority.',o:[['FARMS',()=>addBuilding(k,pick(k.settlements),'farm',false)],['ARMY',()=>k.military+=12],['CITY',()=>{const s=pick(k.settlements);s.popCap+=5;addBuilding(k,s,pick(['house_a','house_b','house_c']),false);}],['TECH',()=>k.resources.knowledge=(k.resources.knowledge||0)+20]]};}
  function startVote(k,kind){if(state.vote||!k?.alive)return;const t=voteTemplate(k,kind);state.vote={k,kind:t.kind,q:t.q,options:t.o.map(([label,run])=>({label,run,v:0})),voters:new Map(),ends:state.time+16};renderVote();$('#votePanel').classList.remove('hidden');}
  function castVote(username,choice){const v=state.vote,m=member(username);if(!v||!m||m.kingdom!==v.k)return false;const txt=String(choice).trim().toUpperCase();let i=/^\d+$/.test(txt)?Number(txt)-1:v.options.findIndex(o=>o.label.startsWith(txt));if(i<0||i>=v.options.length)return false;const old=v.voters.get(keyUser(username));if(old!==undefined)v.options[old].v-=1;const weight=m.role==='King / Queen'||(m.role==='General'&&v.kind==='war')?2:1;v.voters.set(keyUser(username),i);v.options[i].v+=weight;renderVote();return true;}
  function renderVote(){const v=state.vote;if(!v)return;$('#voteColor').style.background=v.k.color;$('#voteKingdom').textContent=`${v.k.key} COUNCIL`;$('#voteQuestion').textContent=v.q;$('#voteOptions').innerHTML=v.options.map((o,i)=>`<div class="vote-option"><b>${i+1}</b><span>${o.label}</span><em>${o.v}</em></div>`).join('');}
  function finishVote(){const v=state.vote;if(!v)return;let i=0;for(let j=1;j<v.options.length;j++)if(v.options[j].v>v.options[i].v)i=j;if(!v.voters.size)i=Math.floor(Math.random()*v.options.length);v.options[i].run();history(`${v.k.name} chose ${v.options[i].label}.`);toast(`${v.k.key}: ${v.options[i].label}`);state.vote=null;$('#votePanel').classList.add('hidden');state.nextVote=state.time+42;}

  function normalize(raw){const envelope=raw&&typeof raw==='object'?raw:{},p=[envelope.data,envelope.payload,envelope.eventData].find(x=>x&&typeof x==='object')||{},e={...envelope,...p},type=String(e.type||e.event||e.eventType||'').toLowerCase(),username=String(e.username||e.uniqueId||e.user?.uniqueId||e.nickname||'Viewer');return{e,type,username};}
  function comment(username,text){const c=String(text||'').trim(),joinMatch=c.match(/^!?(RED|BLUE|GREEN|YELLOW|PURPLE|ORANGE)$/i)||c.match(/^JOIN\s+!?(RED|BLUE|GREEN|YELLOW|PURPLE|ORANGE)$/i);if(joinMatch)return join(username,joinMatch[1]);if(/^JOIN$/i.test(c))return join(username);if(castVote(username,c))return;}
  function ingest(raw){if(mode==='live'&&raw?.__test)return;const{e,type,username}=normalize(raw);if(type.includes('comment')||e.comment||e.message)return comment(username,e.comment||e.message||e.text);if(type.includes('like'))return likes(username,e.count||e.likeCount||e.repeatCount||1);if(type.includes('follow'))return follow(username);if(type.includes('share'))return share(username);if(type.includes('gift')){const d=e.giftDetails||{},g=e.gift||{},gd=e.giftData||{};return gift(username,e.giftName||d.giftName||d.name||g.name||'Gift',e.repeatCount||e.count||1,{diamonds:e.diamondCount||d.diamondCount||g.diamondCount||gd.value||0,value:e.value||gd.value||0});}}

  function updateTerritory(){if(!state.territoryDirty)return;state.territoryDirty=false;const c=state.territory.getContext('2d'),im=c.createImageData(state.territory.width,state.territory.height);for(let y=0;y<state.territory.height;y++)for(let x=0;x<state.territory.width;x++){const wx=x/state.territory.width*WORLD.w,wy=y/state.territory.height*WORLD.h,p=(y*state.territory.width+x)*4;if(!land(wx,wy))continue;let best=null,score=1e9;for(const k of state.kingdoms)if(k.alive)for(const s of k.settlements){const terrainPenalty=terrainAt(wx,wy)==='mountain'?1.5:terrainAt(wx,wy)==='forest'?1.12:1,d=Math.hypot(wx-s.x,wy-s.y)*terrainPenalty/(75+Math.sqrt(s.population)*18+s.buildings.length*4);if(d<score){score=d;best=k;}}if(best&&score<1.8){const col=best.color.match(/\w\w/g).map(v=>parseInt(v,16));im.data[p]=col[0];im.data[p+1]=col[1];im.data[p+2]=col[2];im.data[p+3]=score<1.55?50:Math.floor((1.8-score)*180);}}c.putImageData(im,0,0);}
  function screen(p){return{x:(p.x-state.camera.x)*state.camera.z+innerWidth/2,y:(p.y-state.camera.y)*state.camera.z*WORLD_TILT+innerHeight/2};}
  function visible(p,pad=80){const s=screen(p);return s.x>-pad&&s.y>-pad&&s.x<innerWidth+pad&&s.y<innerHeight+pad;}
  function drawBuilding(k,b){if(!visible(b,120))return;const img=state.tintedBuildings[`${k.key}:${b.type}`]||state.buildings[b.type];if(!img)return;const p=screen(b),scale=(BUILD_SCALE[b.type]||.42)*state.camera.z,w=img.width*scale,h=img.height*scale;ctx.save();ctx.globalAlpha=b.done?1:.5;ctx.fillStyle='rgba(4,12,16,.28)';ctx.beginPath();ctx.ellipse(p.x+w*.09,p.y+3,w*.39,Math.max(2,h*.09),0,0,Math.PI*2);ctx.fill();ctx.fillStyle=`${k.color}55`;ctx.beginPath();ctx.ellipse(p.x,p.y+1,w*.34,Math.max(2,h*.055),0,0,Math.PI*2);ctx.fill();ctx.drawImage(img,p.x-w/2,p.y-h*.82,w,h);if(['castle','keep'].includes(b.type)){ctx.globalAlpha=1;ctx.strokeStyle='#291b13';ctx.lineWidth=Math.max(1,state.camera.z*2);ctx.beginPath();ctx.moveTo(p.x+w*.22,p.y-h*.74);ctx.lineTo(p.x+w*.22,p.y-h*1.05);ctx.stroke();ctx.fillStyle=k.color;ctx.beginPath();ctx.moveTo(p.x+w*.22,p.y-h*1.05);ctx.lineTo(p.x+w*.48,p.y-h*.96);ctx.lineTo(p.x+w*.22,p.y-h*.87);ctx.closePath();ctx.fill();}if(b.damage){ctx.fillStyle='rgba(32,22,18,.35)';ctx.fillRect(p.x-w*.32,p.y-h*.55,w*.64,h*.35);}if(!b.done){ctx.globalAlpha=1;ctx.fillStyle='rgba(0,0,0,.7)';ctx.fillRect(p.x-18,p.y+3,36,4);ctx.fillStyle=k.color;ctx.fillRect(p.x-18,p.y+3,36*b.progress,4);}ctx.restore();}
  function drawFolk(role,x,y,action,phase,k){const map=ROLE_SPRITES[role]||ROLE_SPRITES.civilian,[group,name]=map,manifest=state.folkManifest.groups[group],def=manifest.characters[name],token=`${group}:${name}`,img=state.tintedFolk[`${k?.key}:${token}`]||state.folk[token];if(!img)return;const act=def.actions[action==='walk'?'walk':action==='work'&&def.actions.work?'work':action==='flee'?'walk':'idle']||def.actions.idle,row=act[0],count=act[1],cell=def.cell||manifest.cell||32,frame=Math.floor((state.time+phase)*8)%count,p=screen({x,y}),size=cell*state.camera.z*.72;if(size<5)return;ctx.fillStyle='rgba(2,8,12,.3)';ctx.beginPath();ctx.ellipse(p.x+1,p.y+1,size*.25,Math.max(1,size*.08),0,0,Math.PI*2);ctx.fill();ctx.drawImage(img,frame*cell,row*cell,cell,cell,p.x-size/2,p.y-size*.82,size,size);if(k){ctx.fillStyle=k.color;ctx.beginPath();ctx.arc(p.x,p.y-size*.76,Math.max(1.5,size*.085),0,Math.PI*2);ctx.fill();}}
  function draw(){
    const ocean=ctx.createLinearGradient(0,0,0,innerHeight);ocean.addColorStop(0,'#0b2638');ocean.addColorStop(1,'#123f58');ctx.fillStyle=ocean;ctx.fillRect(0,0,innerWidth,innerHeight);ctx.save();ctx.translate(innerWidth/2,innerHeight/2);ctx.scale(state.camera.z,state.camera.z*WORLD_TILT);ctx.translate(-state.camera.x,-state.camera.y);ctx.shadowColor='rgba(0,0,0,.3)';ctx.shadowBlur=18;ctx.shadowOffsetY=14;ctx.drawImage(state.terrain,0,0);ctx.shadowColor='transparent';ctx.globalAlpha=.64;ctx.imageSmoothingEnabled=true;ctx.drawImage(state.territory,0,0,WORLD.w,WORLD.h);ctx.restore();
    ctx.lineCap='round';for(const r of state.roads){const a=screen(r.a),b=screen(r.b);ctx.strokeStyle='rgba(35,27,20,.38)';ctx.lineWidth=Math.max(2,8*state.camera.z);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.bezierCurveTo((a.x+b.x)/2,a.y,(a.x+b.x)/2,b.y,b.x,b.y);ctx.stroke();ctx.strokeStyle=r.k?.color||'rgba(190,153,91,.9)';ctx.globalAlpha=.72;ctx.lineWidth=Math.max(1,3*state.camera.z);ctx.stroke();ctx.globalAlpha=1;}
    const buildings=[];for(const k of state.kingdoms)for(const s of k.settlements)for(const b of s.buildings)buildings.push({k,b});buildings.sort((a,b)=>a.b.y-b.b.y);for(const item of buildings)drawBuilding(item.k,item.b);
    if(state.camera.z>.42)for(const a of state.agents)if(visible(a,40))drawFolk(a.role,a.x,a.y,a.action,a.phase,a.kingdom);
    for(const w of state.armies)if(!w.done)for(const t of w.troops)if(visible(t,40))drawFolk(t.role,t.x,t.y,w.state==='march'?'walk':'work',t.phase,w.a);
    for(const k of state.kingdoms)for(const s of k.settlements)if(visible(s,80)){const p=screen(s);ctx.textAlign='center';ctx.font=`${s.capital?'800':'700'} ${clamp(10*state.camera.z,8,13)}px system-ui`;ctx.lineWidth=3;ctx.strokeStyle='rgba(4,13,18,.88)';ctx.strokeText(s.name,p.x,p.y-55*state.camera.z);ctx.fillStyle='#fff6d9';ctx.fillText(s.name,p.x,p.y-55*state.camera.z);if(state.camera.z>.72){ctx.font='8px system-ui';ctx.fillStyle=k.color;ctx.fillText(`${s.level.toUpperCase()} · ${s.population} POP`,p.x,p.y-43*state.camera.z);}}
  }

  function update(dt){state.time+=dt;state.year=Math.floor(state.time/5)+1;for(const k of state.kingdoms)if(k.alive)updateKingdom(k,dt);for(const a of [...state.agents])routine(a,dt);for(const w of state.armies)updateArmy(w,dt);if(state.time>=state.nextEvent){state.nextEvent=state.time+rand(42,66);randomEvent();}if(state.time>=state.nextDiplomacy){state.nextDiplomacy=state.time+rand(14,23);diplomacy();}if(!state.vote&&state.time>=state.nextVote){const alive=state.kingdoms.filter(k=>k.alive);startVote(alive[Math.floor(state.year/8)%alive.length]);}if(state.vote){$('#voteTime').textContent=`${Math.max(0,Math.ceil(state.vote.ends-state.time))}s`;if(state.time>=state.vote.ends)finishVote();}if(state.time-state.territoryAt>=4){state.territoryAt=state.time;state.territoryDirty=true;}updateTerritory();updateCamera(dt);if(state.time>=state.hudAt){state.hudAt=state.time+.35;updateHud();}}
  function worldFit(){return Math.min(innerWidth/WORLD.w,innerHeight/(WORLD.h*WORLD_TILT))*.94;}
  function updateCamera(dt){const c=state.camera,now=performance.now();if(c.event&&state.time>=c.event.until)c.event=null;if(!c.event&&now>c.manualUntil){const active=state.armies.find(w=>!w.done);if(active){c.tx=active.state==='march'?active.x:active.target.x;c.ty=active.state==='march'?active.y:active.target.y;c.tz=.92;}else{const slot=Math.floor(state.time/10)%state.kingdoms.length,k=state.kingdoms[slot],s=k.settlements[0];if(Math.floor(state.time)%40<8){c.tx=WORLD.w/2;c.ty=WORLD.h/2;c.tz=worldFit();}else{c.tx=s.x;c.ty=s.y;c.tz=.82;}}}const a=1-Math.exp(-dt*1.15);c.x+=(c.tx-c.x)*a;c.y+=(c.ty-c.y)*a;c.z+=(c.tz-c.z)*a;}
  function updateHud(){$('#year').textContent=state.year;$('#age').textContent=state.year<15?'FOUNDING AGE':state.year<50?'AGE OF KINGDOMS':'AGE OF CONQUEST';$('#viewerCount').textContent=`${state.members.size} VIEWERS`;$('#fps').textContent=`${Math.round(state.fps)} FPS`;const alive=state.kingdoms.filter(k=>k.alive).sort((a,b)=>kingdomPower(b)-kingdomPower(a));$('#rankRows').innerHTML=alive.map((k,i)=>`<div class="rank-row"><b>${i+1}</b><i style="background:${k.color}"></i><span>${k.key}</span><span>${fmt(kingdomPop(k))} pop · ${fmt(k.support)} ♥</span></div>`).join('');if(state.selected)renderCard(state.selected);}
  function renderCard(k){$('#kingdomCard').classList.remove('hidden');$('#cardColor').style.background=k.color;$('#cardName').textContent=k.name;$('#cardResources').innerHTML=Object.entries(k.resources).slice(0,6).map(([n,v])=>`<span><small>${n}</small><b>${fmt(v)}</b></span>`).join('');$('#cardStats').innerHTML=`<span><small>Population</small><b>${kingdomPop(k)}</b></span><span><small>Settlements</small><b>${k.settlements.length}</b></span><span><small>Military</small><b>${fmt(k.military)}</b></span><span><small>Influence</small><b>${fmt(k.influence)}</b></span>`;}

  function resize(){const dpr=Math.min(devicePixelRatio||1,1.5);canvas.width=Math.floor(innerWidth*dpr);canvas.height=Math.floor(innerHeight*dpr);canvas.style.width=`${innerWidth}px`;canvas.style.height=`${innerHeight}px`;ctx.setTransform(dpr,0,0,dpr,0,0);}
  function pointerWorld(e){return{x:(e.clientX-innerWidth/2)/state.camera.z+state.camera.x,y:(e.clientY-innerHeight/2)/(state.camera.z*WORLD_TILT)+state.camera.y};}
  function installInput(){let drag=null;canvas.addEventListener('pointerdown',e=>{drag={x:e.clientX,y:e.clientY,cx:state.camera.x,cy:state.camera.y};canvas.setPointerCapture(e.pointerId);state.camera.manualUntil=performance.now()+15000;});canvas.addEventListener('pointermove',e=>{if(!drag)return;state.camera.x=state.camera.tx=drag.cx-(e.clientX-drag.x)/state.camera.z;state.camera.y=state.camera.ty=drag.cy-(e.clientY-drag.y)/(state.camera.z*WORLD_TILT);});canvas.addEventListener('pointerup',e=>{if(drag&&Math.hypot(e.clientX-drag.x,e.clientY-drag.y)<6){const p=pointerWorld(e),k=state.kingdoms.filter(k=>k.alive).sort((a,b)=>Math.min(...a.settlements.map(s=>dist(s,p)))-Math.min(...b.settlements.map(s=>dist(s,p))))[0];if(k&&Math.min(...k.settlements.map(s=>dist(s,p)))<100){state.selected=k;renderCard(k);}}drag=null;});canvas.addEventListener('wheel',e=>{e.preventDefault();state.camera.tz=state.camera.z=clamp(state.camera.z*(e.deltaY>0?.88:1.13),.36,1.7);state.camera.manualUntil=performance.now()+15000;},{passive:false});$('#homeCamera').onclick=()=>{state.camera.tx=WORLD.w/2;state.camera.ty=WORLD.h/2;state.camera.tz=worldFit();state.camera.manualUntil=performance.now()+10000;};$('#zoomIn').onclick=()=>state.camera.tz=clamp(state.camera.tz*1.2,.36,1.7);$('#zoomOut').onclick=()=>state.camera.tz=clamp(state.camera.tz*.82,.36,1.7);$('#cardClose').onclick=()=>{state.selected=null;$('#kingdomCard').classList.add('hidden');};$('#historyToggle').onclick=()=>$('#historyPanel').classList.toggle('collapsed');}
  function installTest(){document.documentElement.dataset.mode=mode;$('#modeLabel').textContent=mode==='live'?'LIVE MODE':'TEST MODE';$('#statusDot').classList.toggle('live',mode==='live');if(mode==='live')return;$('#testToggle').onclick=()=>$('#testPanel').classList.toggle('collapsed');$('#goLive').onclick=()=>{const u=new URL(location.href);u.searchParams.set('mode','live');location.href=u.href;};document.querySelectorAll('[data-test]').forEach(b=>b.onclick=()=>{const username=$('#testUser').value||'TestViewer',kingdom=$('#testKingdom').value,act=b.dataset.test;if(act==='join')return ingest({__test:true,type:'comment',username,comment:`!${kingdom}`});if(!member(username))join(username,kingdom);if(act==='chat')return ingest({__test:true,type:'comment',username,comment:'Hello kingdom!'});if(act==='vote'){if(!state.vote)startVote(member(username).kingdom);return ingest({__test:true,type:'comment',username,comment:'1'});}if(act==='likes')return ingest({__test:true,type:'like',username,count:500});if(act==='follow')return ingest({__test:true,type:'follow',username});if(act==='share')return ingest({__test:true,type:'share',username});if(act==='small')return ingest({__test:true,type:'gift',username,giftName:'Rose',diamondCount:1});if(act==='medium')return ingest({__test:true,type:'gift',username,giftName:'Money Gun',diamondCount:500});if(act==='large')return ingest({__test:true,type:'gift',username,giftName:'Universe',diamondCount:1500});if(act==='war'){const k=member(username).kingdom,rival=state.kingdoms.find(r=>r!==k&&r.alive&&planLandRoute(k.settlements[0],r.settlements[0]));if(rival)startWar(k,rival);else toast('No reachable rival on this continent');}});}
  function connectBridge(){if(mode!=='live')return;const bridge=params.get('bridge')||'',token=params.get('token')||localStorage.getItem('wkl-bridge-token')||'';if(params.get('token'))localStorage.setItem('wkl-bridge-token',params.get('token'));if(!token){$('#modeLabel').textContent='LIVE · BRIDGE URL NEEDED';return;}const base=bridge.replace(/\/$/,'');const es=new EventSource(`${base}/bridge/events?token=${encodeURIComponent(token)}`);es.onopen=()=>$('#modeLabel').textContent='LIVE · TIKFINITY';es.onmessage=e=>{try{ingest(JSON.parse(e.data));}catch(error){console.warn(error);}};es.onerror=()=>$('#modeLabel').textContent='LIVE · RECONNECTING';}
  function loop(now){const dt=Math.min(.05,(now-state.last)/1000);state.last=now;state.fps=state.fps*.92+(1/Math.max(dt,.001))*.08;update(dt);draw();requestAnimationFrame(loop);}
  async function boot(){try{resize();makeTerrain();await loadAssets();seedKingdoms();installInput();installTest();connectBridge();updateTerritory();state.camera.z=state.camera.tz=worldFit();$('#loading').style.opacity='0';setTimeout(()=>$('#loading').remove(),450);history('Six autonomous kingdoms entered the world.');toast('The living world has begun');if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});window.WorldKingdomsLive={state,ingest,join,likes,follow,share,gift,startVote,castVote,version:window.__WKL_VERSION__};requestAnimationFrame(loop);}catch(error){console.error(error);$('#loading').innerHTML=`<b>STARTUP ERROR</b><span>${escapeHtml(error.message)}</span>`;}}
  addEventListener('resize',resize);boot();
})();
