(() => {
'use strict';
const VERSION='6.8-consolidated-runtime',AI=1/20,SORT=.14,MAXDT=.05,PEACE=6,WAR=10,FIRES=8;
const HOUSES=new Set(['house_a','house_b','house_c']),SCALE={warehouse:.72,stable:.88};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),rand=(a,b)=>a+Math.random()*(b-a),pick=a=>a[(Math.random()*a.length)|0];
const toast=m=>{const h=document.querySelector('#toast');if(!h)return;const e=document.createElement('div');e.className='toast';e.textContent=m;h.appendChild(e);setTimeout(()=>e.remove(),2800)};
const cap=k=>Math.max(4,(k?.buildings||[]).reduce((n,b)=>n+(b.__v68Dead||b.hp<=0?0:b.type==='castle'?4:b.type==='keep'?6:HOUSES.has(b.type)?4:0),0));
const syncCap=k=>{if(k){k.popCap=cap(k);k.pop=Math.min(k.pop,k.popCap)}};
const activeWar=(sim,id)=>(sim.wars||[]).find(w=>!w.done&&(w.a===id||w.b===id))||null;
const nextFrame=()=>new Promise(r=>requestAnimationFrame(r));

async function staffFarms(sim,k){if(!k?.alive||!sim.spawnFarmWorker)return;for(const b of k.buildings.filter(x=>x.type==='farm'&&!x.__v68Dead&&x.hp>0)){if(k.farmers.some(f=>f.fixedBuilding===b.id))continue;if(!k.farmers.some(f=>!f.fixedBuilding))break;await sim.spawnFarmWorker(k,b)}}
function ground(b,r){if(!b)return;if(b._foundation){b._foundation.visible=false;b._foundation.alpha=0}if(b._shadow){b._shadow.visible=false;b._shadow.alpha=0}if(b._sprite){b._sprite.anchor?.set?.(.5,1);b._sprite.y=Math.round(b.sy+(b.type==='farm'?0:1));b._sprite.roundPixels=true;const f=SCALE[b.type];if(f&&!b.__v68ScaleTimer){b.__v68ScaleTimer=true;setTimeout(()=>{if(!b._sprite||b._sprite.destroyed)return;const base=r.buildingScale?.(b.type,b._sprite.texture);if(Number.isFinite(base)&&base>0)b._sprite.scale.set(base*f);else b._sprite.scale.set(b._sprite.scale.x*f,b._sprite.scale.y*f);b._sprite.y=Math.round(b.sy+1);r.entities&&(r.entities.sortDirty=true)},1550)}}}
function installRoads(sim,r){r.redrawSettlementGround=function(s=sim){const g=this.settlement;if(!g)return;g.clear();for(const k of s.kingdoms||[]){if(!k.alive)continue;const[cx,cy]=s.iso(...k.capital);g.poly([cx,cy-8,cx+16,cy,cx,cy+8,cx-16,cy]).fill({color:0xb99a68,alpha:.34});const nodes=[{x:cx,y:cy+3}],bs=k.buildings.filter(b=>b.type!=='castle'&&!b.__v68Dead&&b.hp>0).sort((a,b)=>Math.hypot(a.sx-cx,a.sy-cy)-Math.hypot(b.sx-cx,b.sy-cy));for(const b of bs){const end={x:b.sx,y:b.sy+3};let st=nodes[0],bd=1e9;for(const n of nodes){const d=Math.hypot(end.x-n.x,end.y-n.y);if(d<bd){bd=d;st=n}}const mx=(st.x+end.x)/2,my=(st.y+end.y)/2;g.poly([st.x,st.y,mx,my,end.x,end.y]).stroke({color:0x8f724f,width:4,alpha:.24});g.poly([st.x,st.y,mx,my,end.x,end.y]).stroke({color:0xc6aa76,width:1.5,alpha:.6});nodes.push(end);if(b.type==='market')g.circle(b.sx,b.sy+2,7).fill({color:0xd1b679,alpha:.38})}}};r.redrawSettlementGround(sim)}
function installCard(sim,r){const gs=()=>Math.min(innerWidth/r.w.mapWidth,innerHeight/r.w.mapHeight)*1.04,th=()=>Math.max(gs()*1.32,innerWidth<600?.70:.74);r.isKingdomDetailVisible=k=>{if(!k?.alive||!r.root||r.root.scale.x<th())return false;const p=r.kingdomScreenPosition?.(k);return!!p&&Math.hypot(p[0]-innerWidth*.5,p[1]-innerHeight*.48)<Math.min(230,innerWidth*.38)};r.syncKingdomDetail=()=>{const c=document.querySelector('#kingdomCard');if(!c||!r.root||r.root.scale.x<th()){c?.classList.add('hidden');return}let best=null,d=1e9;for(const k of sim.kingdoms){if(!k.alive)continue;const p=r.kingdomScreenPosition?.(k);if(!p)continue;const q=Math.hypot(p[0]-innerWidth*.5,p[1]-innerHeight*.48);if(q<d){d=q;best=k}}if(!best||d>Math.min(230,innerWidth*.38)){c.classList.add('hidden');return}sim.selected=best;sim.updateSelected?.()};const x=document.querySelector('#closeCard');if(x&&!x.dataset.v68){x.dataset.v68='1';x.onclick=()=>document.querySelector('#kingdomCard')?.classList.add('hidden')}}

function installEconomy(sim,r,S){sim.isBuildableCell=function(x,y,t='house_a'){if(!this.land(x,y)||this.isRiver(x,y))return false;const b=this.biome(x,y);if(!['grass','forest','desert'].includes(b)||t==='farm'&&b!=='grass')return false;return this.coastDistance(x,y)>=(t==='castle'?4:2)&&this.neigh(x,y).length>=3};
const add=sim.addBuilding.bind(sim);sim.addBuilding=async function(...a){const b=await add(...a);if(!b)return b;ground(b,this.r);syncCap(a[0]);await staffFarms(this,a[0]);this.r.entities&&(this.r.entities.sortDirty=true);return b};
sim.population=async function(k){syncCap(k);if(this.age-k.lastPop>=5&&k.pop<k.popCap&&k.resources.food>=45){k.lastPop=this.age;k.resources.food-=32;k.pop++;await this.syncCitizens(k)}await staffFarms(this,k)};
sim.giftPopulation=async function(k,n){syncCap(k);k.pop=Math.min(k.popCap,k.pop+Math.max(0,n|0));await this.syncCitizens(k);await staffFarms(this,k)};
sim.buildAI=async function(k){if(this.age-k.lastBuild<6)return;syncCap(k);const c=t=>k.buildings.filter(b=>b.type===t&&!b.__v68Dead&&b.hp>0).length;let t,cost;if(k.popCap-k.pop<2&&k.resources.wood>65){t=pick(['house_a','house_b','house_c']);cost={wood:55,stone:8}}else if(c('farm')<Math.ceil(k.pop/9)&&k.resources.wood>55){t='farm';cost={wood:45,stone:4}}else if(c('warehouse')<Math.ceil(k.territory.size/14)&&k.resources.wood>85&&k.resources.stone>30){t='warehouse';cost={wood:70,stone:24}}else if(c('market')<2&&k.pop>12&&k.resources.wood>95){t='market';cost={wood:80,stone:18,gold:15}}else if(c('barracks')<2&&k.pop>15&&k.resources.wood>110&&k.resources.stone>45){t='barracks';cost={wood:90,stone:38}}else if(k.resources.wood>120&&k.resources.stone>55&&Math.random()<.22){t=pick(['forge','watchtower','windmill','silo','church']);cost={wood:90,stone:45,gold:10}}if(!t)return;for(const[n,v]of Object.entries(cost))if(k.resources[n]<v)return;const cell=this.findBuildCell(k,t,false);if(!cell)return;const b=await this.addBuilding(k,t,...cell,false);if(!b)return;for(const[n,v]of Object.entries(cost))k.resources[n]-=v;syncCap(k);if(HOUSES.has(t)&&k.pop<k.popCap){k.pop++;await this.syncCitizens(k)}k.lastBuild=this.age;this.r.puff?.(...this.iso(...cell));await staffFarms(this,k)};
const tick=sim.tick.bind(sim);sim.tick=async function(){if(this.__v68TickBusy){this.__v68SkippedTicks=(this.__v68SkippedTicks||0)+1;return}this.__v68TickBusy=true;try{return await tick()}catch(e){console.error('[V6.8 tick]',e)}finally{this.__v68TickBusy=false}};
if(r.P)r.addKingdom=async function(k){const t=new this.P.Text({text:k.name,style:{fontFamily:'Arial',fontSize:11,fontWeight:'700',fill:'#fff',stroke:{color:'#071015',width:3}}});t.anchor.set(.5,1);const[x,y]=this.sim.iso(...k.capital);t.position.set(x,y-72);t.zIndex=9999;this.labels.addChild(t);k._label=t};
const join=sim.join.bind(sim);S.joinQ=Promise.resolve();sim.join=function(...a){S.joinQ=S.joinQ.then(async()=>{S.pause=performance.now()+900;const k=await join(...a);if(k?.alive){for(const b of k.buildings)ground(b,r);syncCap(k);await this.syncCitizens(k);await staffFarms(this,k)}S.pause=Math.max(S.pause,performance.now()+450);return k}).catch(e=>{console.error('[V6.8 JOIN]',e);toast('JOIN recovered — please try again');return null});return S.joinQ}}

async function buildMany(sim,k,types){for(const q of types){const t=q==='house'?pick(['house_a','house_b','house_c']):q;let cell=sim.findBuildCell(k,t,false);if(!cell){sim.claimGiftLand?.(k,4);cell=sim.findBuildCell(k,t,false)}if(cell)await sim.addBuilding(k,t,...cell,false,true);await nextFrame()}syncCap(k)}
function installGifts(sim,r,S){sim.follow=function(name){const k=this.kingdomByName.get(String(name).toLowerCase());if(!k?.alive||k.followed)return;k.followed=true;k.resources.wood+=85;k.resources.stone+=35;k.resources.gold+=20;k.boostUntil=Math.max(k.boostUntil,this.age+30);toast(`🔨 ${name}: construction boom`);this.r.supportFx?.(k,'🔨',4)};S.gifts=new Map();
sim.gift=function(name,gift,repeat=1,meta={}){const id=String(name).toLowerCase(),prev=S.gifts.get(id)||Promise.resolve();const task=prev.then(async()=>{const k=this.kingdomByName.get(id);if(!k?.alive)return;const g=String(gift||'').toLowerCase(),raw=Math.max(1,Number(repeat)||1),n=Math.min(3,raw),d=Math.max(0,Number(meta.diamonds||meta.diamondCount||0));let builds=[],cit=0,land=0,icon='🎁',label='';
const add=(f,w,s,o,m,b,c,l,i,L)=>{k.resources.food+=f*n;k.resources.wood+=w*n;k.resources.stone+=s*n;k.resources.gold+=o*n;k.military+=m*n;builds=b;cit=c*n;land=l*n;icon=i;label=L};
if(/universe|dragon|castle fantasy|interstellar|phoenix/.test(g)||d*raw>=1000)add(6000,5500,5000,8000,420,['house','house','house','farm','farm','barracks','forge','market','stone_tower'],24,24,'👑','LEGENDARY HELP');
else if(g.includes('lion'))add(2600,2800,2200,4200,220,['house','house','farm','barracks','forge','watchtower'],14,15,'🦁','ROYAL HELP');
else if(g.includes('galaxy'))add(1500,1200,900,1800,90,['house','farm','barracks'],7,8,'🌌','CITY BOOST');
else if(/meteor|rocket|planet|supercar/.test(g)||d*raw>=500)add(1650,1450,980,1050,75,['house','house','farm','farm','barracks','forge'],10,13,'☄️','MEGA HELP');
else if(/private jet|yacht|whale diving|sports car|train|money gun|motorcycle|concert/.test(g)||d*raw>=200)add(720,620,430,410,32,['house','house','farm','market'],6,7,'⚡','BIG HELP');
else if(/swan|celebration|diamond tree/.test(g)||d*raw>=80)add(280,240,150,130,12,['house','farm'],3,3,'✨','INSTANT HELP');
else if(g.includes('rose')){k.resources.food+=45*raw;k.resources.gold+=12*raw;icon='🌹'}
else if(g.includes('ice cream')){k.resources.food+=70*raw;cit=raw;icon='🍦'}
else if(g.includes('coffee')||g.includes('doughnut')||g.includes('donut')){k.resources.food+=120*raw;k.resources.gold+=25*raw;icon='☕'}
else if(/paper crane|heart me|hand heart/.test(g)){k.resources.food+=180*raw;k.resources.wood+=110*raw;builds=['house'];cit=2*raw;icon='💞'}
else if(g.includes('finger heart')){k.resources.food+=90*raw;k.resources.wood+=55*raw;icon='🫰'}
else if(g.includes('perfume')){k.resources.gold+=120*raw;k.resources.stone+=45*raw;icon='✨'}
else if(g.includes('firework')){k.resources.gold+=260*raw;k.resources.wood+=180*raw;k.resources.stone+=120*raw;icon='🎆'}
else if(g.includes('tiktok')){k.resources.gold+=180*raw;k.resources.wood+=120*raw;icon='🎵'}
else{k.resources.gold+=(35+Math.max(1,d)*.8)*raw;k.resources.food+=(35+Math.max(1,d)*.5)*raw;k.resources.wood+=(25+Math.max(1,d)*.35)*raw}
if(label)k.boostUntil=Math.max(k.boostUntil,this.age+(label==='LEGENDARY HELP'?480:label==='ROYAL HELP'?300:label==='CITY BOOST'||label==='MEGA HELP'?180:label==='BIG HELP'?110:65));if(land)this.claimGiftLand?.(k,land);if(builds.length)await buildMany(this,k,builds);syncCap(k);if(cit)await this.giftPopulation(k,cit);await staffFarms(this,k);this.r.supportFx?.(k,icon,Math.min(10,3+builds.length));if(label)toast(`${name}: ${label} — instant kingdom development`);this.updateSelected?.()}).catch(e=>console.error('[V6.8 gift]',e));const wrapped=task.finally(()=>{if(S.gifts.get(id)===wrapped)S.gifts.delete(id)});S.gifts.set(id,wrapped);return wrapped}}

function wm(w){return w.__v68||(w.__v68={phase:'rally',age:0,combat:0,loss:{[w.a]:0,[w.b]:0},break:false,winner:null,loser:null,anchor:null,dir:{x:1,y:0},lastCap:-1e9})}
const arr=(S,id)=>S.guards.get(id)||[],live=(S,id,wid=null)=>arr(S,id).filter(u=>!u.dead&&(!wid||u.warId===wid));
function setAnim(r,sim,u,k){if(!u?.s?._sprite||u.dead&&k!=='death'||u.s._animKey===k)return;let a=u.s._anim[k];if(!a?.length){const team=sim.kingdoms[u.side];a=r.getUnitAnim?.(team,u.s._unit,k)||u.s._anim.idle;u.s._anim[k]=a}if(!a?.length)return;u.s._animKey=k;const sp=u.s._sprite;sp.textures=a;sp.loop=k!=='death';sp.animationSpeed=k==='walk'?(u.role==='sword'?.19:u.role==='spear'?.18:.16):k==='attack'?.19:.14;sp.tint=0xffffff;sp.gotoAndPlay(0)}
const face=(u,x)=>{if(u?.s?._sprite){const m=Math.abs(u.s._sprite.scale.x||1);u.s._sprite.scale.x=x>=u.x?m:-m}};
function patrolTarget(sim,k,u){let c=k.capital,n=0;for(const t of k.territory){const q=t.split(',').map(Number);if(!sim.isWalkableCell(...q)||sim.buildingAt?.(...q)||Math.hypot(q[0]-k.capital[0],q[1]-k.capital[1])>6)continue;if(Math.random()<1/++n)c=q}const p=sim.iso(...c);u.tx=p[0]+rand(-4,4);u.ty=p[1]+6+rand(-2,2);u.wait=rand(.2,.9)}
function makeGuard(sim,r,S,k){if(performance.now()<S.pause)return null;const i=k.__v68Seq=(k.__v68Seq||0)+1,role=i%5===0?'archer':i%3===0?'spear':'sword',unit=role==='archer'?'archer':'knight',idle=r.getUnitAnim?.(k,unit,'idle')||[];if(!idle.length)return null;const c=new r.P.Container(),sp=new r.P.AnimatedSprite(idle);sp.anchor.set(.5,.84);sp.scale.set(role==='archer'?.39:role==='spear'?.40:.41);sp.animationSpeed=.14;sp.roundPixels=true;sp.play();c.addChild(sp);c._sprite=sp;c._anim={idle};c._animKey='idle';c._unit=unit;c._role=role;if(role==='spear'){const g=new r.P.Graphics();g.poly([0,-8,12,-19]).stroke({color:0x8a5e32,width:1.2});c.addChild(g)}const p=sim.iso(...k.capital),x=p[0]+rand(-8,8),y=p[1]+8+rand(-3,3);c.position.set(x,y);c.zIndex=Math.round(y*100)+16;r.entities.addChild(c);const u={s:c,side:k.id,role,x,y,vx:x,vy:y,tx:x,ty:y,wait:0,speed:rand(16,20),hp:role==='archer'?40:role==='spear'?56:50,warId:null,group:0,slot:0,target:null,building:null,cool:rand(.1,.7),hurt:0,dead:false,deadAge:0,siege:null,civil:0};if(!S.guards.has(k.id))S.guards.set(k.id,[]);S.guards.get(k.id).push(u);patrolTarget(sim,k,u);return u}
function sep(u,peers){let x=0,y=0;for(const q of peers){if(q===u||q.dead)continue;let dx=u.x-q.x,dy=u.y-q.y,d=Math.hypot(dx,dy),m=q.side===u.side?9:5.5;if(d>.01&&d<m){const f=(m-d)/m;x+=dx/d*f;y+=dy/d*f}}return[x,y]}
function steer(sim,u){let x=0,y=0;for(const k of sim.kingdoms){if(!k.alive)continue;for(const b of k.buildings){if(b.__v68Dead||b.hp<=0)continue;let dx=u.x-b.sx,dy=u.y-(b.sy-5);if(Math.abs(dx)>24||Math.abs(dy)>22)continue;const d=Math.max(.1,Math.hypot(dx,dy)),m=b.type==='castle'?23:b.type==='farm'?15:13;if(d<m){const f=(m-d)/m;x+=dx/d*f*1.5;y+=dy/d*f*1.1}}}return[x,y]}
function move(sim,r,u,x,y,dt,speed,peers){let dx=x-u.x,dy=y-u.y,d=Math.hypot(dx,dy);if(d<.65){setAnim(r,sim,u,'idle');return true}let a=dx/d,b=dy/d,[sx,sy]=sep(u,peers),[ox,oy]=steer(sim,u);a+=sx*.7+ox;b+=sy*.7+oy;const l=Math.max(.001,Math.hypot(a,b));a/=l;b/=l;const st=Math.min(d,speed*dt);u.x+=a*st;u.y+=b*st;face(u,u.x+a*8);setAnim(r,sim,u,'walk');return d<2.2}
function geo(sim,w,u){if(!w.front)return null;const oc=u.side===w.a?w.front[0]:w.front[1],ec=u.side===w.a?w.front[1]:w.front[0],o=sim.iso(...oc),e=sim.iso(...ec);let dx=e[0]-o[0],dy=e[1]-o[1],l=Math.max(1,Math.hypot(dx,dy));dx/=l;dy/=l;const px=-dy,py=dx,mx=(o[0]+e[0])/2,my=(o[1]+e[1])/2+5,lane=(u.group-1)*13+(u.slot%2?3:-3),row=Math.floor(u.slot/2)*6;return{ex:e[0],ey:e[1]+5,rx:mx-dx*(34+row)+px*lane,ry:my-dy*(34+row)+py*lane,ax:mx-dx*(7+row*.4)+px*lane,ay:my-dy*(7+row*.4)+py*lane}}
function assign(S,w){for(const side of[w.a,w.b])live(S,side).forEach((u,i)=>{u.warId=w.id;u.group=i%3;u.slot=Math.floor(i/3);u.target=u.building=null;u.siege=null})}
function nearestBuilding(k,x,y){let bs=k.buildings.filter(b=>!b.__v68Dead&&b.hp>0&&b.owner===k.id&&b.type!=='castle');if(!bs.length)bs=k.buildings.filter(b=>!b.__v68Dead&&b.hp>0&&b.owner===k.id);return bs.sort((a,b)=>Math.hypot(a.sx-x,a.sy-y)-Math.hypot(b.sx-x,b.sy-y))[0]||null}
function loadVfx(r,S){const load=async(f,w,h,n)=>{const b=await r.P.Assets.load(f),a=[];b.source&&(b.source.scaleMode='nearest');for(let i=0;i<n;i++)a.push(new r.P.Texture({source:b.source,frame:new r.P.Rectangle(i*w,0,w,h)}));return a};Promise.all([load('assets/vfx/fire-sheet.svg',32,32,6),load('assets/vfx/destruction-sheet.svg',40,32,6),load('assets/vfx/blood-sheet.svg',32,32,5),load('assets/vfx/impact-sheet.svg',32,32,5)]).then(([fire,destroy,blood,impact])=>{S.vfx={fire,destroy,blood,impact};S.vfxReady=true}).catch(e=>console.warn('[V6.8 VFX]',e))}
function shot(r,S,k,x,y,sc=1){if(!S.vfxReady)return false;S.pool[k]||=Array.from({length:k==='blood'?10:k==='impact'?8:6},()=>{const s=new r.P.AnimatedSprite(S.vfx[k]);s.anchor.set(.5,.72);s.animationSpeed=k==='impact'?.22:k==='blood'?.2:.16;s.loop=false;s.visible=false;s.onComplete=()=>{s.visible=false;s.stop()};r.fx.addChild(s);return s});const s=S.pool[k].find(q=>!q.visible)||S.pool[k][0];s.position.set(Math.round(x),Math.round(y));s.scale.set(sc);s.alpha=1;s.visible=true;s.gotoAndPlay(0);return true}
function fire(r,S,b){if(!S.vfxReady||!b?._sprite||b.__v68Dead)return;const old=S.fires.get(b);if(old){old.until=performance.now()+6500;return}if(S.fires.size>=FIRES)return;const s=new r.P.AnimatedSprite(S.vfx.fire);s.anchor.set(.5,.88);s.animationSpeed=.15;s.loop=true;s.scale.set(b.type==='castle'?.92:.68);s.play();r.fx.addChild(s);S.fires.set(b,{s,until:performance.now()+6500})}
function kill(sim,r,S,w,u,killer){if(u.dead)return;u.dead=true;u.deadAge=0;setAnim(r,sim,u,'death');shot(r,S,'blood',u.x,u.y-3,.9);wm(w).loss[u.side]++;const v=sim.kingdoms[u.side];v.military=Math.max(2,v.military-.45);sim.kingdoms[killer].military+=.08}
function attack(sim,r,S,w,u,t,dt){if(!t||t.dead||t.side===u.side)return;const range=u.role==='archer'?25:9.5,d=Math.hypot(t.x-u.x,t.y-u.y);if(d>range)return move(sim,r,u,t.x,t.y,dt,u.role==='archer'?17:20,live(S,u.side,w.id));face(u,t.x);setAnim(r,sim,u,'attack');u.cool-=dt;if(u.cool>0)return;u.cool=u.role==='archer'?rand(.85,1.15):rand(.68,.95);t.hp-=u.role==='archer'?rand(4.5,7.5):u.role==='spear'?rand(8.5,12.5):rand(7.5,11.5);t.hurt=.12;if(Math.random()<.35)shot(r,S,'blood',t.x,t.y-3,.6);if(t.hp<=0)kill(sim,r,S,w,t,u.side)}
function attackBuilding(sim,r,S,w,u,b,dt){const enemy=u.side===w.a?w.b:w.a;if(!b||b.owner!==enemy||b.owner===u.side||b.__v68Dead||b.hp<=0){u.building=null;return}const d=Math.hypot(b.sx-u.x,b.sy+4-u.y);if(d>14)return move(sim,r,u,b.sx,b.sy+5,dt,u.role==='archer'?16:18,live(S,u.side,w.id));face(u,b.sx);setAnim(r,sim,u,'attack');u.cool-=dt;if(u.cool>0)return;u.cool=rand(.78,1.08);b.hp=Math.max(0,b.hp-(u.role==='archer'?rand(2,3.5):rand(4.5,7.5)));r.damageBuilding?.(b);fire(r,S,b);shot(r,S,'impact',b.sx+rand(-5,5),b.sy-rand(7,16),.68);if(b.hp<=0){const o=sim.kingdoms[b.owner];if(!o||o.id===u.side)return;o.buildings=o.buildings.filter(x=>x!==b);sim.releaseFarmWorker?.(o,b.id);b.__v68Dead=true;r.destroyBuilding?.(b);syncCap(o);u.building=null}}
function civilian(sim,r,S,w,u){u.civil-=AI;if(u.civil>0)return false;const e=sim.kingdoms[u.side===w.a?w.b:w.a];if(!e?.alive||e.pop<=2)return false;let v=null,d=1e9;for(const f of e.farmers){if(f.fixedBuilding||!f._sprite)continue;const q=Math.hypot(f.x-u.x,f.y-u.y);if(q<d){d=q;v=f}}if(!v||d>11)return false;u.civil=rand(1.8,2.8);e.farmers=e.farmers.filter(f=>f!==v);e.pop=Math.max(2,e.pop-1);const s=v._sprite;v._sprite=null;r.farmerSprites?.delete(v.id);shot(r,S,'blood',s.x,s.y-4,.85);S.corpses.push({s,life:1.4});return true}
function warPhase(sim,S,w,dt){const m=wm(w),A=live(S,w.a,w.id),B=live(S,w.b,w.id);if(m.break)return;if(A.length<2||B.length<2){m.age=0;return}m.age+=dt;const U=[...A,...B];if(m.phase==='rally'){const n=U.filter(u=>{const g=geo(sim,w,u);return g&&Math.hypot(u.x-g.rx,u.y-g.ry)<7}).length;if(m.age>3.6||m.age>1.2&&n/U.length>=.6){m.phase='advance';m.age=0}}else if(m.phase==='advance'){const n=U.filter(u=>{const g=geo(sim,w,u);return g&&Math.hypot(u.x-g.ax,u.y-g.ay)<8}).length;if(m.age>4.4||m.age>1.25&&n/U.length>=.45){m.phase='combat';m.age=0;m.combat=0}}else{m.combat+=dt;const la=m.loss[w.a],lb=m.loss[w.b];if(!(m.combat>=6&&la+lb>=2)&&m.combat<15)return;const winner=la+1<lb?w.a:lb+1<la?w.b:A.length!==B.length?(A.length>B.length?w.a:w.b):(sim.power(sim.kingdoms[w.a])>=sim.power(sim.kingdoms[w.b])?w.a:w.b);m.break=true;m.winner=winner;m.loser=winner===w.a?w.b:w.a;m.lastCap=sim.age;const W=live(S,winner,w.id),p=W.length?{x:W.reduce((s,u)=>s+u.x,0)/W.length,y:W.reduce((s,u)=>s+u.y,0)/W.length}:{x:sim.iso(...(winner===w.a?w.front[0]:w.front[1]))[0],y:sim.iso(...(winner===w.a?w.front[0]:w.front[1]))[1]+5};m.anchor=p;const ord=W.sort((a,b)=>(a.role==='spear'?0:a.role==='sword'?1:2)-(b.role==='spear'?0:b.role==='sword'?1:2)),rc=ord.length>=6?2:1;ord.forEach((u,i)=>{u.siege=i>=ord.length-rc?'raider':'legion'});live(S,m.loser,w.id).forEach(u=>u.siege='defender');toast(`⚔️ ${sim.kingdoms[winner].name} breaks the line — siege of ${sim.kingdoms[m.loser].name}`)}}
function anchor(sim,S,w,dt){const m=wm(w);if(!m.break||!m.anchor)return;const k=sim.kingdoms[m.loser],b=nearestBuilding(k,m.anchor.x,m.anchor.y),p=sim.iso(...k.capital),tx=b?.sx??p[0],ty=(b?.sy??p[1])+5;let dx=tx-m.anchor.x,dy=ty-m.anchor.y,d=Math.max(.001,Math.hypot(dx,dy));dx/=d;dy/=d;const st=Math.min(d,13*dt);m.anchor.x+=dx*st;m.anchor.y+=dy*st;m.dir={x:dx,y:dy}}
function updateUnits(sim,r,S,w,u,dt){const m=wm(w),peers=live(S,u.side,w.id);if(u.hurt>0){u.hurt-=dt;setAnim(r,sim,u,'hurt');return}if(!m.break){const g=geo(sim,w,u);if(!g)return;if(m.phase==='rally')return void move(sim,r,u,g.rx,g.ry,dt,20,peers);if(m.phase==='advance')return void move(sim,r,u,g.ax,g.ay,dt,21.5,peers);const enemies=live(S,u.side===w.a?w.b:w.a,w.id).filter(q=>!q.dead);let enemy=null,best=1e9;for(const q of enemies){const score=Math.hypot(q.x-u.x,q.y-u.y)+(q.load||0)*12;if(score<best){best=score;enemy=q}}if(enemy)enemy.load=(enemy.load||0)+1;return enemy?attack(sim,r,S,w,u,enemy,dt):move(sim,r,u,g.ex,g.ey,dt,18,peers)}const enemy=live(S,u.side===w.a?w.b:w.a,w.id).filter(q=>Math.hypot(q.x-u.x,q.y-u.y)<=15)[0];if(enemy)return attack(sim,r,S,w,u,enemy,dt);if(u.side===m.winner){if(u.siege==='raider'){if(civilian(sim,r,S,w,u))return;const k=sim.kingdoms[m.loser];if(!u.building||u.building.owner!==k.id||u.building.__v68Dead)u.building=nearestBuilding(k,u.x,u.y);if(u.building)return attackBuilding(sim,r,S,w,u,u.building,dt)}const legion=live(S,m.winner,w.id).filter(q=>q.siege==='legion'),i=Math.max(0,legion.indexOf(u)),cols=Math.min(3,Math.max(2,legion.length)),col=i%cols-(cols-1)/2,row=Math.floor(i/cols),px=-m.dir.y,py=m.dir.x;return void move(sim,r,u,m.anchor.x-m.dir.x*row*8.5+px*col*9.5,m.anchor.y-m.dir.y*row*8.5+py*col*9.5,dt,14.5,peers)}const k=sim.kingdoms[m.loser],p=sim.iso(...k.capital),D=live(S,k.id,w.id),i=D.indexOf(u);move(sim,r,u,p[0]+(i%3-1)*9,p[1]+8+Math.floor(i/3)*8,dt,12.5,peers);face(u,m.anchor?.x??p[0])}
function installBattle(sim,r,S){S.guards=new Map();S.next=new Map();S.clock=0;S.acc=0;S.sort=0;S.fires=new Map();S.pool={};S.corpses=[];S.vfxReady=false;S.pause=performance.now()+1200;const destroy=r.destroyBuilding?.bind(r);
const oldFarmer=r.updateFarmer?.bind(r);if(oldFarmer&&r.anim)r.updateFarmer=function(f,dx,dy){const s=f?._sprite;if(!s)return;if(f.action==='walk'){const a=Math.abs(dx)>Math.abs(dy)?dx<0?'walk_left':'walk_right':dy<0?'walk_up':'walk_down';if(this.anim[a]&&s._action!==a){s.textures=this.anim[a];s._action=a;s.animationSpeed=.18;this.applyFarmerScale?.(s,a);s.gotoAndPlay(0)}}s.position.set(f.x,f.y)};
r.startWar=function(w,s=sim){wm(w);assign(S,w)};r.endWar=function(w){for(const side of[w.a,w.b])for(const u of arr(S,side))if(u.warId===w.id&&!u.dead){u.warId=null;u.target=u.building=null;u.siege=null;patrolTarget(sim,sim.kingdoms[side],u)}};r.casualty=()=>{};r.battleFx=(x,y)=>shot(r,S,'blood',x,y,.7);r.frontImpact=(w,s=sim)=>{if(!w.front)return;const a=s.iso(...w.front[0]),b=s.iso(...w.front[1]);shot(r,S,'impact',(a[0]+b[0])/2,(a[1]+b[1])/2+4,.75)};r.damageBuilding=b=>{if(!b?._sprite)return;const q=clamp(b.hp/Math.max(1,b.maxHp),0,1);b.damageState=q<.35?2:1;b._sprite.tint=q<.35?0x886d63:0xc9ad9d;fire(r,S,b)};r.destroyBuilding=function(b,...a){if(!b)return;b.__v68Dead=true;shot(r,S,'destroy',b.sx,b.sy-8,b.type==='castle'?1.1:.9);const f=S.fires.get(b);if(f){f.s.destroy();S.fires.delete(b)}return destroy?.(b,...a)};
sim.resolveWars=function(){for(const w of this.wars){if(w.done)continue;const A=this.kingdoms[w.a],B=this.kingdoms[w.b],pair=A?.alive&&B?.alive?this.borderPair(A,B):null;if(!pair){w.done=true;r.endWar(w);continue}w.front=pair;const m=wm(w);if(!m.break||this.age-m.lastCap<3.5||!m.anchor)continue;const win=this.kingdoms[m.winner],lose=this.kingdoms[m.loser],c=[];for(const t of lose.territory){const[x,y]=t.split(',').map(Number);if(!this.neigh(x,y).some(([a,b])=>this.getOwner(a,b)===win.id))continue;const p=this.iso(x,y),d=Math.hypot(p[0]-m.anchor.x,p[1]+5-m.anchor.y);c.push({x,y,d,p})}c.sort((a,b)=>a.d-b.d);if(!c.length||c[0].d>105)continue;const q=c[0];m.lastCap=this.age;this.capture(win,lose,q.x,q.y);win.military+=.35;lose.military=Math.max(2,lose.military-.8);shot(r,S,'impact',q.p[0],q.p[1]+5,.78);r.redrawTerritories?.(this);r.redrawSettlementGround?.(this);if(q.x===lose.capital[0]&&q.y===lose.capital[1]||lose.territory.size<=1)this.eliminate(lose,win)}};
function ai(dt){S.clock+=dt;for(const k of sim.kingdoms){if(!k.alive)continue;const w=activeWar(sim,k.id),m=w?wm(w):null,desired=w?(m.break&&m.loser===k.id?4:WAR):PEACE,L=live(S,k.id);if(L.length<desired&&S.clock>=(S.next.get(k.id)||0)&&performance.now()>=S.pause){const u=makeGuard(sim,r,S,k);S.next.set(k.id,S.clock+(w?1.25:.95));if(u&&w){u.warId=w.id;const n=live(S,k.id,w.id).length;u.group=n%3;u.slot=Math.floor(n/3)}}}for(const w of sim.wars){if(w.done)continue;for(const side of[w.a,w.b])for(const u of live(S,side,w.id))u.load=0;warPhase(sim,S,w,dt);anchor(sim,S,w,dt)}for(const k of sim.kingdoms){if(!k.alive)continue;const w=activeWar(sim,k.id),A=arr(S,k.id);for(const u of A){if(u.dead){u.deadAge+=dt;continue}if(!w){u.warId=null;if(u.wait>0){u.wait-=dt;setAnim(r,sim,u,'idle')}else{if(Math.hypot(u.x-u.tx,u.y-u.ty)<3)patrolTarget(sim,k,u);move(sim,r,u,u.tx,u.ty,dt,u.speed,A)}continue}if(u.warId!==w.id){u.warId=w.id;const n=live(S,k.id,w.id).length;u.group=n%3;u.slot=Math.floor(n/3)}updateUnits(sim,r,S,w,u,dt)}}for(const[id,A]of S.guards){S.guards.set(id,A.filter(u=>{if(u.dead&&u.deadAge>3.8){u.s.destroy({children:true});return false}return true}))}}
r.updateWars=function(s,raw){const dt=clamp(Number(raw)||.016,.001,MAXDT);S.acc=Math.min(S.acc+dt,AI*2.2);let n=0;while(S.acc>=AI&&n++<2){ai(AI);S.acc-=AI}S.sort+=dt;const sort=S.sort>=SORT;if(sort)S.sort=0,void 0;const a=1-Math.exp(-22*dt);for(const[,A]of S.guards)for(const u of A){if(u.dead){u.vx=u.x;u.vy=u.y;u.s.alpha=u.deadAge<2.3?1:clamp(1-(u.deadAge-2.3)/1.3,0,1)}else{u.vx+=(u.x-u.vx)*a;u.vy+=(u.y-u.vy)*a;u.s.alpha=1;u.s._sprite&&(u.s._sprite.tint=0xffffff)}u.s.position.set(u.vx,u.vy);if(sort)u.s.zIndex=Math.round(u.vy*100)+16}S.corpses=S.corpses.filter(c=>{c.life-=dt;if(!c.s||c.s.destroyed)return false;c.s.alpha=clamp(c.life/1.1,0,1);if(c.life<=0){c.s.destroy();return false}return true});const now=performance.now();for(const[b,f]of[...S.fires]){if(!b._sprite||b.__v68Dead||now>f.until){f.s.destroy();S.fires.delete(b)}else f.s.position.set(Math.round(b.sx),Math.round(b.sy-Math.max(13,(b._sprite.height||36)*.34)))}if(sort){for(const k of s.kingdoms)for(const f of k.farmers)if(f._sprite)f._sprite.zIndex=Math.round(f.y*100)+10;r.entities&&(r.entities.sortDirty=true)}else r.entities&&(r.entities.sortDirty=false)};loadVfx(r,S)}

function install(sim){if(sim.__v68Installed)return;const r=sim.r;if(!r?.P||!r?.app||!r?.entities){setTimeout(()=>install(sim),35);return}sim.__v68Installed=true;const S=sim.__v68={};window.__BUILD_VERSION=VERSION;document.documentElement.dataset.runtime='single-runtime';document.documentElement.dataset.battleSystem='v68-consolidated';const tag=document.querySelector('.build-tag');if(tag)tag.textContent='V6.8 CONSOLIDATED';installCard(sim,r);installRoads(sim,r);installEconomy(sim,r,S);installGifts(sim,r,S);installBattle(sim,r,S);window.GodWorldDiagnostics={version:VERSION,snapshot:()=>({version:VERSION,kingdoms:sim.kingdoms.filter(k=>k.alive).length,wars:sim.wars.filter(w=>!w.done).length,guards:[...S.guards.values()].reduce((n,a)=>n+a.length,0),fires:S.fires.size,entities:r.entities.children.length,fx:r.fx.children.length,skippedTicks:sim.__v68SkippedTicks||0,trees:window.__TREE_DEPTH_READY?.count||0})};for(const k of sim.kingdoms){syncCap(k);for(const b of k.buildings)ground(b,r)}r.syncKingdomDetail?.();toast('V6.8 CONSOLIDATED loaded')}
(function wait(){const sim=window.__SIM;if(!sim?.r?.app||!sim.r.P)return setTimeout(wait,30);install(sim)})();
})();
