(() => {
  'use strict';
  const VERSION='v713-live-power-1';
  if(window.__V713_LIVE_POWER?.installed)return;
  const LIKE_POWER=10, POWER_PER_DIAMOND=100, FOLLOW_BOOST=120, BIG_THRESHOLD=1000;
  const BIG=['meteor','galaxy','lion','universe','dragon','castle fantasy','interstellar','phoenix'];
  const state=window.__V713_LIVE_POWER={installed:false,version:VERSION,likePower:10,rosePower:100,powerPerDiamond:100,bigGiftThreshold:1000,followBoostSeconds:120,events:0,combatScaling:false,conquestScaling:false,errors:[]};
  const sleep=ms=>new Promise(r=>setTimeout(r,ms));
  const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
  const getK=(sim,name)=>sim?.kingdomByName?.get?.(String(name||'').toLowerCase())||null;
  function fallback(name){const g=String(name||'').toLowerCase();if(g.includes('rose'))return 1;if(g.includes('ice cream')||g.includes('finger heart'))return 5;if(g.includes('coffee')||g.includes('doughnut')||g.includes('donut'))return 15;if(g.includes('perfume')||g.includes('firework')||g.includes('tiktok'))return 50;if(g.includes('money gun')||g.includes('train')||g.includes('motorcycle'))return 180;if(g.includes('sports car')||g.includes('yacht')||g.includes('private jet')||g.includes('whale diving'))return 600;if(BIG.some(x=>g.includes(x)))return 1500;return 1;}
  function value(gift,repeat,meta){const n=Math.max(1,Number(repeat)||1),d=Math.max(0,Number(meta?.diamonds||meta?.diamondCount||0));return Math.max(1,d||fallback(gift))*n;}
  function addPower(k,n){if(k?.alive&&Number.isFinite(n)&&n>0)k.__v713InteractionPower=Math.max(0,Number(k.__v713InteractionPower||0))+n;}
  function combatMult(sim,k){const p=Math.max(0,Number(sim.power?.(k)||0));return clamp(1+Math.log10(1+p/100)*.35,1,3);}
  function baseHp(u){return u?.role==='archer'?38:(u?.role==='spear'?54:48);}
  function strengthenGuards(sim,r){const map=r?.__v66Guards;if(!(map instanceof Map))return;for(const[id,list]of map){const k=sim.kingdoms?.[id];if(!k?.alive)continue;const mult=combatMult(sim,k);k.__v713CombatMultiplier=mult;for(const u of list||[]){if(!u||u.dead)continue;const base=baseHp(u),next=base*mult,old=Math.max(base,Number(u.__v713PowerMaxHp||base));let hp=Number.isFinite(u.__v661Hp)?u.__v661Hp:base;if(next>old)hp+=next-old;else if(next<old)hp=Math.min(hp,next);u.__v661Hp=clamp(hp,0,next);u.__v713PowerMaxHp=next;}}}
  function speedHits(sim,r){const map=r?.__v66Guards;if(!(map instanceof Map))return;const now=performance.now();for(const[id,list]of map){const k=sim.kingdoms?.[id];if(!k?.alive)continue;const mult=combatMult(sim,k);for(const u of list||[]){if(!u||u.dead||u.state!=='combat'||!Number.isFinite(u.__v661NextHit))continue;if(u.__v713SeenNextHit===u.__v661NextHit)continue;u.__v661NextHit=now+Math.max(0,u.__v661NextHit-now)/mult;u.__v713SeenNextHit=u.__v661NextHit;}}}
  async function install(){for(let i=0;i<2200;i++){const s=window.__SIM;if(s?.r&&window.__V712_ENGAGEMENT_RECOVERY?.installed&&s.__v661BattleStabilityInstalled&&typeof s.power==='function')break;await sleep(20);}const sim=window.__SIM;if(!sim?.r)throw new Error('simulation unavailable');
    const oldPower=sim.power.bind(sim);sim.power=function(k){return oldPower(k)+Math.max(0,Number(k?.__v713InteractionPower||0));};
    const oldLike=sim.like.bind(sim);sim.like=function(name,count=1){const out=oldLike(name,count),k=getK(this,name);if(k?.alive){addPower(k,Math.max(1,Number(count)||1)*LIKE_POWER);this.updateSelected?.();this.updateUI?.();}return out;};
    const oldFollow=sim.follow.bind(sim);sim.follow=function(name,...rest){const before=getK(this,name)?.followed,out=oldFollow(name,...rest),k=getK(this,name);if(k?.alive&&!before&&k.followed){k.boostUntil=Math.max(Number(k.boostUntil||0),this.age+FOLLOW_BOOST);k.lastBuild-=12;k.lastExpand-=5;k.lastPop-=4;k.resources.food+=120;k.resources.wood+=160;k.resources.stone+=80;k.resources.gold+=45;this.updateSelected?.();this.updateUI?.();}return out;};
    const oldGift=sim.gift.bind(sim);sim.gift=async function(name,gift,repeat=1,meta={}){const k=getK(this,name),v=value(gift,repeat,meta),big=v>=BIG_THRESHOLD||BIG.some(x=>String(gift||'').toLowerCase().includes(x));if(k?.alive&&big){k.__v713GiftBuildOverride=true;this.claimGiftLand?.(k,clamp(Math.round(42+Math.sqrt(v)*.7),42,95));}let out;try{out=await oldGift(name,gift,repeat,meta);}finally{if(k&&big)k.__v713GiftBuildOverride=false;}const live=getK(this,name);if(live?.alive){addPower(live,v*POWER_PER_DIAMOND);live.resources.food+=v*10;live.resources.wood+=v*8;live.resources.stone+=v*6;live.resources.gold+=v*5;const log=Math.log2(v+1);live.lastBuild-=clamp(.8+log*1.2,1,16);live.lastExpand-=clamp(.5+log*.7,.7,9);live.lastPop-=clamp(.35+log*.45,.5,6);live.boostUntil=Math.max(Number(live.boostUntil||0),this.age+clamp(25+Math.sqrt(v)*10,30,480));if(big){live.__v713Superpower=true;live.__v713MetropolisGiftAt=this.age;}state.events++;this.updateSelected?.();this.updateUI?.();}return out;};
    const oldWars=sim.r.updateWars.bind(sim.r);sim.r.updateWars=function(s,dt){strengthenGuards(s||sim,this);const out=oldWars(s,dt);speedHits(s||sim,this);return out;};state.combatScaling=true;
    const oldResolve=sim.resolveWars.bind(sim);sim.resolveWars=function(){for(const w of this.wars||[]){if(w.done)continue;const a=this.kingdoms?.[w.a],b=this.kingdoms?.[w.b];if(!a?.alive||!b?.alive)continue;const pa=Math.max(1,this.power(a)),pb=Math.max(1,this.power(b)),ratio=Math.max(pa,pb)/Math.max(1,Math.min(pa,pb));if(ratio>1.25)w.lastCapture-=clamp((ratio-1)*.55,0,1.65);}return oldResolve();};state.conquestScaling=true;
    state.installed=true;document.documentElement.dataset.livePower=VERSION;
  }
  install().catch(e=>{state.errors.push(String(e?.message||e));console.error('[v713-live-power]',e);});
})();
